# coding=utf-8
# *** WARNING: this file was generated by crd2pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from ... import _utilities
from ... import meta as _meta

__all__ = [
    'ExtensionConfigSpecClientConfigPatchArgs',
    'ExtensionConfigSpecClientConfigPatchArgsDict',
    'ExtensionConfigSpecClientConfigServicePatchArgs',
    'ExtensionConfigSpecClientConfigServicePatchArgsDict',
    'ExtensionConfigSpecClientConfigServiceArgs',
    'ExtensionConfigSpecClientConfigServiceArgsDict',
    'ExtensionConfigSpecClientConfigArgs',
    'ExtensionConfigSpecClientConfigArgsDict',
    'ExtensionConfigSpecNamespaceSelectorMatchExpressionsPatchArgs',
    'ExtensionConfigSpecNamespaceSelectorMatchExpressionsPatchArgsDict',
    'ExtensionConfigSpecNamespaceSelectorMatchExpressionsArgs',
    'ExtensionConfigSpecNamespaceSelectorMatchExpressionsArgsDict',
    'ExtensionConfigSpecNamespaceSelectorPatchArgs',
    'ExtensionConfigSpecNamespaceSelectorPatchArgsDict',
    'ExtensionConfigSpecNamespaceSelectorArgs',
    'ExtensionConfigSpecNamespaceSelectorArgsDict',
    'ExtensionConfigSpecPatchArgs',
    'ExtensionConfigSpecPatchArgsDict',
    'ExtensionConfigSpecArgs',
    'ExtensionConfigSpecArgsDict',
    'ExtensionConfigStatusConditionsArgs',
    'ExtensionConfigStatusConditionsArgsDict',
    'ExtensionConfigStatusDeprecatedV1beta1ConditionsArgs',
    'ExtensionConfigStatusDeprecatedV1beta1ConditionsArgsDict',
    'ExtensionConfigStatusDeprecatedV1beta1Args',
    'ExtensionConfigStatusDeprecatedV1beta1ArgsDict',
    'ExtensionConfigStatusDeprecatedArgs',
    'ExtensionConfigStatusDeprecatedArgsDict',
    'ExtensionConfigStatusHandlersRequestHookArgs',
    'ExtensionConfigStatusHandlersRequestHookArgsDict',
    'ExtensionConfigStatusHandlersArgs',
    'ExtensionConfigStatusHandlersArgsDict',
    'ExtensionConfigStatusArgs',
    'ExtensionConfigStatusArgsDict',
    'ExtensionConfigArgs',
    'ExtensionConfigArgsDict',
]

class ExtensionConfigSpecClientConfigPatchArgsDict(TypedDict):
    """
    clientConfig defines how to communicate with the Extension server.
    """
    ca_bundle: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    caBundle is a PEM encoded CA bundle which will be used to validate the Extension server's server certificate.
    """
    service: NotRequired[pulumi.Input[Optional['ExtensionConfigSpecClientConfigServicePatchArgs']]]
    url: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    url gives the location of the Extension server, in standard URL form
    (`scheme://host:port/path`).
    Note: Exactly one of `url` or `service` must be specified.

    The scheme must be "https".

    The `host` should not refer to a service running in the cluster; use
    the `service` field instead.

    A path is optional, and if present may be any string permissible in
    a URL. If a path is set it will be used as prefix to the hook-specific path.

    Attempting to use a user or basic auth e.g. "user:password@" is not
    allowed. Fragments ("#...") and query parameters ("?...") are not
    allowed either.
    """

@pulumi.input_type
class ExtensionConfigSpecClientConfigPatchArgs:
    def __init__(__self__, *,
                 ca_bundle: pulumi.Input[Optional[_builtins.str]] = None,
                 service: pulumi.Input[Optional['ExtensionConfigSpecClientConfigServicePatchArgs']] = None,
                 url: pulumi.Input[Optional[_builtins.str]] = None):
        """
        clientConfig defines how to communicate with the Extension server.

        :param pulumi.Input[_builtins.str] ca_bundle: caBundle is a PEM encoded CA bundle which will be used to validate the Extension server's server certificate.
        :param pulumi.Input[_builtins.str] url: url gives the location of the Extension server, in standard URL form
               (`scheme://host:port/path`).
               Note: Exactly one of `url` or `service` must be specified.
               
               The scheme must be "https".
               
               The `host` should not refer to a service running in the cluster; use
               the `service` field instead.
               
               A path is optional, and if present may be any string permissible in
               a URL. If a path is set it will be used as prefix to the hook-specific path.
               
               Attempting to use a user or basic auth e.g. "user:password@" is not
               allowed. Fragments ("#...") and query parameters ("?...") are not
               allowed either.
        """
        if ca_bundle is not None:
            pulumi.set(__self__, "ca_bundle", ca_bundle)
        if service is not None:
            pulumi.set(__self__, "service", service)
        if url is not None:
            pulumi.set(__self__, "url", url)

    @_builtins.property
    @pulumi.getter(name="caBundle")
    def ca_bundle(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        caBundle is a PEM encoded CA bundle which will be used to validate the Extension server's server certificate.
        """
        return pulumi.get(self, "ca_bundle")

    @ca_bundle.setter
    def ca_bundle(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ca_bundle", value)

    @_builtins.property
    @pulumi.getter
    def service(self) -> pulumi.Input[Optional['ExtensionConfigSpecClientConfigServicePatchArgs']]:
        return pulumi.get(self, "service")

    @service.setter
    def service(self, value: pulumi.Input[Optional['ExtensionConfigSpecClientConfigServicePatchArgs']]):
        pulumi.set(self, "service", value)

    @_builtins.property
    @pulumi.getter
    def url(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        url gives the location of the Extension server, in standard URL form
        (`scheme://host:port/path`).
        Note: Exactly one of `url` or `service` must be specified.

        The scheme must be "https".

        The `host` should not refer to a service running in the cluster; use
        the `service` field instead.

        A path is optional, and if present may be any string permissible in
        a URL. If a path is set it will be used as prefix to the hook-specific path.

        Attempting to use a user or basic auth e.g. "user:password@" is not
        allowed. Fragments ("#...") and query parameters ("?...") are not
        allowed either.
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "url", value)


class ExtensionConfigSpecClientConfigServicePatchArgsDict(TypedDict):
    """
    service is a reference to the Kubernetes service for the Extension server.
    Note: Exactly one of `url` or `service` must be specified.

    If the Extension server is running within a cluster, then you should use `service`.
    """
    name: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    name is the name of the service.
    """
    namespace: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    namespace is the namespace of the service.
    """
    path: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    path is an optional URL path and if present may be any string permissible in
    a URL. If a path is set it will be used as prefix to the hook-specific path.
    """
    port: NotRequired[pulumi.Input[Optional[_builtins.int]]]
    """
    port is the port on the service that's hosting the Extension server.
    Defaults to 443.
    Port should be a valid port number (1-65535, inclusive).
    """

@pulumi.input_type
class ExtensionConfigSpecClientConfigServicePatchArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 namespace: pulumi.Input[Optional[_builtins.str]] = None,
                 path: pulumi.Input[Optional[_builtins.str]] = None,
                 port: pulumi.Input[Optional[_builtins.int]] = None):
        """
        service is a reference to the Kubernetes service for the Extension server.
        Note: Exactly one of `url` or `service` must be specified.

        If the Extension server is running within a cluster, then you should use `service`.

        :param pulumi.Input[_builtins.str] name: name is the name of the service.
        :param pulumi.Input[_builtins.str] namespace: namespace is the namespace of the service.
        :param pulumi.Input[_builtins.str] path: path is an optional URL path and if present may be any string permissible in
               a URL. If a path is set it will be used as prefix to the hook-specific path.
        :param pulumi.Input[_builtins.int] port: port is the port on the service that's hosting the Extension server.
               Defaults to 443.
               Port should be a valid port number (1-65535, inclusive).
        """
        if name is not None:
            pulumi.set(__self__, "name", name)
        if namespace is not None:
            pulumi.set(__self__, "namespace", namespace)
        if path is not None:
            pulumi.set(__self__, "path", path)
        if port is not None:
            pulumi.set(__self__, "port", port)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        name is the name of the service.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def namespace(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        namespace is the namespace of the service.
        """
        return pulumi.get(self, "namespace")

    @namespace.setter
    def namespace(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "namespace", value)

    @_builtins.property
    @pulumi.getter
    def path(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        path is an optional URL path and if present may be any string permissible in
        a URL. If a path is set it will be used as prefix to the hook-specific path.
        """
        return pulumi.get(self, "path")

    @path.setter
    def path(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "path", value)

    @_builtins.property
    @pulumi.getter
    def port(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        port is the port on the service that's hosting the Extension server.
        Defaults to 443.
        Port should be a valid port number (1-65535, inclusive).
        """
        return pulumi.get(self, "port")

    @port.setter
    def port(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "port", value)


class ExtensionConfigSpecClientConfigServiceArgsDict(TypedDict):
    """
    service is a reference to the Kubernetes service for the Extension server.
    Note: Exactly one of `url` or `service` must be specified.

    If the Extension server is running within a cluster, then you should use `service`.
    """
    name: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    name is the name of the service.
    """
    namespace: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    namespace is the namespace of the service.
    """
    path: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    path is an optional URL path and if present may be any string permissible in
    a URL. If a path is set it will be used as prefix to the hook-specific path.
    """
    port: NotRequired[pulumi.Input[Optional[_builtins.int]]]
    """
    port is the port on the service that's hosting the Extension server.
    Defaults to 443.
    Port should be a valid port number (1-65535, inclusive).
    """

@pulumi.input_type
class ExtensionConfigSpecClientConfigServiceArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 namespace: pulumi.Input[Optional[_builtins.str]] = None,
                 path: pulumi.Input[Optional[_builtins.str]] = None,
                 port: pulumi.Input[Optional[_builtins.int]] = None):
        """
        service is a reference to the Kubernetes service for the Extension server.
        Note: Exactly one of `url` or `service` must be specified.

        If the Extension server is running within a cluster, then you should use `service`.

        :param pulumi.Input[_builtins.str] name: name is the name of the service.
        :param pulumi.Input[_builtins.str] namespace: namespace is the namespace of the service.
        :param pulumi.Input[_builtins.str] path: path is an optional URL path and if present may be any string permissible in
               a URL. If a path is set it will be used as prefix to the hook-specific path.
        :param pulumi.Input[_builtins.int] port: port is the port on the service that's hosting the Extension server.
               Defaults to 443.
               Port should be a valid port number (1-65535, inclusive).
        """
        if name is not None:
            pulumi.set(__self__, "name", name)
        if namespace is not None:
            pulumi.set(__self__, "namespace", namespace)
        if path is not None:
            pulumi.set(__self__, "path", path)
        if port is not None:
            pulumi.set(__self__, "port", port)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        name is the name of the service.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def namespace(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        namespace is the namespace of the service.
        """
        return pulumi.get(self, "namespace")

    @namespace.setter
    def namespace(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "namespace", value)

    @_builtins.property
    @pulumi.getter
    def path(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        path is an optional URL path and if present may be any string permissible in
        a URL. If a path is set it will be used as prefix to the hook-specific path.
        """
        return pulumi.get(self, "path")

    @path.setter
    def path(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "path", value)

    @_builtins.property
    @pulumi.getter
    def port(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        port is the port on the service that's hosting the Extension server.
        Defaults to 443.
        Port should be a valid port number (1-65535, inclusive).
        """
        return pulumi.get(self, "port")

    @port.setter
    def port(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "port", value)


class ExtensionConfigSpecClientConfigArgsDict(TypedDict):
    """
    clientConfig defines how to communicate with the Extension server.
    """
    ca_bundle: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    caBundle is a PEM encoded CA bundle which will be used to validate the Extension server's server certificate.
    """
    service: NotRequired[pulumi.Input[Optional['ExtensionConfigSpecClientConfigServiceArgs']]]
    url: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    url gives the location of the Extension server, in standard URL form
    (`scheme://host:port/path`).
    Note: Exactly one of `url` or `service` must be specified.

    The scheme must be "https".

    The `host` should not refer to a service running in the cluster; use
    the `service` field instead.

    A path is optional, and if present may be any string permissible in
    a URL. If a path is set it will be used as prefix to the hook-specific path.

    Attempting to use a user or basic auth e.g. "user:password@" is not
    allowed. Fragments ("#...") and query parameters ("?...") are not
    allowed either.
    """

@pulumi.input_type
class ExtensionConfigSpecClientConfigArgs:
    def __init__(__self__, *,
                 ca_bundle: pulumi.Input[Optional[_builtins.str]] = None,
                 service: pulumi.Input[Optional['ExtensionConfigSpecClientConfigServiceArgs']] = None,
                 url: pulumi.Input[Optional[_builtins.str]] = None):
        """
        clientConfig defines how to communicate with the Extension server.

        :param pulumi.Input[_builtins.str] ca_bundle: caBundle is a PEM encoded CA bundle which will be used to validate the Extension server's server certificate.
        :param pulumi.Input[_builtins.str] url: url gives the location of the Extension server, in standard URL form
               (`scheme://host:port/path`).
               Note: Exactly one of `url` or `service` must be specified.
               
               The scheme must be "https".
               
               The `host` should not refer to a service running in the cluster; use
               the `service` field instead.
               
               A path is optional, and if present may be any string permissible in
               a URL. If a path is set it will be used as prefix to the hook-specific path.
               
               Attempting to use a user or basic auth e.g. "user:password@" is not
               allowed. Fragments ("#...") and query parameters ("?...") are not
               allowed either.
        """
        if ca_bundle is not None:
            pulumi.set(__self__, "ca_bundle", ca_bundle)
        if service is not None:
            pulumi.set(__self__, "service", service)
        if url is not None:
            pulumi.set(__self__, "url", url)

    @_builtins.property
    @pulumi.getter(name="caBundle")
    def ca_bundle(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        caBundle is a PEM encoded CA bundle which will be used to validate the Extension server's server certificate.
        """
        return pulumi.get(self, "ca_bundle")

    @ca_bundle.setter
    def ca_bundle(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ca_bundle", value)

    @_builtins.property
    @pulumi.getter
    def service(self) -> pulumi.Input[Optional['ExtensionConfigSpecClientConfigServiceArgs']]:
        return pulumi.get(self, "service")

    @service.setter
    def service(self, value: pulumi.Input[Optional['ExtensionConfigSpecClientConfigServiceArgs']]):
        pulumi.set(self, "service", value)

    @_builtins.property
    @pulumi.getter
    def url(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        url gives the location of the Extension server, in standard URL form
        (`scheme://host:port/path`).
        Note: Exactly one of `url` or `service` must be specified.

        The scheme must be "https".

        The `host` should not refer to a service running in the cluster; use
        the `service` field instead.

        A path is optional, and if present may be any string permissible in
        a URL. If a path is set it will be used as prefix to the hook-specific path.

        Attempting to use a user or basic auth e.g. "user:password@" is not
        allowed. Fragments ("#...") and query parameters ("?...") are not
        allowed either.
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "url", value)


class ExtensionConfigSpecNamespaceSelectorMatchExpressionsPatchArgsDict(TypedDict):
    """
    A label selector requirement is a selector that contains values, a key, and an operator that
    relates the key and values.
    """
    key: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    key is the label key that the selector applies to.
    """
    operator: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    operator represents a key's relationship to a set of values.
    Valid operators are In, NotIn, Exists and DoesNotExist.
    """
    values: NotRequired[pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]]
    """
    values is an array of string values. If the operator is In or NotIn,
    the values array must be non-empty. If the operator is Exists or DoesNotExist,
    the values array must be empty. This array is replaced during a strategic
    merge patch.
    """

@pulumi.input_type
class ExtensionConfigSpecNamespaceSelectorMatchExpressionsPatchArgs:
    def __init__(__self__, *,
                 key: pulumi.Input[Optional[_builtins.str]] = None,
                 operator: pulumi.Input[Optional[_builtins.str]] = None,
                 values: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        A label selector requirement is a selector that contains values, a key, and an operator that
        relates the key and values.

        :param pulumi.Input[_builtins.str] key: key is the label key that the selector applies to.
        :param pulumi.Input[_builtins.str] operator: operator represents a key's relationship to a set of values.
               Valid operators are In, NotIn, Exists and DoesNotExist.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] values: values is an array of string values. If the operator is In or NotIn,
               the values array must be non-empty. If the operator is Exists or DoesNotExist,
               the values array must be empty. This array is replaced during a strategic
               merge patch.
        """
        if key is not None:
            pulumi.set(__self__, "key", key)
        if operator is not None:
            pulumi.set(__self__, "operator", operator)
        if values is not None:
            pulumi.set(__self__, "values", values)

    @_builtins.property
    @pulumi.getter
    def key(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        key is the label key that the selector applies to.
        """
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "key", value)

    @_builtins.property
    @pulumi.getter
    def operator(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        operator represents a key's relationship to a set of values.
        Valid operators are In, NotIn, Exists and DoesNotExist.
        """
        return pulumi.get(self, "operator")

    @operator.setter
    def operator(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "operator", value)

    @_builtins.property
    @pulumi.getter
    def values(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        values is an array of string values. If the operator is In or NotIn,
        the values array must be non-empty. If the operator is Exists or DoesNotExist,
        the values array must be empty. This array is replaced during a strategic
        merge patch.
        """
        return pulumi.get(self, "values")

    @values.setter
    def values(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "values", value)


class ExtensionConfigSpecNamespaceSelectorMatchExpressionsArgsDict(TypedDict):
    """
    A label selector requirement is a selector that contains values, a key, and an operator that
    relates the key and values.
    """
    key: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    key is the label key that the selector applies to.
    """
    operator: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    operator represents a key's relationship to a set of values.
    Valid operators are In, NotIn, Exists and DoesNotExist.
    """
    values: NotRequired[pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]]
    """
    values is an array of string values. If the operator is In or NotIn,
    the values array must be non-empty. If the operator is Exists or DoesNotExist,
    the values array must be empty. This array is replaced during a strategic
    merge patch.
    """

@pulumi.input_type
class ExtensionConfigSpecNamespaceSelectorMatchExpressionsArgs:
    def __init__(__self__, *,
                 key: pulumi.Input[Optional[_builtins.str]] = None,
                 operator: pulumi.Input[Optional[_builtins.str]] = None,
                 values: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        A label selector requirement is a selector that contains values, a key, and an operator that
        relates the key and values.

        :param pulumi.Input[_builtins.str] key: key is the label key that the selector applies to.
        :param pulumi.Input[_builtins.str] operator: operator represents a key's relationship to a set of values.
               Valid operators are In, NotIn, Exists and DoesNotExist.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] values: values is an array of string values. If the operator is In or NotIn,
               the values array must be non-empty. If the operator is Exists or DoesNotExist,
               the values array must be empty. This array is replaced during a strategic
               merge patch.
        """
        if key is not None:
            pulumi.set(__self__, "key", key)
        if operator is not None:
            pulumi.set(__self__, "operator", operator)
        if values is not None:
            pulumi.set(__self__, "values", values)

    @_builtins.property
    @pulumi.getter
    def key(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        key is the label key that the selector applies to.
        """
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "key", value)

    @_builtins.property
    @pulumi.getter
    def operator(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        operator represents a key's relationship to a set of values.
        Valid operators are In, NotIn, Exists and DoesNotExist.
        """
        return pulumi.get(self, "operator")

    @operator.setter
    def operator(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "operator", value)

    @_builtins.property
    @pulumi.getter
    def values(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        values is an array of string values. If the operator is In or NotIn,
        the values array must be non-empty. If the operator is Exists or DoesNotExist,
        the values array must be empty. This array is replaced during a strategic
        merge patch.
        """
        return pulumi.get(self, "values")

    @values.setter
    def values(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "values", value)


class ExtensionConfigSpecNamespaceSelectorPatchArgsDict(TypedDict):
    """
    namespaceSelector decides whether to call the hook for an object based
    on whether the namespace for that object matches the selector.
    Defaults to the empty LabelSelector, which matches all objects.
    """
    match_expressions: NotRequired[pulumi.Input[Optional[Sequence[pulumi.Input['ExtensionConfigSpecNamespaceSelectorMatchExpressionsPatchArgs']]]]]
    """
    matchExpressions is a list of label selector requirements. The requirements are ANDed.
    """
    match_labels: NotRequired[pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]]
    """
    matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
    map is equivalent to an element of matchExpressions, whose key field is "key", the
    operator is "In", and the values array contains only "value". The requirements are ANDed.
    """

@pulumi.input_type
class ExtensionConfigSpecNamespaceSelectorPatchArgs:
    def __init__(__self__, *,
                 match_expressions: pulumi.Input[Optional[Sequence[pulumi.Input['ExtensionConfigSpecNamespaceSelectorMatchExpressionsPatchArgs']]]] = None,
                 match_labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None):
        """
        namespaceSelector decides whether to call the hook for an object based
        on whether the namespace for that object matches the selector.
        Defaults to the empty LabelSelector, which matches all objects.

        :param pulumi.Input[Sequence[pulumi.Input['ExtensionConfigSpecNamespaceSelectorMatchExpressionsPatchArgs']]] match_expressions: matchExpressions is a list of label selector requirements. The requirements are ANDed.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] match_labels: matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
               map is equivalent to an element of matchExpressions, whose key field is "key", the
               operator is "In", and the values array contains only "value". The requirements are ANDed.
        """
        if match_expressions is not None:
            pulumi.set(__self__, "match_expressions", match_expressions)
        if match_labels is not None:
            pulumi.set(__self__, "match_labels", match_labels)

    @_builtins.property
    @pulumi.getter(name="matchExpressions")
    def match_expressions(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['ExtensionConfigSpecNamespaceSelectorMatchExpressionsPatchArgs']]]]:
        """
        matchExpressions is a list of label selector requirements. The requirements are ANDed.
        """
        return pulumi.get(self, "match_expressions")

    @match_expressions.setter
    def match_expressions(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['ExtensionConfigSpecNamespaceSelectorMatchExpressionsPatchArgs']]]]):
        pulumi.set(self, "match_expressions", value)

    @_builtins.property
    @pulumi.getter(name="matchLabels")
    def match_labels(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
        map is equivalent to an element of matchExpressions, whose key field is "key", the
        operator is "In", and the values array contains only "value". The requirements are ANDed.
        """
        return pulumi.get(self, "match_labels")

    @match_labels.setter
    def match_labels(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "match_labels", value)


class ExtensionConfigSpecNamespaceSelectorArgsDict(TypedDict):
    """
    namespaceSelector decides whether to call the hook for an object based
    on whether the namespace for that object matches the selector.
    Defaults to the empty LabelSelector, which matches all objects.
    """
    match_expressions: NotRequired[pulumi.Input[Optional[Sequence[pulumi.Input['ExtensionConfigSpecNamespaceSelectorMatchExpressionsArgs']]]]]
    """
    matchExpressions is a list of label selector requirements. The requirements are ANDed.
    """
    match_labels: NotRequired[pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]]
    """
    matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
    map is equivalent to an element of matchExpressions, whose key field is "key", the
    operator is "In", and the values array contains only "value". The requirements are ANDed.
    """

@pulumi.input_type
class ExtensionConfigSpecNamespaceSelectorArgs:
    def __init__(__self__, *,
                 match_expressions: pulumi.Input[Optional[Sequence[pulumi.Input['ExtensionConfigSpecNamespaceSelectorMatchExpressionsArgs']]]] = None,
                 match_labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None):
        """
        namespaceSelector decides whether to call the hook for an object based
        on whether the namespace for that object matches the selector.
        Defaults to the empty LabelSelector, which matches all objects.

        :param pulumi.Input[Sequence[pulumi.Input['ExtensionConfigSpecNamespaceSelectorMatchExpressionsArgs']]] match_expressions: matchExpressions is a list of label selector requirements. The requirements are ANDed.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] match_labels: matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
               map is equivalent to an element of matchExpressions, whose key field is "key", the
               operator is "In", and the values array contains only "value". The requirements are ANDed.
        """
        if match_expressions is not None:
            pulumi.set(__self__, "match_expressions", match_expressions)
        if match_labels is not None:
            pulumi.set(__self__, "match_labels", match_labels)

    @_builtins.property
    @pulumi.getter(name="matchExpressions")
    def match_expressions(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['ExtensionConfigSpecNamespaceSelectorMatchExpressionsArgs']]]]:
        """
        matchExpressions is a list of label selector requirements. The requirements are ANDed.
        """
        return pulumi.get(self, "match_expressions")

    @match_expressions.setter
    def match_expressions(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['ExtensionConfigSpecNamespaceSelectorMatchExpressionsArgs']]]]):
        pulumi.set(self, "match_expressions", value)

    @_builtins.property
    @pulumi.getter(name="matchLabels")
    def match_labels(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
        map is equivalent to an element of matchExpressions, whose key field is "key", the
        operator is "In", and the values array contains only "value". The requirements are ANDed.
        """
        return pulumi.get(self, "match_labels")

    @match_labels.setter
    def match_labels(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "match_labels", value)


class ExtensionConfigSpecPatchArgsDict(TypedDict):
    """
    spec is the desired state of the ExtensionConfig.
    """
    client_config: NotRequired[pulumi.Input[Optional['ExtensionConfigSpecClientConfigPatchArgs']]]
    namespace_selector: NotRequired[pulumi.Input[Optional['ExtensionConfigSpecNamespaceSelectorPatchArgs']]]
    settings: NotRequired[pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]]
    """
    settings defines key value pairs to be passed to all calls
    to all supported RuntimeExtensions.
    Note: Settings can be overridden on the ClusterClass.
    """

@pulumi.input_type
class ExtensionConfigSpecPatchArgs:
    def __init__(__self__, *,
                 client_config: pulumi.Input[Optional['ExtensionConfigSpecClientConfigPatchArgs']] = None,
                 namespace_selector: pulumi.Input[Optional['ExtensionConfigSpecNamespaceSelectorPatchArgs']] = None,
                 settings: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None):
        """
        spec is the desired state of the ExtensionConfig.

        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] settings: settings defines key value pairs to be passed to all calls
               to all supported RuntimeExtensions.
               Note: Settings can be overridden on the ClusterClass.
        """
        if client_config is not None:
            pulumi.set(__self__, "client_config", client_config)
        if namespace_selector is not None:
            pulumi.set(__self__, "namespace_selector", namespace_selector)
        if settings is not None:
            pulumi.set(__self__, "settings", settings)

    @_builtins.property
    @pulumi.getter(name="clientConfig")
    def client_config(self) -> pulumi.Input[Optional['ExtensionConfigSpecClientConfigPatchArgs']]:
        return pulumi.get(self, "client_config")

    @client_config.setter
    def client_config(self, value: pulumi.Input[Optional['ExtensionConfigSpecClientConfigPatchArgs']]):
        pulumi.set(self, "client_config", value)

    @_builtins.property
    @pulumi.getter(name="namespaceSelector")
    def namespace_selector(self) -> pulumi.Input[Optional['ExtensionConfigSpecNamespaceSelectorPatchArgs']]:
        return pulumi.get(self, "namespace_selector")

    @namespace_selector.setter
    def namespace_selector(self, value: pulumi.Input[Optional['ExtensionConfigSpecNamespaceSelectorPatchArgs']]):
        pulumi.set(self, "namespace_selector", value)

    @_builtins.property
    @pulumi.getter
    def settings(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        settings defines key value pairs to be passed to all calls
        to all supported RuntimeExtensions.
        Note: Settings can be overridden on the ClusterClass.
        """
        return pulumi.get(self, "settings")

    @settings.setter
    def settings(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "settings", value)


class ExtensionConfigSpecArgsDict(TypedDict):
    """
    spec is the desired state of the ExtensionConfig.
    """
    client_config: NotRequired[pulumi.Input[Optional['ExtensionConfigSpecClientConfigArgs']]]
    namespace_selector: NotRequired[pulumi.Input[Optional['ExtensionConfigSpecNamespaceSelectorArgs']]]
    settings: NotRequired[pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]]
    """
    settings defines key value pairs to be passed to all calls
    to all supported RuntimeExtensions.
    Note: Settings can be overridden on the ClusterClass.
    """

@pulumi.input_type
class ExtensionConfigSpecArgs:
    def __init__(__self__, *,
                 client_config: pulumi.Input[Optional['ExtensionConfigSpecClientConfigArgs']] = None,
                 namespace_selector: pulumi.Input[Optional['ExtensionConfigSpecNamespaceSelectorArgs']] = None,
                 settings: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None):
        """
        spec is the desired state of the ExtensionConfig.

        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] settings: settings defines key value pairs to be passed to all calls
               to all supported RuntimeExtensions.
               Note: Settings can be overridden on the ClusterClass.
        """
        if client_config is not None:
            pulumi.set(__self__, "client_config", client_config)
        if namespace_selector is not None:
            pulumi.set(__self__, "namespace_selector", namespace_selector)
        if settings is not None:
            pulumi.set(__self__, "settings", settings)

    @_builtins.property
    @pulumi.getter(name="clientConfig")
    def client_config(self) -> pulumi.Input[Optional['ExtensionConfigSpecClientConfigArgs']]:
        return pulumi.get(self, "client_config")

    @client_config.setter
    def client_config(self, value: pulumi.Input[Optional['ExtensionConfigSpecClientConfigArgs']]):
        pulumi.set(self, "client_config", value)

    @_builtins.property
    @pulumi.getter(name="namespaceSelector")
    def namespace_selector(self) -> pulumi.Input[Optional['ExtensionConfigSpecNamespaceSelectorArgs']]:
        return pulumi.get(self, "namespace_selector")

    @namespace_selector.setter
    def namespace_selector(self, value: pulumi.Input[Optional['ExtensionConfigSpecNamespaceSelectorArgs']]):
        pulumi.set(self, "namespace_selector", value)

    @_builtins.property
    @pulumi.getter
    def settings(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        settings defines key value pairs to be passed to all calls
        to all supported RuntimeExtensions.
        Note: Settings can be overridden on the ClusterClass.
        """
        return pulumi.get(self, "settings")

    @settings.setter
    def settings(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "settings", value)


class ExtensionConfigStatusConditionsArgsDict(TypedDict):
    """
    Condition contains details for one aspect of the current state of this API Resource.
    """
    last_transition_time: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    lastTransitionTime is the last time the condition transitioned from one status to another.
    This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
    """
    message: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    message is a human readable message indicating details about the transition.
    This may be an empty string.
    """
    observed_generation: NotRequired[pulumi.Input[Optional[_builtins.int]]]
    """
    observedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    reason contains a programmatic identifier indicating the reason for the condition's last transition.
    Producers of specific condition types may define expected values and meanings for this field,
    and whether the values are considered a guaranteed API.
    The value should be a CamelCase string.
    This field may not be empty.
    """
    status: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    status of the condition, one of True, False, Unknown.
    """
    type: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    type of condition in CamelCase or in foo.example.com/CamelCase.
    """

@pulumi.input_type
class ExtensionConfigStatusConditionsArgs:
    def __init__(__self__, *,
                 last_transition_time: pulumi.Input[Optional[_builtins.str]] = None,
                 message: pulumi.Input[Optional[_builtins.str]] = None,
                 observed_generation: pulumi.Input[Optional[_builtins.int]] = None,
                 reason: pulumi.Input[Optional[_builtins.str]] = None,
                 status: pulumi.Input[Optional[_builtins.str]] = None,
                 type: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Condition contains details for one aspect of the current state of this API Resource.

        :param pulumi.Input[_builtins.str] last_transition_time: lastTransitionTime is the last time the condition transitioned from one status to another.
               This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
        :param pulumi.Input[_builtins.str] message: message is a human readable message indicating details about the transition.
               This may be an empty string.
        :param pulumi.Input[_builtins.int] observed_generation: observedGeneration represents the .metadata.generation that the condition was set based upon.
               For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
               with respect to the current state of the instance.
        :param pulumi.Input[_builtins.str] reason: reason contains a programmatic identifier indicating the reason for the condition's last transition.
               Producers of specific condition types may define expected values and meanings for this field,
               and whether the values are considered a guaranteed API.
               The value should be a CamelCase string.
               This field may not be empty.
        :param pulumi.Input[_builtins.str] status: status of the condition, one of True, False, Unknown.
        :param pulumi.Input[_builtins.str] type: type of condition in CamelCase or in foo.example.com/CamelCase.
        """
        if last_transition_time is not None:
            pulumi.set(__self__, "last_transition_time", last_transition_time)
        if message is not None:
            pulumi.set(__self__, "message", message)
        if observed_generation is not None:
            pulumi.set(__self__, "observed_generation", observed_generation)
        if reason is not None:
            pulumi.set(__self__, "reason", reason)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if type is not None:
            pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter(name="lastTransitionTime")
    def last_transition_time(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        lastTransitionTime is the last time the condition transitioned from one status to another.
        This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
        """
        return pulumi.get(self, "last_transition_time")

    @last_transition_time.setter
    def last_transition_time(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "last_transition_time", value)

    @_builtins.property
    @pulumi.getter
    def message(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        message is a human readable message indicating details about the transition.
        This may be an empty string.
        """
        return pulumi.get(self, "message")

    @message.setter
    def message(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "message", value)

    @_builtins.property
    @pulumi.getter(name="observedGeneration")
    def observed_generation(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        observedGeneration represents the .metadata.generation that the condition was set based upon.
        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
        with respect to the current state of the instance.
        """
        return pulumi.get(self, "observed_generation")

    @observed_generation.setter
    def observed_generation(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "observed_generation", value)

    @_builtins.property
    @pulumi.getter
    def reason(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        reason contains a programmatic identifier indicating the reason for the condition's last transition.
        Producers of specific condition types may define expected values and meanings for this field,
        and whether the values are considered a guaranteed API.
        The value should be a CamelCase string.
        This field may not be empty.
        """
        return pulumi.get(self, "reason")

    @reason.setter
    def reason(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "reason", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        status of the condition, one of True, False, Unknown.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        type of condition in CamelCase or in foo.example.com/CamelCase.
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "type", value)


class ExtensionConfigStatusDeprecatedV1beta1ConditionsArgsDict(TypedDict):
    """
    Condition defines an observation of a Cluster API resource operational state.

    Deprecated: This type is deprecated and is going to be removed when support for v1beta1 will be dropped. Please see https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20240916-improve-status-in-CAPI-resources.md for more details.
    """
    last_transition_time: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    lastTransitionTime is the last time the condition transitioned from one status to another.
    This should be when the underlying condition changed. If that is not known, then using the time when
    the API field changed is acceptable.
    """
    message: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    message is a human readable message indicating details about the transition.
    This field may be empty.
    """
    reason: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    reason is the reason for the condition's last transition in CamelCase.
    The specific API may choose whether or not this field is considered a guaranteed API.
    This field may be empty.
    """
    severity: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    severity provides an explicit classification of Reason code, so the users or machines can immediately
    understand the current situation and act accordingly.
    The Severity field MUST be set only when Status=False.
    """
    status: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    status of the condition, one of True, False, Unknown.
    """
    type: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    type of condition in CamelCase or in foo.example.com/CamelCase.
    Many .condition.type values are consistent across resources like Available, but because arbitrary conditions
    can be useful (see .node.status.conditions), the ability to deconflict is important.
    """

@pulumi.input_type
class ExtensionConfigStatusDeprecatedV1beta1ConditionsArgs:
    def __init__(__self__, *,
                 last_transition_time: pulumi.Input[Optional[_builtins.str]] = None,
                 message: pulumi.Input[Optional[_builtins.str]] = None,
                 reason: pulumi.Input[Optional[_builtins.str]] = None,
                 severity: pulumi.Input[Optional[_builtins.str]] = None,
                 status: pulumi.Input[Optional[_builtins.str]] = None,
                 type: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Condition defines an observation of a Cluster API resource operational state.

        Deprecated: This type is deprecated and is going to be removed when support for v1beta1 will be dropped. Please see https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20240916-improve-status-in-CAPI-resources.md for more details.

        :param pulumi.Input[_builtins.str] last_transition_time: lastTransitionTime is the last time the condition transitioned from one status to another.
               This should be when the underlying condition changed. If that is not known, then using the time when
               the API field changed is acceptable.
        :param pulumi.Input[_builtins.str] message: message is a human readable message indicating details about the transition.
               This field may be empty.
        :param pulumi.Input[_builtins.str] reason: reason is the reason for the condition's last transition in CamelCase.
               The specific API may choose whether or not this field is considered a guaranteed API.
               This field may be empty.
        :param pulumi.Input[_builtins.str] severity: severity provides an explicit classification of Reason code, so the users or machines can immediately
               understand the current situation and act accordingly.
               The Severity field MUST be set only when Status=False.
        :param pulumi.Input[_builtins.str] status: status of the condition, one of True, False, Unknown.
        :param pulumi.Input[_builtins.str] type: type of condition in CamelCase or in foo.example.com/CamelCase.
               Many .condition.type values are consistent across resources like Available, but because arbitrary conditions
               can be useful (see .node.status.conditions), the ability to deconflict is important.
        """
        if last_transition_time is not None:
            pulumi.set(__self__, "last_transition_time", last_transition_time)
        if message is not None:
            pulumi.set(__self__, "message", message)
        if reason is not None:
            pulumi.set(__self__, "reason", reason)
        if severity is not None:
            pulumi.set(__self__, "severity", severity)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if type is not None:
            pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter(name="lastTransitionTime")
    def last_transition_time(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        lastTransitionTime is the last time the condition transitioned from one status to another.
        This should be when the underlying condition changed. If that is not known, then using the time when
        the API field changed is acceptable.
        """
        return pulumi.get(self, "last_transition_time")

    @last_transition_time.setter
    def last_transition_time(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "last_transition_time", value)

    @_builtins.property
    @pulumi.getter
    def message(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        message is a human readable message indicating details about the transition.
        This field may be empty.
        """
        return pulumi.get(self, "message")

    @message.setter
    def message(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "message", value)

    @_builtins.property
    @pulumi.getter
    def reason(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        reason is the reason for the condition's last transition in CamelCase.
        The specific API may choose whether or not this field is considered a guaranteed API.
        This field may be empty.
        """
        return pulumi.get(self, "reason")

    @reason.setter
    def reason(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "reason", value)

    @_builtins.property
    @pulumi.getter
    def severity(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        severity provides an explicit classification of Reason code, so the users or machines can immediately
        understand the current situation and act accordingly.
        The Severity field MUST be set only when Status=False.
        """
        return pulumi.get(self, "severity")

    @severity.setter
    def severity(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "severity", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        status of the condition, one of True, False, Unknown.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        type of condition in CamelCase or in foo.example.com/CamelCase.
        Many .condition.type values are consistent across resources like Available, but because arbitrary conditions
        can be useful (see .node.status.conditions), the ability to deconflict is important.
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "type", value)


class ExtensionConfigStatusDeprecatedV1beta1ArgsDict(TypedDict):
    """
    v1beta1 groups all the status fields that are deprecated and will be removed when support for v1beta1 will be dropped.

    Deprecated: This field is deprecated and is going to be removed when support for v1beta1 will be dropped. Please see https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20240916-improve-status-in-CAPI-resources.md for more details.
    """
    conditions: NotRequired[pulumi.Input[Optional[Sequence[pulumi.Input['ExtensionConfigStatusDeprecatedV1beta1ConditionsArgs']]]]]
    """
    conditions defines current service state of the ExtensionConfig.

    Deprecated: This field is deprecated and is going to be removed when support for v1beta1 will be dropped. Please see https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20240916-improve-status-in-CAPI-resources.md for more details.
    """

@pulumi.input_type
class ExtensionConfigStatusDeprecatedV1beta1Args:
    def __init__(__self__, *,
                 conditions: pulumi.Input[Optional[Sequence[pulumi.Input['ExtensionConfigStatusDeprecatedV1beta1ConditionsArgs']]]] = None):
        """
        v1beta1 groups all the status fields that are deprecated and will be removed when support for v1beta1 will be dropped.

        Deprecated: This field is deprecated and is going to be removed when support for v1beta1 will be dropped. Please see https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20240916-improve-status-in-CAPI-resources.md for more details.

        :param pulumi.Input[Sequence[pulumi.Input['ExtensionConfigStatusDeprecatedV1beta1ConditionsArgs']]] conditions: conditions defines current service state of the ExtensionConfig.
               
               Deprecated: This field is deprecated and is going to be removed when support for v1beta1 will be dropped. Please see https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20240916-improve-status-in-CAPI-resources.md for more details.
        """
        if conditions is not None:
            pulumi.set(__self__, "conditions", conditions)

    @_builtins.property
    @pulumi.getter
    def conditions(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['ExtensionConfigStatusDeprecatedV1beta1ConditionsArgs']]]]:
        """
        conditions defines current service state of the ExtensionConfig.

        Deprecated: This field is deprecated and is going to be removed when support for v1beta1 will be dropped. Please see https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20240916-improve-status-in-CAPI-resources.md for more details.
        """
        return pulumi.get(self, "conditions")

    @conditions.setter
    def conditions(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['ExtensionConfigStatusDeprecatedV1beta1ConditionsArgs']]]]):
        pulumi.set(self, "conditions", value)


class ExtensionConfigStatusDeprecatedArgsDict(TypedDict):
    """
    deprecated groups all the status fields that are deprecated and will be removed when all the nested field are removed.
    """
    v1beta1: NotRequired[pulumi.Input[Optional['ExtensionConfigStatusDeprecatedV1beta1Args']]]

@pulumi.input_type
class ExtensionConfigStatusDeprecatedArgs:
    def __init__(__self__, *,
                 v1beta1: pulumi.Input[Optional['ExtensionConfigStatusDeprecatedV1beta1Args']] = None):
        """
        deprecated groups all the status fields that are deprecated and will be removed when all the nested field are removed.
        """
        if v1beta1 is not None:
            pulumi.set(__self__, "v1beta1", v1beta1)

    @_builtins.property
    @pulumi.getter
    def v1beta1(self) -> pulumi.Input[Optional['ExtensionConfigStatusDeprecatedV1beta1Args']]:
        return pulumi.get(self, "v1beta1")

    @v1beta1.setter
    def v1beta1(self, value: pulumi.Input[Optional['ExtensionConfigStatusDeprecatedV1beta1Args']]):
        pulumi.set(self, "v1beta1", value)


class ExtensionConfigStatusHandlersRequestHookArgsDict(TypedDict):
    """
    requestHook defines the versioned runtime hook which this ExtensionHandler serves.
    """
    api_version: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    apiVersion is the group and version of the Hook.
    """
    hook: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    hook is the name of the hook.
    """

@pulumi.input_type
class ExtensionConfigStatusHandlersRequestHookArgs:
    def __init__(__self__, *,
                 api_version: pulumi.Input[Optional[_builtins.str]] = None,
                 hook: pulumi.Input[Optional[_builtins.str]] = None):
        """
        requestHook defines the versioned runtime hook which this ExtensionHandler serves.

        :param pulumi.Input[_builtins.str] api_version: apiVersion is the group and version of the Hook.
        :param pulumi.Input[_builtins.str] hook: hook is the name of the hook.
        """
        if api_version is not None:
            pulumi.set(__self__, "api_version", api_version)
        if hook is not None:
            pulumi.set(__self__, "hook", hook)

    @_builtins.property
    @pulumi.getter(name="apiVersion")
    def api_version(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        apiVersion is the group and version of the Hook.
        """
        return pulumi.get(self, "api_version")

    @api_version.setter
    def api_version(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "api_version", value)

    @_builtins.property
    @pulumi.getter
    def hook(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        hook is the name of the hook.
        """
        return pulumi.get(self, "hook")

    @hook.setter
    def hook(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "hook", value)


class ExtensionConfigStatusHandlersArgsDict(TypedDict):
    """
    ExtensionHandler specifies the details of a handler for a particular runtime hook registered by an Extension server.
    """
    failure_policy: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    failurePolicy defines how failures in calls to the ExtensionHandler should be handled by a client.
    Defaults to Fail if not set.
    """
    name: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    name is the unique name of the ExtensionHandler.
    """
    request_hook: NotRequired[pulumi.Input[Optional['ExtensionConfigStatusHandlersRequestHookArgs']]]
    timeout_seconds: NotRequired[pulumi.Input[Optional[_builtins.int]]]
    """
    timeoutSeconds defines the timeout duration for client calls to the ExtensionHandler.
    Defaults to 10 if not set.
    """

@pulumi.input_type
class ExtensionConfigStatusHandlersArgs:
    def __init__(__self__, *,
                 failure_policy: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 request_hook: pulumi.Input[Optional['ExtensionConfigStatusHandlersRequestHookArgs']] = None,
                 timeout_seconds: pulumi.Input[Optional[_builtins.int]] = None):
        """
        ExtensionHandler specifies the details of a handler for a particular runtime hook registered by an Extension server.

        :param pulumi.Input[_builtins.str] failure_policy: failurePolicy defines how failures in calls to the ExtensionHandler should be handled by a client.
               Defaults to Fail if not set.
        :param pulumi.Input[_builtins.str] name: name is the unique name of the ExtensionHandler.
        :param pulumi.Input[_builtins.int] timeout_seconds: timeoutSeconds defines the timeout duration for client calls to the ExtensionHandler.
               Defaults to 10 if not set.
        """
        if failure_policy is not None:
            pulumi.set(__self__, "failure_policy", failure_policy)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if request_hook is not None:
            pulumi.set(__self__, "request_hook", request_hook)
        if timeout_seconds is not None:
            pulumi.set(__self__, "timeout_seconds", timeout_seconds)

    @_builtins.property
    @pulumi.getter(name="failurePolicy")
    def failure_policy(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        failurePolicy defines how failures in calls to the ExtensionHandler should be handled by a client.
        Defaults to Fail if not set.
        """
        return pulumi.get(self, "failure_policy")

    @failure_policy.setter
    def failure_policy(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "failure_policy", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        name is the unique name of the ExtensionHandler.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="requestHook")
    def request_hook(self) -> pulumi.Input[Optional['ExtensionConfigStatusHandlersRequestHookArgs']]:
        return pulumi.get(self, "request_hook")

    @request_hook.setter
    def request_hook(self, value: pulumi.Input[Optional['ExtensionConfigStatusHandlersRequestHookArgs']]):
        pulumi.set(self, "request_hook", value)

    @_builtins.property
    @pulumi.getter(name="timeoutSeconds")
    def timeout_seconds(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        timeoutSeconds defines the timeout duration for client calls to the ExtensionHandler.
        Defaults to 10 if not set.
        """
        return pulumi.get(self, "timeout_seconds")

    @timeout_seconds.setter
    def timeout_seconds(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "timeout_seconds", value)


class ExtensionConfigStatusArgsDict(TypedDict):
    """
    status is the current state of the ExtensionConfig
    """
    conditions: NotRequired[pulumi.Input[Optional[Sequence[pulumi.Input['ExtensionConfigStatusConditionsArgs']]]]]
    """
    conditions represents the observations of a ExtensionConfig's current state.
    Known condition types are Discovered, Paused.
    """
    deprecated: NotRequired[pulumi.Input[Optional['ExtensionConfigStatusDeprecatedArgs']]]
    handlers: NotRequired[pulumi.Input[Optional[Sequence[pulumi.Input['ExtensionConfigStatusHandlersArgs']]]]]
    """
    handlers defines the current ExtensionHandlers supported by an Extension.
    """

@pulumi.input_type
class ExtensionConfigStatusArgs:
    def __init__(__self__, *,
                 conditions: pulumi.Input[Optional[Sequence[pulumi.Input['ExtensionConfigStatusConditionsArgs']]]] = None,
                 deprecated: pulumi.Input[Optional['ExtensionConfigStatusDeprecatedArgs']] = None,
                 handlers: pulumi.Input[Optional[Sequence[pulumi.Input['ExtensionConfigStatusHandlersArgs']]]] = None):
        """
        status is the current state of the ExtensionConfig

        :param pulumi.Input[Sequence[pulumi.Input['ExtensionConfigStatusConditionsArgs']]] conditions: conditions represents the observations of a ExtensionConfig's current state.
               Known condition types are Discovered, Paused.
        :param pulumi.Input[Sequence[pulumi.Input['ExtensionConfigStatusHandlersArgs']]] handlers: handlers defines the current ExtensionHandlers supported by an Extension.
        """
        if conditions is not None:
            pulumi.set(__self__, "conditions", conditions)
        if deprecated is not None:
            pulumi.set(__self__, "deprecated", deprecated)
        if handlers is not None:
            pulumi.set(__self__, "handlers", handlers)

    @_builtins.property
    @pulumi.getter
    def conditions(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['ExtensionConfigStatusConditionsArgs']]]]:
        """
        conditions represents the observations of a ExtensionConfig's current state.
        Known condition types are Discovered, Paused.
        """
        return pulumi.get(self, "conditions")

    @conditions.setter
    def conditions(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['ExtensionConfigStatusConditionsArgs']]]]):
        pulumi.set(self, "conditions", value)

    @_builtins.property
    @pulumi.getter
    def deprecated(self) -> pulumi.Input[Optional['ExtensionConfigStatusDeprecatedArgs']]:
        return pulumi.get(self, "deprecated")

    @deprecated.setter
    def deprecated(self, value: pulumi.Input[Optional['ExtensionConfigStatusDeprecatedArgs']]):
        pulumi.set(self, "deprecated", value)

    @_builtins.property
    @pulumi.getter
    def handlers(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['ExtensionConfigStatusHandlersArgs']]]]:
        """
        handlers defines the current ExtensionHandlers supported by an Extension.
        """
        return pulumi.get(self, "handlers")

    @handlers.setter
    def handlers(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['ExtensionConfigStatusHandlersArgs']]]]):
        pulumi.set(self, "handlers", value)


class ExtensionConfigArgsDict(TypedDict):
    """
    ExtensionConfig is the Schema for the ExtensionConfig API.
    NOTE: This CRD can only be used if the RuntimeSDK feature gate is enabled.
    """
    api_version: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: NotRequired[pulumi.Input[Optional['_meta.v1.ObjectMetaArgs']]]
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: NotRequired[pulumi.Input[Optional['ExtensionConfigSpecArgs']]]
    status: NotRequired[pulumi.Input[Optional['ExtensionConfigStatusArgs']]]

@pulumi.input_type
class ExtensionConfigArgs:
    def __init__(__self__, *,
                 api_version: pulumi.Input[Optional[_builtins.str]] = None,
                 kind: pulumi.Input[Optional[_builtins.str]] = None,
                 metadata: pulumi.Input[Optional['_meta.v1.ObjectMetaArgs']] = None,
                 spec: pulumi.Input[Optional['ExtensionConfigSpecArgs']] = None,
                 status: pulumi.Input[Optional['ExtensionConfigStatusArgs']] = None):
        """
        ExtensionConfig is the Schema for the ExtensionConfig API.
        NOTE: This CRD can only be used if the RuntimeSDK feature gate is enabled.

        :param pulumi.Input[_builtins.str] api_version: APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
        :param pulumi.Input[_builtins.str] kind: Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        :param pulumi.Input['_meta.v1.ObjectMetaArgs'] metadata: Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        """
        if api_version is not None:
            pulumi.set(__self__, "api_version", 'runtime.cluster.x-k8s.io/v1beta2')
        if kind is not None:
            pulumi.set(__self__, "kind", 'ExtensionConfig')
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if spec is not None:
            pulumi.set(__self__, "spec", spec)
        if status is not None:
            pulumi.set(__self__, "status", status)

    @_builtins.property
    @pulumi.getter(name="apiVersion")
    def api_version(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
        """
        return pulumi.get(self, "api_version")

    @api_version.setter
    def api_version(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "api_version", value)

    @_builtins.property
    @pulumi.getter
    def kind(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        """
        return pulumi.get(self, "kind")

    @kind.setter
    def kind(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "kind", value)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Input[Optional['_meta.v1.ObjectMetaArgs']]:
        """
        Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        """
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: pulumi.Input[Optional['_meta.v1.ObjectMetaArgs']]):
        pulumi.set(self, "metadata", value)

    @_builtins.property
    @pulumi.getter
    def spec(self) -> pulumi.Input[Optional['ExtensionConfigSpecArgs']]:
        return pulumi.get(self, "spec")

    @spec.setter
    def spec(self, value: pulumi.Input[Optional['ExtensionConfigSpecArgs']]):
        pulumi.set(self, "spec", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Input[Optional['ExtensionConfigStatusArgs']]:
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: pulumi.Input[Optional['ExtensionConfigStatusArgs']]):
        pulumi.set(self, "status", value)


