[project]
  name = "pulumi_awx"
  description = "A Pulumi provider dynamically bridged from awx."
  dependencies = ["parver>=0.2.1", "pulumi>=3.231.0,<4.0.0", "semver>=2.8.1", "typing-extensions>=4.11,<5; python_version < \"3.11\""]
  readme = "README.md"
  requires-python = ">=3.9"
  version = "24.6.1.post2"
  [project.urls]
    Repository = "https://github.com/ilijamt/terraform-provider-awx"

[build-system]
  requires = ["setuptools>=61.0"]
  build-backend = "setuptools.build_meta"

[tool]
  [tool.setuptools]
    [tool.setuptools.package-data]
      pulumi_awx = ["py.typed", "pulumi-plugin.json"]
