# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['GpgKeyArgs', 'GpgKey']

@pulumi.input_type
class GpgKeyArgs:
    def __init__(__self__, *,
                 armored_public_key: pulumi.Input[_builtins.str],
                 gpg_key_id: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a GpgKey resource.

        :param pulumi.Input[_builtins.str] armored_public_key: An armored GPG public key
        """
        pulumi.set(__self__, "armored_public_key", armored_public_key)
        if gpg_key_id is not None:
            pulumi.set(__self__, "gpg_key_id", gpg_key_id)

    @_builtins.property
    @pulumi.getter(name="armoredPublicKey")
    def armored_public_key(self) -> pulumi.Input[_builtins.str]:
        """
        An armored GPG public key
        """
        return pulumi.get(self, "armored_public_key")

    @armored_public_key.setter
    def armored_public_key(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "armored_public_key", value)

    @_builtins.property
    @pulumi.getter(name="gpgKeyId")
    def gpg_key_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "gpg_key_id")

    @gpg_key_id.setter
    def gpg_key_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "gpg_key_id", value)


@pulumi.input_type
class _GpgKeyState:
    def __init__(__self__, *,
                 armored_public_key: pulumi.Input[Optional[_builtins.str]] = None,
                 gpg_key_id: pulumi.Input[Optional[_builtins.str]] = None,
                 key_id: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering GpgKey resources.

        :param pulumi.Input[_builtins.str] armored_public_key: An armored GPG public key
        :param pulumi.Input[_builtins.str] key_id: The ID of the GPG key
        """
        if armored_public_key is not None:
            pulumi.set(__self__, "armored_public_key", armored_public_key)
        if gpg_key_id is not None:
            pulumi.set(__self__, "gpg_key_id", gpg_key_id)
        if key_id is not None:
            pulumi.set(__self__, "key_id", key_id)

    @_builtins.property
    @pulumi.getter(name="armoredPublicKey")
    def armored_public_key(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        An armored GPG public key
        """
        return pulumi.get(self, "armored_public_key")

    @armored_public_key.setter
    def armored_public_key(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "armored_public_key", value)

    @_builtins.property
    @pulumi.getter(name="gpgKeyId")
    def gpg_key_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "gpg_key_id")

    @gpg_key_id.setter
    def gpg_key_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "gpg_key_id", value)

    @_builtins.property
    @pulumi.getter(name="keyId")
    def key_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The ID of the GPG key
        """
        return pulumi.get(self, "key_id")

    @key_id.setter
    def key_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "key_id", value)


@pulumi.type_token("gitea:index/gpgKey:GpgKey")
class GpgKey(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 armored_public_key: pulumi.Input[Optional[_builtins.str]] = None,
                 gpg_key_id: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Create a GpgKey resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] armored_public_key: An armored GPG public key
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: GpgKeyArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a GpgKey resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param GpgKeyArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(GpgKeyArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 armored_public_key: pulumi.Input[Optional[_builtins.str]] = None,
                 gpg_key_id: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = GpgKeyArgs.__new__(GpgKeyArgs)

            if armored_public_key is None and not opts.urn:
                raise TypeError("Missing required property 'armored_public_key'")
            __props__.__dict__["armored_public_key"] = armored_public_key
            __props__.__dict__["gpg_key_id"] = gpg_key_id
            __props__.__dict__["key_id"] = None
        super(GpgKey, __self__).__init__(
            'gitea:index/gpgKey:GpgKey',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            armored_public_key: pulumi.Input[Optional[_builtins.str]] = None,
            gpg_key_id: pulumi.Input[Optional[_builtins.str]] = None,
            key_id: pulumi.Input[Optional[_builtins.str]] = None) -> 'GpgKey':
        """
        Get an existing GpgKey resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] armored_public_key: An armored GPG public key
        :param pulumi.Input[_builtins.str] key_id: The ID of the GPG key
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _GpgKeyState.__new__(_GpgKeyState)

        __props__.__dict__["armored_public_key"] = armored_public_key
        __props__.__dict__["gpg_key_id"] = gpg_key_id
        __props__.__dict__["key_id"] = key_id
        return GpgKey(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="armoredPublicKey")
    def armored_public_key(self) -> pulumi.Output[_builtins.str]:
        """
        An armored GPG public key
        """
        return pulumi.get(self, "armored_public_key")

    @_builtins.property
    @pulumi.getter(name="gpgKeyId")
    def gpg_key_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "gpg_key_id")

    @_builtins.property
    @pulumi.getter(name="keyId")
    def key_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the GPG key
        """
        return pulumi.get(self, "key_id")

