# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['Oauth2AppArgs', 'Oauth2App']

@pulumi.input_type
class Oauth2AppArgs:
    def __init__(__self__, *,
                 redirect_uris: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]],
                 confidential_client: pulumi.Input[Optional[_builtins.bool]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 oauth2_app_id: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a Oauth2App resource.

        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] redirect_uris: Accepted redirect URIs
        :param pulumi.Input[_builtins.bool] confidential_client: If set to false, it will be a public client (PKCE will be required)
        :param pulumi.Input[_builtins.str] name: OAuth Application name
        """
        pulumi.set(__self__, "redirect_uris", redirect_uris)
        if confidential_client is not None:
            pulumi.set(__self__, "confidential_client", confidential_client)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if oauth2_app_id is not None:
            pulumi.set(__self__, "oauth2_app_id", oauth2_app_id)

    @_builtins.property
    @pulumi.getter(name="redirectUris")
    def redirect_uris(self) -> pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]:
        """
        Accepted redirect URIs
        """
        return pulumi.get(self, "redirect_uris")

    @redirect_uris.setter
    def redirect_uris(self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "redirect_uris", value)

    @_builtins.property
    @pulumi.getter(name="confidentialClient")
    def confidential_client(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        If set to false, it will be a public client (PKCE will be required)
        """
        return pulumi.get(self, "confidential_client")

    @confidential_client.setter
    def confidential_client(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "confidential_client", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        OAuth Application name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="oauth2AppId")
    def oauth2_app_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "oauth2_app_id")

    @oauth2_app_id.setter
    def oauth2_app_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "oauth2_app_id", value)


@pulumi.input_type
class _Oauth2AppState:
    def __init__(__self__, *,
                 client_id: pulumi.Input[Optional[_builtins.str]] = None,
                 client_secret: pulumi.Input[Optional[_builtins.str]] = None,
                 confidential_client: pulumi.Input[Optional[_builtins.bool]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 oauth2_app_id: pulumi.Input[Optional[_builtins.str]] = None,
                 redirect_uris: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        Input properties used for looking up and filtering Oauth2App resources.

        :param pulumi.Input[_builtins.str] client_id: OAuth2 Application client id
        :param pulumi.Input[_builtins.str] client_secret: Oauth2 Application client secret
        :param pulumi.Input[_builtins.bool] confidential_client: If set to false, it will be a public client (PKCE will be required)
        :param pulumi.Input[_builtins.str] name: OAuth Application name
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] redirect_uris: Accepted redirect URIs
        """
        if client_id is not None:
            pulumi.set(__self__, "client_id", client_id)
        if client_secret is not None:
            pulumi.set(__self__, "client_secret", client_secret)
        if confidential_client is not None:
            pulumi.set(__self__, "confidential_client", confidential_client)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if oauth2_app_id is not None:
            pulumi.set(__self__, "oauth2_app_id", oauth2_app_id)
        if redirect_uris is not None:
            pulumi.set(__self__, "redirect_uris", redirect_uris)

    @_builtins.property
    @pulumi.getter(name="clientId")
    def client_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        OAuth2 Application client id
        """
        return pulumi.get(self, "client_id")

    @client_id.setter
    def client_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "client_id", value)

    @_builtins.property
    @pulumi.getter(name="clientSecret")
    def client_secret(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Oauth2 Application client secret
        """
        return pulumi.get(self, "client_secret")

    @client_secret.setter
    def client_secret(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "client_secret", value)

    @_builtins.property
    @pulumi.getter(name="confidentialClient")
    def confidential_client(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        If set to false, it will be a public client (PKCE will be required)
        """
        return pulumi.get(self, "confidential_client")

    @confidential_client.setter
    def confidential_client(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "confidential_client", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        OAuth Application name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="oauth2AppId")
    def oauth2_app_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "oauth2_app_id")

    @oauth2_app_id.setter
    def oauth2_app_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "oauth2_app_id", value)

    @_builtins.property
    @pulumi.getter(name="redirectUris")
    def redirect_uris(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Accepted redirect URIs
        """
        return pulumi.get(self, "redirect_uris")

    @redirect_uris.setter
    def redirect_uris(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "redirect_uris", value)


@pulumi.type_token("gitea:index/oauth2App:Oauth2App")
class Oauth2App(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 confidential_client: pulumi.Input[Optional[_builtins.bool]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 oauth2_app_id: pulumi.Input[Optional[_builtins.str]] = None,
                 redirect_uris: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        """
        Create a Oauth2App resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] confidential_client: If set to false, it will be a public client (PKCE will be required)
        :param pulumi.Input[_builtins.str] name: OAuth Application name
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] redirect_uris: Accepted redirect URIs
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Oauth2AppArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Oauth2App resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param Oauth2AppArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(Oauth2AppArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 confidential_client: pulumi.Input[Optional[_builtins.bool]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 oauth2_app_id: pulumi.Input[Optional[_builtins.str]] = None,
                 redirect_uris: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = Oauth2AppArgs.__new__(Oauth2AppArgs)

            __props__.__dict__["confidential_client"] = confidential_client
            __props__.__dict__["name"] = name
            __props__.__dict__["oauth2_app_id"] = oauth2_app_id
            if redirect_uris is None and not opts.urn:
                raise TypeError("Missing required property 'redirect_uris'")
            __props__.__dict__["redirect_uris"] = redirect_uris
            __props__.__dict__["client_id"] = None
            __props__.__dict__["client_secret"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["clientSecret"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(Oauth2App, __self__).__init__(
            'gitea:index/oauth2App:Oauth2App',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            client_id: pulumi.Input[Optional[_builtins.str]] = None,
            client_secret: pulumi.Input[Optional[_builtins.str]] = None,
            confidential_client: pulumi.Input[Optional[_builtins.bool]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            oauth2_app_id: pulumi.Input[Optional[_builtins.str]] = None,
            redirect_uris: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None) -> 'Oauth2App':
        """
        Get an existing Oauth2App resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] client_id: OAuth2 Application client id
        :param pulumi.Input[_builtins.str] client_secret: Oauth2 Application client secret
        :param pulumi.Input[_builtins.bool] confidential_client: If set to false, it will be a public client (PKCE will be required)
        :param pulumi.Input[_builtins.str] name: OAuth Application name
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] redirect_uris: Accepted redirect URIs
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _Oauth2AppState.__new__(_Oauth2AppState)

        __props__.__dict__["client_id"] = client_id
        __props__.__dict__["client_secret"] = client_secret
        __props__.__dict__["confidential_client"] = confidential_client
        __props__.__dict__["name"] = name
        __props__.__dict__["oauth2_app_id"] = oauth2_app_id
        __props__.__dict__["redirect_uris"] = redirect_uris
        return Oauth2App(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="clientId")
    def client_id(self) -> pulumi.Output[_builtins.str]:
        """
        OAuth2 Application client id
        """
        return pulumi.get(self, "client_id")

    @_builtins.property
    @pulumi.getter(name="clientSecret")
    def client_secret(self) -> pulumi.Output[_builtins.str]:
        """
        Oauth2 Application client secret
        """
        return pulumi.get(self, "client_secret")

    @_builtins.property
    @pulumi.getter(name="confidentialClient")
    def confidential_client(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        If set to false, it will be a public client (PKCE will be required)
        """
        return pulumi.get(self, "confidential_client")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        OAuth Application name
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="oauth2AppId")
    def oauth2_app_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "oauth2_app_id")

    @_builtins.property
    @pulumi.getter(name="redirectUris")
    def redirect_uris(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        Accepted redirect URIs
        """
        return pulumi.get(self, "redirect_uris")

