# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetCommandResult',
    'AwaitableGetCommandResult',
    'get_command',
    'get_command_output',
]

@pulumi.output_type
class GetCommandResult:
    """
    A collection of values returned by getCommand.
    """
    def __init__(__self__, allow_non_zero_exit_code=None, arguments=None, command=None, exit_code=None, id=None, stderr=None, stdin=None, stdout=None, working_directory=None):
        if allow_non_zero_exit_code and not isinstance(allow_non_zero_exit_code, bool):
            raise TypeError("Expected argument 'allow_non_zero_exit_code' to be a bool")
        pulumi.set(__self__, "allow_non_zero_exit_code", allow_non_zero_exit_code)
        if arguments and not isinstance(arguments, list):
            raise TypeError("Expected argument 'arguments' to be a list")
        pulumi.set(__self__, "arguments", arguments)
        if command and not isinstance(command, str):
            raise TypeError("Expected argument 'command' to be a str")
        pulumi.set(__self__, "command", command)
        if exit_code and not isinstance(exit_code, float):
            raise TypeError("Expected argument 'exit_code' to be a float")
        pulumi.set(__self__, "exit_code", exit_code)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if stderr and not isinstance(stderr, str):
            raise TypeError("Expected argument 'stderr' to be a str")
        pulumi.set(__self__, "stderr", stderr)
        if stdin and not isinstance(stdin, str):
            raise TypeError("Expected argument 'stdin' to be a str")
        pulumi.set(__self__, "stdin", stdin)
        if stdout and not isinstance(stdout, str):
            raise TypeError("Expected argument 'stdout' to be a str")
        pulumi.set(__self__, "stdout", stdout)
        if working_directory and not isinstance(working_directory, str):
            raise TypeError("Expected argument 'working_directory' to be a str")
        pulumi.set(__self__, "working_directory", working_directory)

    @_builtins.property
    @pulumi.getter(name="allowNonZeroExitCode")
    def allow_non_zero_exit_code(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "allow_non_zero_exit_code")

    @_builtins.property
    @pulumi.getter
    def arguments(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "arguments")

    @_builtins.property
    @pulumi.getter
    def command(self) -> _builtins.str:
        return pulumi.get(self, "command")

    @_builtins.property
    @pulumi.getter(name="exitCode")
    def exit_code(self) -> _builtins.float:
        return pulumi.get(self, "exit_code")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def stderr(self) -> _builtins.str:
        return pulumi.get(self, "stderr")

    @_builtins.property
    @pulumi.getter
    def stdin(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "stdin")

    @_builtins.property
    @pulumi.getter
    def stdout(self) -> _builtins.str:
        return pulumi.get(self, "stdout")

    @_builtins.property
    @pulumi.getter(name="workingDirectory")
    def working_directory(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "working_directory")


class AwaitableGetCommandResult(GetCommandResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetCommandResult(
            allow_non_zero_exit_code=self.allow_non_zero_exit_code,
            arguments=self.arguments,
            command=self.command,
            exit_code=self.exit_code,
            id=self.id,
            stderr=self.stderr,
            stdin=self.stdin,
            stdout=self.stdout,
            working_directory=self.working_directory)


def get_command(allow_non_zero_exit_code: Optional[_builtins.bool] = None,
                arguments: Optional[Sequence[_builtins.str]] = None,
                command: Optional[_builtins.str] = None,
                stdin: Optional[_builtins.str] = None,
                working_directory: Optional[_builtins.str] = None,
                opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetCommandResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['allowNonZeroExitCode'] = allow_non_zero_exit_code
    __args__['arguments'] = arguments
    __args__['command'] = command
    __args__['stdin'] = stdin
    __args__['workingDirectory'] = working_directory
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('local:index/getCommand:getCommand', __args__, opts=opts, typ=GetCommandResult, package_ref=_utilities.get_package()).value

    return AwaitableGetCommandResult(
        allow_non_zero_exit_code=pulumi.get(__ret__, 'allow_non_zero_exit_code'),
        arguments=pulumi.get(__ret__, 'arguments'),
        command=pulumi.get(__ret__, 'command'),
        exit_code=pulumi.get(__ret__, 'exit_code'),
        id=pulumi.get(__ret__, 'id'),
        stderr=pulumi.get(__ret__, 'stderr'),
        stdin=pulumi.get(__ret__, 'stdin'),
        stdout=pulumi.get(__ret__, 'stdout'),
        working_directory=pulumi.get(__ret__, 'working_directory'))
def get_command_output(allow_non_zero_exit_code: pulumi.Input[Optional[Optional[_builtins.bool]]] = None,
                       arguments: pulumi.Input[Optional[Optional[Sequence[_builtins.str]]]] = None,
                       command: pulumi.Input[Optional[_builtins.str]] = None,
                       stdin: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                       working_directory: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                       opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetCommandResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['allowNonZeroExitCode'] = allow_non_zero_exit_code
    __args__['arguments'] = arguments
    __args__['command'] = command
    __args__['stdin'] = stdin
    __args__['workingDirectory'] = working_directory
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('local:index/getCommand:getCommand', __args__, opts=opts, typ=GetCommandResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetCommandResult(
        allow_non_zero_exit_code=pulumi.get(__response__, 'allow_non_zero_exit_code'),
        arguments=pulumi.get(__response__, 'arguments'),
        command=pulumi.get(__response__, 'command'),
        exit_code=pulumi.get(__response__, 'exit_code'),
        id=pulumi.get(__response__, 'id'),
        stderr=pulumi.get(__response__, 'stderr'),
        stdin=pulumi.get(__response__, 'stdin'),
        stdout=pulumi.get(__response__, 'stdout'),
        working_directory=pulumi.get(__response__, 'working_directory')))
