apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nodeset-scaledobject
  namespace: slurm
spec:
  scaleTargetRef:
    apiVersion: slinky.slurm.net/v1beta1
    kind: NodeSet
    name: slurm-worker-slinky
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090
      query: slurm_partition_jobs_pending{partition="all"}
      threshold: '1'
      activationThreshold: '1'
      unsafeSsl: 'true'