# coding=utf-8
# *** WARNING: this file was generated by crd2pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from ... import _utilities
from ... import meta as _meta

__all__ = [
    'IPAddressClaimSpecPatchArgs',
    'IPAddressClaimSpecPatchArgsDict',
    'IPAddressClaimSpecPoolRefPatchArgs',
    'IPAddressClaimSpecPoolRefPatchArgsDict',
    'IPAddressClaimSpecPoolRefArgs',
    'IPAddressClaimSpecPoolRefArgsDict',
    'IPAddressClaimSpecArgs',
    'IPAddressClaimSpecArgsDict',
    'IPAddressClaimStatusAddressRefArgs',
    'IPAddressClaimStatusAddressRefArgsDict',
    'IPAddressClaimStatusConditionsArgs',
    'IPAddressClaimStatusConditionsArgsDict',
    'IPAddressClaimStatusDeprecatedV1beta1ConditionsArgs',
    'IPAddressClaimStatusDeprecatedV1beta1ConditionsArgsDict',
    'IPAddressClaimStatusDeprecatedV1beta1Args',
    'IPAddressClaimStatusDeprecatedV1beta1ArgsDict',
    'IPAddressClaimStatusDeprecatedArgs',
    'IPAddressClaimStatusDeprecatedArgsDict',
    'IPAddressClaimStatusArgs',
    'IPAddressClaimStatusArgsDict',
    'IPAddressClaimArgs',
    'IPAddressClaimArgsDict',
    'IPAddressSpecClaimRefPatchArgs',
    'IPAddressSpecClaimRefPatchArgsDict',
    'IPAddressSpecClaimRefArgs',
    'IPAddressSpecClaimRefArgsDict',
    'IPAddressSpecPatchArgs',
    'IPAddressSpecPatchArgsDict',
    'IPAddressSpecPoolRefPatchArgs',
    'IPAddressSpecPoolRefPatchArgsDict',
    'IPAddressSpecPoolRefArgs',
    'IPAddressSpecPoolRefArgsDict',
    'IPAddressSpecArgs',
    'IPAddressSpecArgsDict',
    'IPAddressArgs',
    'IPAddressArgsDict',
]

class IPAddressClaimSpecPatchArgsDict(TypedDict):
    """
    spec is the desired state of IPAddressClaim.
    """
    cluster_name: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    clusterName is the name of the Cluster this object belongs to.
    """
    pool_ref: NotRequired[pulumi.Input[Optional['IPAddressClaimSpecPoolRefPatchArgs']]]

@pulumi.input_type
class IPAddressClaimSpecPatchArgs:
    def __init__(__self__, *,
                 cluster_name: pulumi.Input[Optional[_builtins.str]] = None,
                 pool_ref: pulumi.Input[Optional['IPAddressClaimSpecPoolRefPatchArgs']] = None):
        """
        spec is the desired state of IPAddressClaim.

        :param pulumi.Input[_builtins.str] cluster_name: clusterName is the name of the Cluster this object belongs to.
        """
        if cluster_name is not None:
            pulumi.set(__self__, "cluster_name", cluster_name)
        if pool_ref is not None:
            pulumi.set(__self__, "pool_ref", pool_ref)

    @_builtins.property
    @pulumi.getter(name="clusterName")
    def cluster_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        clusterName is the name of the Cluster this object belongs to.
        """
        return pulumi.get(self, "cluster_name")

    @cluster_name.setter
    def cluster_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "cluster_name", value)

    @_builtins.property
    @pulumi.getter(name="poolRef")
    def pool_ref(self) -> pulumi.Input[Optional['IPAddressClaimSpecPoolRefPatchArgs']]:
        return pulumi.get(self, "pool_ref")

    @pool_ref.setter
    def pool_ref(self, value: pulumi.Input[Optional['IPAddressClaimSpecPoolRefPatchArgs']]):
        pulumi.set(self, "pool_ref", value)


class IPAddressClaimSpecPoolRefPatchArgsDict(TypedDict):
    """
    poolRef is a reference to the pool from which an IP address should be created.
    """
    api_group: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    apiGroup of the IPPool.
    apiGroup must be fully qualified domain name.
    """
    kind: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    kind of the IPPool.
    kind must consist of alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character.
    """
    name: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    name of the IPPool.
    name must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character.
    """

@pulumi.input_type
class IPAddressClaimSpecPoolRefPatchArgs:
    def __init__(__self__, *,
                 api_group: pulumi.Input[Optional[_builtins.str]] = None,
                 kind: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None):
        """
        poolRef is a reference to the pool from which an IP address should be created.

        :param pulumi.Input[_builtins.str] api_group: apiGroup of the IPPool.
               apiGroup must be fully qualified domain name.
        :param pulumi.Input[_builtins.str] kind: kind of the IPPool.
               kind must consist of alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character.
        :param pulumi.Input[_builtins.str] name: name of the IPPool.
               name must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character.
        """
        if api_group is not None:
            pulumi.set(__self__, "api_group", api_group)
        if kind is not None:
            pulumi.set(__self__, "kind", kind)
        if name is not None:
            pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter(name="apiGroup")
    def api_group(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        apiGroup of the IPPool.
        apiGroup must be fully qualified domain name.
        """
        return pulumi.get(self, "api_group")

    @api_group.setter
    def api_group(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "api_group", value)

    @_builtins.property
    @pulumi.getter
    def kind(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        kind of the IPPool.
        kind must consist of alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character.
        """
        return pulumi.get(self, "kind")

    @kind.setter
    def kind(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "kind", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        name of the IPPool.
        name must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)


class IPAddressClaimSpecPoolRefArgsDict(TypedDict):
    """
    poolRef is a reference to the pool from which an IP address should be created.
    """
    api_group: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    apiGroup of the IPPool.
    apiGroup must be fully qualified domain name.
    """
    kind: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    kind of the IPPool.
    kind must consist of alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character.
    """
    name: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    name of the IPPool.
    name must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character.
    """

@pulumi.input_type
class IPAddressClaimSpecPoolRefArgs:
    def __init__(__self__, *,
                 api_group: pulumi.Input[Optional[_builtins.str]] = None,
                 kind: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None):
        """
        poolRef is a reference to the pool from which an IP address should be created.

        :param pulumi.Input[_builtins.str] api_group: apiGroup of the IPPool.
               apiGroup must be fully qualified domain name.
        :param pulumi.Input[_builtins.str] kind: kind of the IPPool.
               kind must consist of alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character.
        :param pulumi.Input[_builtins.str] name: name of the IPPool.
               name must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character.
        """
        if api_group is not None:
            pulumi.set(__self__, "api_group", api_group)
        if kind is not None:
            pulumi.set(__self__, "kind", kind)
        if name is not None:
            pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter(name="apiGroup")
    def api_group(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        apiGroup of the IPPool.
        apiGroup must be fully qualified domain name.
        """
        return pulumi.get(self, "api_group")

    @api_group.setter
    def api_group(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "api_group", value)

    @_builtins.property
    @pulumi.getter
    def kind(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        kind of the IPPool.
        kind must consist of alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character.
        """
        return pulumi.get(self, "kind")

    @kind.setter
    def kind(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "kind", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        name of the IPPool.
        name must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)


class IPAddressClaimSpecArgsDict(TypedDict):
    """
    spec is the desired state of IPAddressClaim.
    """
    cluster_name: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    clusterName is the name of the Cluster this object belongs to.
    """
    pool_ref: NotRequired[pulumi.Input[Optional['IPAddressClaimSpecPoolRefArgs']]]

@pulumi.input_type
class IPAddressClaimSpecArgs:
    def __init__(__self__, *,
                 cluster_name: pulumi.Input[Optional[_builtins.str]] = None,
                 pool_ref: pulumi.Input[Optional['IPAddressClaimSpecPoolRefArgs']] = None):
        """
        spec is the desired state of IPAddressClaim.

        :param pulumi.Input[_builtins.str] cluster_name: clusterName is the name of the Cluster this object belongs to.
        """
        if cluster_name is not None:
            pulumi.set(__self__, "cluster_name", cluster_name)
        if pool_ref is not None:
            pulumi.set(__self__, "pool_ref", pool_ref)

    @_builtins.property
    @pulumi.getter(name="clusterName")
    def cluster_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        clusterName is the name of the Cluster this object belongs to.
        """
        return pulumi.get(self, "cluster_name")

    @cluster_name.setter
    def cluster_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "cluster_name", value)

    @_builtins.property
    @pulumi.getter(name="poolRef")
    def pool_ref(self) -> pulumi.Input[Optional['IPAddressClaimSpecPoolRefArgs']]:
        return pulumi.get(self, "pool_ref")

    @pool_ref.setter
    def pool_ref(self, value: pulumi.Input[Optional['IPAddressClaimSpecPoolRefArgs']]):
        pulumi.set(self, "pool_ref", value)


class IPAddressClaimStatusAddressRefArgsDict(TypedDict):
    """
    addressRef is a reference to the address that was created for this claim.
    """
    name: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    name of the IPAddress.
    name must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character.
    """

@pulumi.input_type
class IPAddressClaimStatusAddressRefArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[Optional[_builtins.str]] = None):
        """
        addressRef is a reference to the address that was created for this claim.

        :param pulumi.Input[_builtins.str] name: name of the IPAddress.
               name must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character.
        """
        if name is not None:
            pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        name of the IPAddress.
        name must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)


class IPAddressClaimStatusConditionsArgsDict(TypedDict):
    """
    Condition contains details for one aspect of the current state of this API Resource.
    """
    last_transition_time: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    lastTransitionTime is the last time the condition transitioned from one status to another.
    This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
    """
    message: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    message is a human readable message indicating details about the transition.
    This may be an empty string.
    """
    observed_generation: NotRequired[pulumi.Input[Optional[_builtins.int]]]
    """
    observedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    reason contains a programmatic identifier indicating the reason for the condition's last transition.
    Producers of specific condition types may define expected values and meanings for this field,
    and whether the values are considered a guaranteed API.
    The value should be a CamelCase string.
    This field may not be empty.
    """
    status: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    status of the condition, one of True, False, Unknown.
    """
    type: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    type of condition in CamelCase or in foo.example.com/CamelCase.
    """

@pulumi.input_type
class IPAddressClaimStatusConditionsArgs:
    def __init__(__self__, *,
                 last_transition_time: pulumi.Input[Optional[_builtins.str]] = None,
                 message: pulumi.Input[Optional[_builtins.str]] = None,
                 observed_generation: pulumi.Input[Optional[_builtins.int]] = None,
                 reason: pulumi.Input[Optional[_builtins.str]] = None,
                 status: pulumi.Input[Optional[_builtins.str]] = None,
                 type: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Condition contains details for one aspect of the current state of this API Resource.

        :param pulumi.Input[_builtins.str] last_transition_time: lastTransitionTime is the last time the condition transitioned from one status to another.
               This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
        :param pulumi.Input[_builtins.str] message: message is a human readable message indicating details about the transition.
               This may be an empty string.
        :param pulumi.Input[_builtins.int] observed_generation: observedGeneration represents the .metadata.generation that the condition was set based upon.
               For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
               with respect to the current state of the instance.
        :param pulumi.Input[_builtins.str] reason: reason contains a programmatic identifier indicating the reason for the condition's last transition.
               Producers of specific condition types may define expected values and meanings for this field,
               and whether the values are considered a guaranteed API.
               The value should be a CamelCase string.
               This field may not be empty.
        :param pulumi.Input[_builtins.str] status: status of the condition, one of True, False, Unknown.
        :param pulumi.Input[_builtins.str] type: type of condition in CamelCase or in foo.example.com/CamelCase.
        """
        if last_transition_time is not None:
            pulumi.set(__self__, "last_transition_time", last_transition_time)
        if message is not None:
            pulumi.set(__self__, "message", message)
        if observed_generation is not None:
            pulumi.set(__self__, "observed_generation", observed_generation)
        if reason is not None:
            pulumi.set(__self__, "reason", reason)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if type is not None:
            pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter(name="lastTransitionTime")
    def last_transition_time(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        lastTransitionTime is the last time the condition transitioned from one status to another.
        This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
        """
        return pulumi.get(self, "last_transition_time")

    @last_transition_time.setter
    def last_transition_time(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "last_transition_time", value)

    @_builtins.property
    @pulumi.getter
    def message(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        message is a human readable message indicating details about the transition.
        This may be an empty string.
        """
        return pulumi.get(self, "message")

    @message.setter
    def message(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "message", value)

    @_builtins.property
    @pulumi.getter(name="observedGeneration")
    def observed_generation(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        observedGeneration represents the .metadata.generation that the condition was set based upon.
        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
        with respect to the current state of the instance.
        """
        return pulumi.get(self, "observed_generation")

    @observed_generation.setter
    def observed_generation(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "observed_generation", value)

    @_builtins.property
    @pulumi.getter
    def reason(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        reason contains a programmatic identifier indicating the reason for the condition's last transition.
        Producers of specific condition types may define expected values and meanings for this field,
        and whether the values are considered a guaranteed API.
        The value should be a CamelCase string.
        This field may not be empty.
        """
        return pulumi.get(self, "reason")

    @reason.setter
    def reason(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "reason", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        status of the condition, one of True, False, Unknown.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        type of condition in CamelCase or in foo.example.com/CamelCase.
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "type", value)


class IPAddressClaimStatusDeprecatedV1beta1ConditionsArgsDict(TypedDict):
    """
    Condition defines an observation of a Cluster API resource operational state.

    Deprecated: This type is deprecated and is going to be removed when support for v1beta1 will be dropped. Please see https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20240916-improve-status-in-CAPI-resources.md for more details.
    """
    last_transition_time: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    lastTransitionTime is the last time the condition transitioned from one status to another.
    This should be when the underlying condition changed. If that is not known, then using the time when
    the API field changed is acceptable.
    """
    message: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    message is a human readable message indicating details about the transition.
    This field may be empty.
    """
    reason: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    reason is the reason for the condition's last transition in CamelCase.
    The specific API may choose whether or not this field is considered a guaranteed API.
    This field may be empty.
    """
    severity: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    severity provides an explicit classification of Reason code, so the users or machines can immediately
    understand the current situation and act accordingly.
    The Severity field MUST be set only when Status=False.
    """
    status: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    status of the condition, one of True, False, Unknown.
    """
    type: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    type of condition in CamelCase or in foo.example.com/CamelCase.
    Many .condition.type values are consistent across resources like Available, but because arbitrary conditions
    can be useful (see .node.status.conditions), the ability to deconflict is important.
    """

@pulumi.input_type
class IPAddressClaimStatusDeprecatedV1beta1ConditionsArgs:
    def __init__(__self__, *,
                 last_transition_time: pulumi.Input[Optional[_builtins.str]] = None,
                 message: pulumi.Input[Optional[_builtins.str]] = None,
                 reason: pulumi.Input[Optional[_builtins.str]] = None,
                 severity: pulumi.Input[Optional[_builtins.str]] = None,
                 status: pulumi.Input[Optional[_builtins.str]] = None,
                 type: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Condition defines an observation of a Cluster API resource operational state.

        Deprecated: This type is deprecated and is going to be removed when support for v1beta1 will be dropped. Please see https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20240916-improve-status-in-CAPI-resources.md for more details.

        :param pulumi.Input[_builtins.str] last_transition_time: lastTransitionTime is the last time the condition transitioned from one status to another.
               This should be when the underlying condition changed. If that is not known, then using the time when
               the API field changed is acceptable.
        :param pulumi.Input[_builtins.str] message: message is a human readable message indicating details about the transition.
               This field may be empty.
        :param pulumi.Input[_builtins.str] reason: reason is the reason for the condition's last transition in CamelCase.
               The specific API may choose whether or not this field is considered a guaranteed API.
               This field may be empty.
        :param pulumi.Input[_builtins.str] severity: severity provides an explicit classification of Reason code, so the users or machines can immediately
               understand the current situation and act accordingly.
               The Severity field MUST be set only when Status=False.
        :param pulumi.Input[_builtins.str] status: status of the condition, one of True, False, Unknown.
        :param pulumi.Input[_builtins.str] type: type of condition in CamelCase or in foo.example.com/CamelCase.
               Many .condition.type values are consistent across resources like Available, but because arbitrary conditions
               can be useful (see .node.status.conditions), the ability to deconflict is important.
        """
        if last_transition_time is not None:
            pulumi.set(__self__, "last_transition_time", last_transition_time)
        if message is not None:
            pulumi.set(__self__, "message", message)
        if reason is not None:
            pulumi.set(__self__, "reason", reason)
        if severity is not None:
            pulumi.set(__self__, "severity", severity)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if type is not None:
            pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter(name="lastTransitionTime")
    def last_transition_time(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        lastTransitionTime is the last time the condition transitioned from one status to another.
        This should be when the underlying condition changed. If that is not known, then using the time when
        the API field changed is acceptable.
        """
        return pulumi.get(self, "last_transition_time")

    @last_transition_time.setter
    def last_transition_time(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "last_transition_time", value)

    @_builtins.property
    @pulumi.getter
    def message(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        message is a human readable message indicating details about the transition.
        This field may be empty.
        """
        return pulumi.get(self, "message")

    @message.setter
    def message(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "message", value)

    @_builtins.property
    @pulumi.getter
    def reason(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        reason is the reason for the condition's last transition in CamelCase.
        The specific API may choose whether or not this field is considered a guaranteed API.
        This field may be empty.
        """
        return pulumi.get(self, "reason")

    @reason.setter
    def reason(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "reason", value)

    @_builtins.property
    @pulumi.getter
    def severity(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        severity provides an explicit classification of Reason code, so the users or machines can immediately
        understand the current situation and act accordingly.
        The Severity field MUST be set only when Status=False.
        """
        return pulumi.get(self, "severity")

    @severity.setter
    def severity(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "severity", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        status of the condition, one of True, False, Unknown.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        type of condition in CamelCase or in foo.example.com/CamelCase.
        Many .condition.type values are consistent across resources like Available, but because arbitrary conditions
        can be useful (see .node.status.conditions), the ability to deconflict is important.
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "type", value)


class IPAddressClaimStatusDeprecatedV1beta1ArgsDict(TypedDict):
    """
    v1beta1 groups all the status fields that are deprecated and will be removed when support for v1beta1 will be dropped.
    """
    conditions: NotRequired[pulumi.Input[Optional[Sequence[pulumi.Input['IPAddressClaimStatusDeprecatedV1beta1ConditionsArgs']]]]]
    """
    conditions summarises the current state of the IPAddressClaim

    Deprecated: This field is deprecated and is going to be removed when support for v1beta1 will be dropped. Please see https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20240916-improve-status-in-CAPI-resources.md for more details.
    """

@pulumi.input_type
class IPAddressClaimStatusDeprecatedV1beta1Args:
    def __init__(__self__, *,
                 conditions: pulumi.Input[Optional[Sequence[pulumi.Input['IPAddressClaimStatusDeprecatedV1beta1ConditionsArgs']]]] = None):
        """
        v1beta1 groups all the status fields that are deprecated and will be removed when support for v1beta1 will be dropped.

        :param pulumi.Input[Sequence[pulumi.Input['IPAddressClaimStatusDeprecatedV1beta1ConditionsArgs']]] conditions: conditions summarises the current state of the IPAddressClaim
               
               Deprecated: This field is deprecated and is going to be removed when support for v1beta1 will be dropped. Please see https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20240916-improve-status-in-CAPI-resources.md for more details.
        """
        if conditions is not None:
            pulumi.set(__self__, "conditions", conditions)

    @_builtins.property
    @pulumi.getter
    def conditions(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['IPAddressClaimStatusDeprecatedV1beta1ConditionsArgs']]]]:
        """
        conditions summarises the current state of the IPAddressClaim

        Deprecated: This field is deprecated and is going to be removed when support for v1beta1 will be dropped. Please see https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20240916-improve-status-in-CAPI-resources.md for more details.
        """
        return pulumi.get(self, "conditions")

    @conditions.setter
    def conditions(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['IPAddressClaimStatusDeprecatedV1beta1ConditionsArgs']]]]):
        pulumi.set(self, "conditions", value)


class IPAddressClaimStatusDeprecatedArgsDict(TypedDict):
    """
    deprecated groups all the status fields that are deprecated and will be removed when all the nested field are removed.
    """
    v1beta1: NotRequired[pulumi.Input[Optional['IPAddressClaimStatusDeprecatedV1beta1Args']]]

@pulumi.input_type
class IPAddressClaimStatusDeprecatedArgs:
    def __init__(__self__, *,
                 v1beta1: pulumi.Input[Optional['IPAddressClaimStatusDeprecatedV1beta1Args']] = None):
        """
        deprecated groups all the status fields that are deprecated and will be removed when all the nested field are removed.
        """
        if v1beta1 is not None:
            pulumi.set(__self__, "v1beta1", v1beta1)

    @_builtins.property
    @pulumi.getter
    def v1beta1(self) -> pulumi.Input[Optional['IPAddressClaimStatusDeprecatedV1beta1Args']]:
        return pulumi.get(self, "v1beta1")

    @v1beta1.setter
    def v1beta1(self, value: pulumi.Input[Optional['IPAddressClaimStatusDeprecatedV1beta1Args']]):
        pulumi.set(self, "v1beta1", value)


class IPAddressClaimStatusArgsDict(TypedDict):
    """
    status is the observed state of IPAddressClaim.
    """
    address_ref: NotRequired[pulumi.Input[Optional['IPAddressClaimStatusAddressRefArgs']]]
    conditions: NotRequired[pulumi.Input[Optional[Sequence[pulumi.Input['IPAddressClaimStatusConditionsArgs']]]]]
    """
    conditions represents the observations of a IPAddressClaim's current state.
    Known condition types are Ready.
    """
    deprecated: NotRequired[pulumi.Input[Optional['IPAddressClaimStatusDeprecatedArgs']]]

@pulumi.input_type
class IPAddressClaimStatusArgs:
    def __init__(__self__, *,
                 address_ref: pulumi.Input[Optional['IPAddressClaimStatusAddressRefArgs']] = None,
                 conditions: pulumi.Input[Optional[Sequence[pulumi.Input['IPAddressClaimStatusConditionsArgs']]]] = None,
                 deprecated: pulumi.Input[Optional['IPAddressClaimStatusDeprecatedArgs']] = None):
        """
        status is the observed state of IPAddressClaim.

        :param pulumi.Input[Sequence[pulumi.Input['IPAddressClaimStatusConditionsArgs']]] conditions: conditions represents the observations of a IPAddressClaim's current state.
               Known condition types are Ready.
        """
        if address_ref is not None:
            pulumi.set(__self__, "address_ref", address_ref)
        if conditions is not None:
            pulumi.set(__self__, "conditions", conditions)
        if deprecated is not None:
            pulumi.set(__self__, "deprecated", deprecated)

    @_builtins.property
    @pulumi.getter(name="addressRef")
    def address_ref(self) -> pulumi.Input[Optional['IPAddressClaimStatusAddressRefArgs']]:
        return pulumi.get(self, "address_ref")

    @address_ref.setter
    def address_ref(self, value: pulumi.Input[Optional['IPAddressClaimStatusAddressRefArgs']]):
        pulumi.set(self, "address_ref", value)

    @_builtins.property
    @pulumi.getter
    def conditions(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['IPAddressClaimStatusConditionsArgs']]]]:
        """
        conditions represents the observations of a IPAddressClaim's current state.
        Known condition types are Ready.
        """
        return pulumi.get(self, "conditions")

    @conditions.setter
    def conditions(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['IPAddressClaimStatusConditionsArgs']]]]):
        pulumi.set(self, "conditions", value)

    @_builtins.property
    @pulumi.getter
    def deprecated(self) -> pulumi.Input[Optional['IPAddressClaimStatusDeprecatedArgs']]:
        return pulumi.get(self, "deprecated")

    @deprecated.setter
    def deprecated(self, value: pulumi.Input[Optional['IPAddressClaimStatusDeprecatedArgs']]):
        pulumi.set(self, "deprecated", value)


class IPAddressClaimArgsDict(TypedDict):
    """
    IPAddressClaim is the Schema for the ipaddressclaim API.
    """
    api_version: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: NotRequired[pulumi.Input[Optional['_meta.v1.ObjectMetaArgs']]]
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: NotRequired[pulumi.Input[Optional['IPAddressClaimSpecArgs']]]
    status: NotRequired[pulumi.Input[Optional['IPAddressClaimStatusArgs']]]

@pulumi.input_type
class IPAddressClaimArgs:
    def __init__(__self__, *,
                 api_version: pulumi.Input[Optional[_builtins.str]] = None,
                 kind: pulumi.Input[Optional[_builtins.str]] = None,
                 metadata: pulumi.Input[Optional['_meta.v1.ObjectMetaArgs']] = None,
                 spec: pulumi.Input[Optional['IPAddressClaimSpecArgs']] = None,
                 status: pulumi.Input[Optional['IPAddressClaimStatusArgs']] = None):
        """
        IPAddressClaim is the Schema for the ipaddressclaim API.

        :param pulumi.Input[_builtins.str] api_version: APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
        :param pulumi.Input[_builtins.str] kind: Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        :param pulumi.Input['_meta.v1.ObjectMetaArgs'] metadata: Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        """
        if api_version is not None:
            pulumi.set(__self__, "api_version", 'ipam.cluster.x-k8s.io/v1beta2')
        if kind is not None:
            pulumi.set(__self__, "kind", 'IPAddressClaim')
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if spec is not None:
            pulumi.set(__self__, "spec", spec)
        if status is not None:
            pulumi.set(__self__, "status", status)

    @_builtins.property
    @pulumi.getter(name="apiVersion")
    def api_version(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
        """
        return pulumi.get(self, "api_version")

    @api_version.setter
    def api_version(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "api_version", value)

    @_builtins.property
    @pulumi.getter
    def kind(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        """
        return pulumi.get(self, "kind")

    @kind.setter
    def kind(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "kind", value)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Input[Optional['_meta.v1.ObjectMetaArgs']]:
        """
        Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        """
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: pulumi.Input[Optional['_meta.v1.ObjectMetaArgs']]):
        pulumi.set(self, "metadata", value)

    @_builtins.property
    @pulumi.getter
    def spec(self) -> pulumi.Input[Optional['IPAddressClaimSpecArgs']]:
        return pulumi.get(self, "spec")

    @spec.setter
    def spec(self, value: pulumi.Input[Optional['IPAddressClaimSpecArgs']]):
        pulumi.set(self, "spec", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Input[Optional['IPAddressClaimStatusArgs']]:
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: pulumi.Input[Optional['IPAddressClaimStatusArgs']]):
        pulumi.set(self, "status", value)


class IPAddressSpecClaimRefPatchArgsDict(TypedDict):
    """
    claimRef is a reference to the claim this IPAddress was created for.
    """
    name: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    name of the IPAddressClaim.
    name must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character.
    """

@pulumi.input_type
class IPAddressSpecClaimRefPatchArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[Optional[_builtins.str]] = None):
        """
        claimRef is a reference to the claim this IPAddress was created for.

        :param pulumi.Input[_builtins.str] name: name of the IPAddressClaim.
               name must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character.
        """
        if name is not None:
            pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        name of the IPAddressClaim.
        name must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)


class IPAddressSpecClaimRefArgsDict(TypedDict):
    """
    claimRef is a reference to the claim this IPAddress was created for.
    """
    name: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    name of the IPAddressClaim.
    name must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character.
    """

@pulumi.input_type
class IPAddressSpecClaimRefArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[Optional[_builtins.str]] = None):
        """
        claimRef is a reference to the claim this IPAddress was created for.

        :param pulumi.Input[_builtins.str] name: name of the IPAddressClaim.
               name must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character.
        """
        if name is not None:
            pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        name of the IPAddressClaim.
        name must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)


class IPAddressSpecPatchArgsDict(TypedDict):
    """
    spec is the desired state of IPAddress.
    """
    address: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    address is the IP address.
    """
    claim_ref: NotRequired[pulumi.Input[Optional['IPAddressSpecClaimRefPatchArgs']]]
    gateway: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    gateway is the network gateway of the network the address is from.
    """
    pool_ref: NotRequired[pulumi.Input[Optional['IPAddressSpecPoolRefPatchArgs']]]
    prefix: NotRequired[pulumi.Input[Optional[_builtins.int]]]
    """
    prefix is the prefix of the address.
    """

@pulumi.input_type
class IPAddressSpecPatchArgs:
    def __init__(__self__, *,
                 address: pulumi.Input[Optional[_builtins.str]] = None,
                 claim_ref: pulumi.Input[Optional['IPAddressSpecClaimRefPatchArgs']] = None,
                 gateway: pulumi.Input[Optional[_builtins.str]] = None,
                 pool_ref: pulumi.Input[Optional['IPAddressSpecPoolRefPatchArgs']] = None,
                 prefix: pulumi.Input[Optional[_builtins.int]] = None):
        """
        spec is the desired state of IPAddress.

        :param pulumi.Input[_builtins.str] address: address is the IP address.
        :param pulumi.Input[_builtins.str] gateway: gateway is the network gateway of the network the address is from.
        :param pulumi.Input[_builtins.int] prefix: prefix is the prefix of the address.
        """
        if address is not None:
            pulumi.set(__self__, "address", address)
        if claim_ref is not None:
            pulumi.set(__self__, "claim_ref", claim_ref)
        if gateway is not None:
            pulumi.set(__self__, "gateway", gateway)
        if pool_ref is not None:
            pulumi.set(__self__, "pool_ref", pool_ref)
        if prefix is not None:
            pulumi.set(__self__, "prefix", prefix)

    @_builtins.property
    @pulumi.getter
    def address(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        address is the IP address.
        """
        return pulumi.get(self, "address")

    @address.setter
    def address(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "address", value)

    @_builtins.property
    @pulumi.getter(name="claimRef")
    def claim_ref(self) -> pulumi.Input[Optional['IPAddressSpecClaimRefPatchArgs']]:
        return pulumi.get(self, "claim_ref")

    @claim_ref.setter
    def claim_ref(self, value: pulumi.Input[Optional['IPAddressSpecClaimRefPatchArgs']]):
        pulumi.set(self, "claim_ref", value)

    @_builtins.property
    @pulumi.getter
    def gateway(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        gateway is the network gateway of the network the address is from.
        """
        return pulumi.get(self, "gateway")

    @gateway.setter
    def gateway(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "gateway", value)

    @_builtins.property
    @pulumi.getter(name="poolRef")
    def pool_ref(self) -> pulumi.Input[Optional['IPAddressSpecPoolRefPatchArgs']]:
        return pulumi.get(self, "pool_ref")

    @pool_ref.setter
    def pool_ref(self, value: pulumi.Input[Optional['IPAddressSpecPoolRefPatchArgs']]):
        pulumi.set(self, "pool_ref", value)

    @_builtins.property
    @pulumi.getter
    def prefix(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        prefix is the prefix of the address.
        """
        return pulumi.get(self, "prefix")

    @prefix.setter
    def prefix(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "prefix", value)


class IPAddressSpecPoolRefPatchArgsDict(TypedDict):
    """
    poolRef is a reference to the pool that this IPAddress was created from.
    """
    api_group: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    apiGroup of the IPPool.
    apiGroup must be fully qualified domain name.
    """
    kind: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    kind of the IPPool.
    kind must consist of alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character.
    """
    name: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    name of the IPPool.
    name must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character.
    """

@pulumi.input_type
class IPAddressSpecPoolRefPatchArgs:
    def __init__(__self__, *,
                 api_group: pulumi.Input[Optional[_builtins.str]] = None,
                 kind: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None):
        """
        poolRef is a reference to the pool that this IPAddress was created from.

        :param pulumi.Input[_builtins.str] api_group: apiGroup of the IPPool.
               apiGroup must be fully qualified domain name.
        :param pulumi.Input[_builtins.str] kind: kind of the IPPool.
               kind must consist of alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character.
        :param pulumi.Input[_builtins.str] name: name of the IPPool.
               name must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character.
        """
        if api_group is not None:
            pulumi.set(__self__, "api_group", api_group)
        if kind is not None:
            pulumi.set(__self__, "kind", kind)
        if name is not None:
            pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter(name="apiGroup")
    def api_group(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        apiGroup of the IPPool.
        apiGroup must be fully qualified domain name.
        """
        return pulumi.get(self, "api_group")

    @api_group.setter
    def api_group(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "api_group", value)

    @_builtins.property
    @pulumi.getter
    def kind(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        kind of the IPPool.
        kind must consist of alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character.
        """
        return pulumi.get(self, "kind")

    @kind.setter
    def kind(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "kind", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        name of the IPPool.
        name must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)


class IPAddressSpecPoolRefArgsDict(TypedDict):
    """
    poolRef is a reference to the pool that this IPAddress was created from.
    """
    api_group: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    apiGroup of the IPPool.
    apiGroup must be fully qualified domain name.
    """
    kind: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    kind of the IPPool.
    kind must consist of alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character.
    """
    name: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    name of the IPPool.
    name must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character.
    """

@pulumi.input_type
class IPAddressSpecPoolRefArgs:
    def __init__(__self__, *,
                 api_group: pulumi.Input[Optional[_builtins.str]] = None,
                 kind: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None):
        """
        poolRef is a reference to the pool that this IPAddress was created from.

        :param pulumi.Input[_builtins.str] api_group: apiGroup of the IPPool.
               apiGroup must be fully qualified domain name.
        :param pulumi.Input[_builtins.str] kind: kind of the IPPool.
               kind must consist of alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character.
        :param pulumi.Input[_builtins.str] name: name of the IPPool.
               name must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character.
        """
        if api_group is not None:
            pulumi.set(__self__, "api_group", api_group)
        if kind is not None:
            pulumi.set(__self__, "kind", kind)
        if name is not None:
            pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter(name="apiGroup")
    def api_group(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        apiGroup of the IPPool.
        apiGroup must be fully qualified domain name.
        """
        return pulumi.get(self, "api_group")

    @api_group.setter
    def api_group(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "api_group", value)

    @_builtins.property
    @pulumi.getter
    def kind(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        kind of the IPPool.
        kind must consist of alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character.
        """
        return pulumi.get(self, "kind")

    @kind.setter
    def kind(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "kind", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        name of the IPPool.
        name must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)


class IPAddressSpecArgsDict(TypedDict):
    """
    spec is the desired state of IPAddress.
    """
    address: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    address is the IP address.
    """
    claim_ref: NotRequired[pulumi.Input[Optional['IPAddressSpecClaimRefArgs']]]
    gateway: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    gateway is the network gateway of the network the address is from.
    """
    pool_ref: NotRequired[pulumi.Input[Optional['IPAddressSpecPoolRefArgs']]]
    prefix: NotRequired[pulumi.Input[Optional[_builtins.int]]]
    """
    prefix is the prefix of the address.
    """

@pulumi.input_type
class IPAddressSpecArgs:
    def __init__(__self__, *,
                 address: pulumi.Input[Optional[_builtins.str]] = None,
                 claim_ref: pulumi.Input[Optional['IPAddressSpecClaimRefArgs']] = None,
                 gateway: pulumi.Input[Optional[_builtins.str]] = None,
                 pool_ref: pulumi.Input[Optional['IPAddressSpecPoolRefArgs']] = None,
                 prefix: pulumi.Input[Optional[_builtins.int]] = None):
        """
        spec is the desired state of IPAddress.

        :param pulumi.Input[_builtins.str] address: address is the IP address.
        :param pulumi.Input[_builtins.str] gateway: gateway is the network gateway of the network the address is from.
        :param pulumi.Input[_builtins.int] prefix: prefix is the prefix of the address.
        """
        if address is not None:
            pulumi.set(__self__, "address", address)
        if claim_ref is not None:
            pulumi.set(__self__, "claim_ref", claim_ref)
        if gateway is not None:
            pulumi.set(__self__, "gateway", gateway)
        if pool_ref is not None:
            pulumi.set(__self__, "pool_ref", pool_ref)
        if prefix is not None:
            pulumi.set(__self__, "prefix", prefix)

    @_builtins.property
    @pulumi.getter
    def address(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        address is the IP address.
        """
        return pulumi.get(self, "address")

    @address.setter
    def address(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "address", value)

    @_builtins.property
    @pulumi.getter(name="claimRef")
    def claim_ref(self) -> pulumi.Input[Optional['IPAddressSpecClaimRefArgs']]:
        return pulumi.get(self, "claim_ref")

    @claim_ref.setter
    def claim_ref(self, value: pulumi.Input[Optional['IPAddressSpecClaimRefArgs']]):
        pulumi.set(self, "claim_ref", value)

    @_builtins.property
    @pulumi.getter
    def gateway(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        gateway is the network gateway of the network the address is from.
        """
        return pulumi.get(self, "gateway")

    @gateway.setter
    def gateway(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "gateway", value)

    @_builtins.property
    @pulumi.getter(name="poolRef")
    def pool_ref(self) -> pulumi.Input[Optional['IPAddressSpecPoolRefArgs']]:
        return pulumi.get(self, "pool_ref")

    @pool_ref.setter
    def pool_ref(self, value: pulumi.Input[Optional['IPAddressSpecPoolRefArgs']]):
        pulumi.set(self, "pool_ref", value)

    @_builtins.property
    @pulumi.getter
    def prefix(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        prefix is the prefix of the address.
        """
        return pulumi.get(self, "prefix")

    @prefix.setter
    def prefix(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "prefix", value)


class IPAddressArgsDict(TypedDict):
    """
    IPAddress is the Schema for the ipaddress API.
    """
    api_version: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: NotRequired[pulumi.Input[Optional['_meta.v1.ObjectMetaArgs']]]
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: NotRequired[pulumi.Input[Optional['IPAddressSpecArgs']]]

@pulumi.input_type
class IPAddressArgs:
    def __init__(__self__, *,
                 api_version: pulumi.Input[Optional[_builtins.str]] = None,
                 kind: pulumi.Input[Optional[_builtins.str]] = None,
                 metadata: pulumi.Input[Optional['_meta.v1.ObjectMetaArgs']] = None,
                 spec: pulumi.Input[Optional['IPAddressSpecArgs']] = None):
        """
        IPAddress is the Schema for the ipaddress API.

        :param pulumi.Input[_builtins.str] api_version: APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
        :param pulumi.Input[_builtins.str] kind: Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        :param pulumi.Input['_meta.v1.ObjectMetaArgs'] metadata: Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        """
        if api_version is not None:
            pulumi.set(__self__, "api_version", 'ipam.cluster.x-k8s.io/v1beta2')
        if kind is not None:
            pulumi.set(__self__, "kind", 'IPAddress')
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if spec is not None:
            pulumi.set(__self__, "spec", spec)

    @_builtins.property
    @pulumi.getter(name="apiVersion")
    def api_version(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
        """
        return pulumi.get(self, "api_version")

    @api_version.setter
    def api_version(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "api_version", value)

    @_builtins.property
    @pulumi.getter
    def kind(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        """
        return pulumi.get(self, "kind")

    @kind.setter
    def kind(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "kind", value)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Input[Optional['_meta.v1.ObjectMetaArgs']]:
        """
        Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
        """
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: pulumi.Input[Optional['_meta.v1.ObjectMetaArgs']]):
        pulumi.set(self, "metadata", value)

    @_builtins.property
    @pulumi.getter
    def spec(self) -> pulumi.Input[Optional['IPAddressSpecArgs']]:
        return pulumi.get(self, "spec")

    @spec.setter
    def spec(self, value: pulumi.Input[Optional['IPAddressSpecArgs']]):
        pulumi.set(self, "spec", value)


