# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetWorkflowJobTemplateResult',
    'AwaitableGetWorkflowJobTemplateResult',
    'get_workflow_job_template',
    'get_workflow_job_template_output',
]

@pulumi.output_type
class GetWorkflowJobTemplateResult:
    """
    A collection of values returned by getWorkflowJobTemplate.
    """
    def __init__(__self__, allow_simultaneous=None, ask_inventory_on_launch=None, ask_labels_on_launch=None, ask_limit_on_launch=None, ask_scm_branch_on_launch=None, ask_skip_tags_on_launch=None, ask_tags_on_launch=None, ask_variables_on_launch=None, description=None, extra_vars=None, id=None, inventory=None, job_tags=None, limit=None, name=None, organization=None, scm_branch=None, skip_tags=None, survey_enabled=None, webhook_credential=None, webhook_service=None):
        if allow_simultaneous and not isinstance(allow_simultaneous, bool):
            raise TypeError("Expected argument 'allow_simultaneous' to be a bool")
        pulumi.set(__self__, "allow_simultaneous", allow_simultaneous)
        if ask_inventory_on_launch and not isinstance(ask_inventory_on_launch, bool):
            raise TypeError("Expected argument 'ask_inventory_on_launch' to be a bool")
        pulumi.set(__self__, "ask_inventory_on_launch", ask_inventory_on_launch)
        if ask_labels_on_launch and not isinstance(ask_labels_on_launch, bool):
            raise TypeError("Expected argument 'ask_labels_on_launch' to be a bool")
        pulumi.set(__self__, "ask_labels_on_launch", ask_labels_on_launch)
        if ask_limit_on_launch and not isinstance(ask_limit_on_launch, bool):
            raise TypeError("Expected argument 'ask_limit_on_launch' to be a bool")
        pulumi.set(__self__, "ask_limit_on_launch", ask_limit_on_launch)
        if ask_scm_branch_on_launch and not isinstance(ask_scm_branch_on_launch, bool):
            raise TypeError("Expected argument 'ask_scm_branch_on_launch' to be a bool")
        pulumi.set(__self__, "ask_scm_branch_on_launch", ask_scm_branch_on_launch)
        if ask_skip_tags_on_launch and not isinstance(ask_skip_tags_on_launch, bool):
            raise TypeError("Expected argument 'ask_skip_tags_on_launch' to be a bool")
        pulumi.set(__self__, "ask_skip_tags_on_launch", ask_skip_tags_on_launch)
        if ask_tags_on_launch and not isinstance(ask_tags_on_launch, bool):
            raise TypeError("Expected argument 'ask_tags_on_launch' to be a bool")
        pulumi.set(__self__, "ask_tags_on_launch", ask_tags_on_launch)
        if ask_variables_on_launch and not isinstance(ask_variables_on_launch, bool):
            raise TypeError("Expected argument 'ask_variables_on_launch' to be a bool")
        pulumi.set(__self__, "ask_variables_on_launch", ask_variables_on_launch)
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if extra_vars and not isinstance(extra_vars, str):
            raise TypeError("Expected argument 'extra_vars' to be a str")
        pulumi.set(__self__, "extra_vars", extra_vars)
        if id and not isinstance(id, float):
            raise TypeError("Expected argument 'id' to be a float")
        pulumi.set(__self__, "id", id)
        if inventory and not isinstance(inventory, float):
            raise TypeError("Expected argument 'inventory' to be a float")
        pulumi.set(__self__, "inventory", inventory)
        if job_tags and not isinstance(job_tags, str):
            raise TypeError("Expected argument 'job_tags' to be a str")
        pulumi.set(__self__, "job_tags", job_tags)
        if limit and not isinstance(limit, str):
            raise TypeError("Expected argument 'limit' to be a str")
        pulumi.set(__self__, "limit", limit)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if organization and not isinstance(organization, float):
            raise TypeError("Expected argument 'organization' to be a float")
        pulumi.set(__self__, "organization", organization)
        if scm_branch and not isinstance(scm_branch, str):
            raise TypeError("Expected argument 'scm_branch' to be a str")
        pulumi.set(__self__, "scm_branch", scm_branch)
        if skip_tags and not isinstance(skip_tags, str):
            raise TypeError("Expected argument 'skip_tags' to be a str")
        pulumi.set(__self__, "skip_tags", skip_tags)
        if survey_enabled and not isinstance(survey_enabled, bool):
            raise TypeError("Expected argument 'survey_enabled' to be a bool")
        pulumi.set(__self__, "survey_enabled", survey_enabled)
        if webhook_credential and not isinstance(webhook_credential, float):
            raise TypeError("Expected argument 'webhook_credential' to be a float")
        pulumi.set(__self__, "webhook_credential", webhook_credential)
        if webhook_service and not isinstance(webhook_service, str):
            raise TypeError("Expected argument 'webhook_service' to be a str")
        pulumi.set(__self__, "webhook_service", webhook_service)

    @_builtins.property
    @pulumi.getter(name="allowSimultaneous")
    def allow_simultaneous(self) -> _builtins.bool:
        return pulumi.get(self, "allow_simultaneous")

    @_builtins.property
    @pulumi.getter(name="askInventoryOnLaunch")
    def ask_inventory_on_launch(self) -> _builtins.bool:
        return pulumi.get(self, "ask_inventory_on_launch")

    @_builtins.property
    @pulumi.getter(name="askLabelsOnLaunch")
    def ask_labels_on_launch(self) -> _builtins.bool:
        return pulumi.get(self, "ask_labels_on_launch")

    @_builtins.property
    @pulumi.getter(name="askLimitOnLaunch")
    def ask_limit_on_launch(self) -> _builtins.bool:
        return pulumi.get(self, "ask_limit_on_launch")

    @_builtins.property
    @pulumi.getter(name="askScmBranchOnLaunch")
    def ask_scm_branch_on_launch(self) -> _builtins.bool:
        return pulumi.get(self, "ask_scm_branch_on_launch")

    @_builtins.property
    @pulumi.getter(name="askSkipTagsOnLaunch")
    def ask_skip_tags_on_launch(self) -> _builtins.bool:
        return pulumi.get(self, "ask_skip_tags_on_launch")

    @_builtins.property
    @pulumi.getter(name="askTagsOnLaunch")
    def ask_tags_on_launch(self) -> _builtins.bool:
        return pulumi.get(self, "ask_tags_on_launch")

    @_builtins.property
    @pulumi.getter(name="askVariablesOnLaunch")
    def ask_variables_on_launch(self) -> _builtins.bool:
        return pulumi.get(self, "ask_variables_on_launch")

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="extraVars")
    def extra_vars(self) -> _builtins.str:
        return pulumi.get(self, "extra_vars")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.float:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def inventory(self) -> _builtins.float:
        return pulumi.get(self, "inventory")

    @_builtins.property
    @pulumi.getter(name="jobTags")
    def job_tags(self) -> _builtins.str:
        return pulumi.get(self, "job_tags")

    @_builtins.property
    @pulumi.getter
    def limit(self) -> _builtins.str:
        return pulumi.get(self, "limit")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def organization(self) -> _builtins.float:
        return pulumi.get(self, "organization")

    @_builtins.property
    @pulumi.getter(name="scmBranch")
    def scm_branch(self) -> _builtins.str:
        return pulumi.get(self, "scm_branch")

    @_builtins.property
    @pulumi.getter(name="skipTags")
    def skip_tags(self) -> _builtins.str:
        return pulumi.get(self, "skip_tags")

    @_builtins.property
    @pulumi.getter(name="surveyEnabled")
    def survey_enabled(self) -> _builtins.bool:
        return pulumi.get(self, "survey_enabled")

    @_builtins.property
    @pulumi.getter(name="webhookCredential")
    def webhook_credential(self) -> _builtins.float:
        return pulumi.get(self, "webhook_credential")

    @_builtins.property
    @pulumi.getter(name="webhookService")
    def webhook_service(self) -> _builtins.str:
        return pulumi.get(self, "webhook_service")


class AwaitableGetWorkflowJobTemplateResult(GetWorkflowJobTemplateResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetWorkflowJobTemplateResult(
            allow_simultaneous=self.allow_simultaneous,
            ask_inventory_on_launch=self.ask_inventory_on_launch,
            ask_labels_on_launch=self.ask_labels_on_launch,
            ask_limit_on_launch=self.ask_limit_on_launch,
            ask_scm_branch_on_launch=self.ask_scm_branch_on_launch,
            ask_skip_tags_on_launch=self.ask_skip_tags_on_launch,
            ask_tags_on_launch=self.ask_tags_on_launch,
            ask_variables_on_launch=self.ask_variables_on_launch,
            description=self.description,
            extra_vars=self.extra_vars,
            id=self.id,
            inventory=self.inventory,
            job_tags=self.job_tags,
            limit=self.limit,
            name=self.name,
            organization=self.organization,
            scm_branch=self.scm_branch,
            skip_tags=self.skip_tags,
            survey_enabled=self.survey_enabled,
            webhook_credential=self.webhook_credential,
            webhook_service=self.webhook_service)


def get_workflow_job_template(id: Optional[_builtins.float] = None,
                              name: Optional[_builtins.str] = None,
                              opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetWorkflowJobTemplateResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('awx:index/getWorkflowJobTemplate:getWorkflowJobTemplate', __args__, opts=opts, typ=GetWorkflowJobTemplateResult, package_ref=_utilities.get_package()).value

    return AwaitableGetWorkflowJobTemplateResult(
        allow_simultaneous=pulumi.get(__ret__, 'allow_simultaneous'),
        ask_inventory_on_launch=pulumi.get(__ret__, 'ask_inventory_on_launch'),
        ask_labels_on_launch=pulumi.get(__ret__, 'ask_labels_on_launch'),
        ask_limit_on_launch=pulumi.get(__ret__, 'ask_limit_on_launch'),
        ask_scm_branch_on_launch=pulumi.get(__ret__, 'ask_scm_branch_on_launch'),
        ask_skip_tags_on_launch=pulumi.get(__ret__, 'ask_skip_tags_on_launch'),
        ask_tags_on_launch=pulumi.get(__ret__, 'ask_tags_on_launch'),
        ask_variables_on_launch=pulumi.get(__ret__, 'ask_variables_on_launch'),
        description=pulumi.get(__ret__, 'description'),
        extra_vars=pulumi.get(__ret__, 'extra_vars'),
        id=pulumi.get(__ret__, 'id'),
        inventory=pulumi.get(__ret__, 'inventory'),
        job_tags=pulumi.get(__ret__, 'job_tags'),
        limit=pulumi.get(__ret__, 'limit'),
        name=pulumi.get(__ret__, 'name'),
        organization=pulumi.get(__ret__, 'organization'),
        scm_branch=pulumi.get(__ret__, 'scm_branch'),
        skip_tags=pulumi.get(__ret__, 'skip_tags'),
        survey_enabled=pulumi.get(__ret__, 'survey_enabled'),
        webhook_credential=pulumi.get(__ret__, 'webhook_credential'),
        webhook_service=pulumi.get(__ret__, 'webhook_service'))
def get_workflow_job_template_output(id: pulumi.Input[Optional[Optional[_builtins.float]]] = None,
                                     name: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                     opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetWorkflowJobTemplateResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('awx:index/getWorkflowJobTemplate:getWorkflowJobTemplate', __args__, opts=opts, typ=GetWorkflowJobTemplateResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetWorkflowJobTemplateResult(
        allow_simultaneous=pulumi.get(__response__, 'allow_simultaneous'),
        ask_inventory_on_launch=pulumi.get(__response__, 'ask_inventory_on_launch'),
        ask_labels_on_launch=pulumi.get(__response__, 'ask_labels_on_launch'),
        ask_limit_on_launch=pulumi.get(__response__, 'ask_limit_on_launch'),
        ask_scm_branch_on_launch=pulumi.get(__response__, 'ask_scm_branch_on_launch'),
        ask_skip_tags_on_launch=pulumi.get(__response__, 'ask_skip_tags_on_launch'),
        ask_tags_on_launch=pulumi.get(__response__, 'ask_tags_on_launch'),
        ask_variables_on_launch=pulumi.get(__response__, 'ask_variables_on_launch'),
        description=pulumi.get(__response__, 'description'),
        extra_vars=pulumi.get(__response__, 'extra_vars'),
        id=pulumi.get(__response__, 'id'),
        inventory=pulumi.get(__response__, 'inventory'),
        job_tags=pulumi.get(__response__, 'job_tags'),
        limit=pulumi.get(__response__, 'limit'),
        name=pulumi.get(__response__, 'name'),
        organization=pulumi.get(__response__, 'organization'),
        scm_branch=pulumi.get(__response__, 'scm_branch'),
        skip_tags=pulumi.get(__response__, 'skip_tags'),
        survey_enabled=pulumi.get(__response__, 'survey_enabled'),
        webhook_credential=pulumi.get(__response__, 'webhook_credential'),
        webhook_service=pulumi.get(__response__, 'webhook_service')))
