# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetInstanceGroupResult',
    'AwaitableGetInstanceGroupResult',
    'get_instance_group',
    'get_instance_group_output',
]

@pulumi.output_type
class GetInstanceGroupResult:
    """
    A collection of values returned by getInstanceGroup.
    """
    def __init__(__self__, capacity=None, id=None, is_container_group=None, name=None):
        if capacity and not isinstance(capacity, float):
            raise TypeError("Expected argument 'capacity' to be a float")
        pulumi.set(__self__, "capacity", capacity)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if is_container_group and not isinstance(is_container_group, bool):
            raise TypeError("Expected argument 'is_container_group' to be a bool")
        pulumi.set(__self__, "is_container_group", is_container_group)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter
    def capacity(self) -> _builtins.float:
        return pulumi.get(self, "capacity")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="isContainerGroup")
    def is_container_group(self) -> _builtins.bool:
        return pulumi.get(self, "is_container_group")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")


class AwaitableGetInstanceGroupResult(GetInstanceGroupResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetInstanceGroupResult(
            capacity=self.capacity,
            id=self.id,
            is_container_group=self.is_container_group,
            name=self.name)


def get_instance_group(id: Optional[_builtins.str] = None,
                       name: Optional[_builtins.str] = None,
                       opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetInstanceGroupResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('awx:index/getInstanceGroup:getInstanceGroup', __args__, opts=opts, typ=GetInstanceGroupResult, package_ref=_utilities.get_package()).value

    return AwaitableGetInstanceGroupResult(
        capacity=pulumi.get(__ret__, 'capacity'),
        id=pulumi.get(__ret__, 'id'),
        is_container_group=pulumi.get(__ret__, 'is_container_group'),
        name=pulumi.get(__ret__, 'name'))
def get_instance_group_output(id: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                              name: pulumi.Input[Optional[_builtins.str]] = None,
                              opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetInstanceGroupResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('awx:index/getInstanceGroup:getInstanceGroup', __args__, opts=opts, typ=GetInstanceGroupResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetInstanceGroupResult(
        capacity=pulumi.get(__response__, 'capacity'),
        id=pulumi.get(__response__, 'id'),
        is_container_group=pulumi.get(__response__, 'is_container_group'),
        name=pulumi.get(__response__, 'name')))
