# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetSettingsMiscAuthenticationResult',
    'AwaitableGetSettingsMiscAuthenticationResult',
    'get_settings_misc_authentication',
    'get_settings_misc_authentication_output',
]

@pulumi.output_type
class GetSettingsMiscAuthenticationResult:
    """
    A collection of values returned by getSettingsMiscAuthentication.
    """
    def __init__(__self__, allow_metrics_for_anonymous_users=None, allow_oauth2_for_external_users=None, auth_basic_enabled=None, authentication_backends=None, disable_local_auth=None, id=None, local_password_min_digits=None, local_password_min_length=None, local_password_min_special=None, local_password_min_upper=None, login_redirect_override=None, oauth2_provider=None, session_cookie_age=None, sessions_per_user=None, social_auth_organization_map=None, social_auth_team_map=None, social_auth_user_fields=None, social_auth_username_is_full_email=None):
        if allow_metrics_for_anonymous_users and not isinstance(allow_metrics_for_anonymous_users, bool):
            raise TypeError("Expected argument 'allow_metrics_for_anonymous_users' to be a bool")
        pulumi.set(__self__, "allow_metrics_for_anonymous_users", allow_metrics_for_anonymous_users)
        if allow_oauth2_for_external_users and not isinstance(allow_oauth2_for_external_users, bool):
            raise TypeError("Expected argument 'allow_oauth2_for_external_users' to be a bool")
        pulumi.set(__self__, "allow_oauth2_for_external_users", allow_oauth2_for_external_users)
        if auth_basic_enabled and not isinstance(auth_basic_enabled, bool):
            raise TypeError("Expected argument 'auth_basic_enabled' to be a bool")
        pulumi.set(__self__, "auth_basic_enabled", auth_basic_enabled)
        if authentication_backends and not isinstance(authentication_backends, list):
            raise TypeError("Expected argument 'authentication_backends' to be a list")
        pulumi.set(__self__, "authentication_backends", authentication_backends)
        if disable_local_auth and not isinstance(disable_local_auth, bool):
            raise TypeError("Expected argument 'disable_local_auth' to be a bool")
        pulumi.set(__self__, "disable_local_auth", disable_local_auth)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if local_password_min_digits and not isinstance(local_password_min_digits, float):
            raise TypeError("Expected argument 'local_password_min_digits' to be a float")
        pulumi.set(__self__, "local_password_min_digits", local_password_min_digits)
        if local_password_min_length and not isinstance(local_password_min_length, float):
            raise TypeError("Expected argument 'local_password_min_length' to be a float")
        pulumi.set(__self__, "local_password_min_length", local_password_min_length)
        if local_password_min_special and not isinstance(local_password_min_special, float):
            raise TypeError("Expected argument 'local_password_min_special' to be a float")
        pulumi.set(__self__, "local_password_min_special", local_password_min_special)
        if local_password_min_upper and not isinstance(local_password_min_upper, float):
            raise TypeError("Expected argument 'local_password_min_upper' to be a float")
        pulumi.set(__self__, "local_password_min_upper", local_password_min_upper)
        if login_redirect_override and not isinstance(login_redirect_override, str):
            raise TypeError("Expected argument 'login_redirect_override' to be a str")
        pulumi.set(__self__, "login_redirect_override", login_redirect_override)
        if oauth2_provider and not isinstance(oauth2_provider, str):
            raise TypeError("Expected argument 'oauth2_provider' to be a str")
        pulumi.set(__self__, "oauth2_provider", oauth2_provider)
        if session_cookie_age and not isinstance(session_cookie_age, float):
            raise TypeError("Expected argument 'session_cookie_age' to be a float")
        pulumi.set(__self__, "session_cookie_age", session_cookie_age)
        if sessions_per_user and not isinstance(sessions_per_user, float):
            raise TypeError("Expected argument 'sessions_per_user' to be a float")
        pulumi.set(__self__, "sessions_per_user", sessions_per_user)
        if social_auth_organization_map and not isinstance(social_auth_organization_map, str):
            raise TypeError("Expected argument 'social_auth_organization_map' to be a str")
        pulumi.set(__self__, "social_auth_organization_map", social_auth_organization_map)
        if social_auth_team_map and not isinstance(social_auth_team_map, str):
            raise TypeError("Expected argument 'social_auth_team_map' to be a str")
        pulumi.set(__self__, "social_auth_team_map", social_auth_team_map)
        if social_auth_user_fields and not isinstance(social_auth_user_fields, list):
            raise TypeError("Expected argument 'social_auth_user_fields' to be a list")
        pulumi.set(__self__, "social_auth_user_fields", social_auth_user_fields)
        if social_auth_username_is_full_email and not isinstance(social_auth_username_is_full_email, bool):
            raise TypeError("Expected argument 'social_auth_username_is_full_email' to be a bool")
        pulumi.set(__self__, "social_auth_username_is_full_email", social_auth_username_is_full_email)

    @_builtins.property
    @pulumi.getter(name="allowMetricsForAnonymousUsers")
    def allow_metrics_for_anonymous_users(self) -> _builtins.bool:
        return pulumi.get(self, "allow_metrics_for_anonymous_users")

    @_builtins.property
    @pulumi.getter(name="allowOauth2ForExternalUsers")
    def allow_oauth2_for_external_users(self) -> _builtins.bool:
        return pulumi.get(self, "allow_oauth2_for_external_users")

    @_builtins.property
    @pulumi.getter(name="authBasicEnabled")
    def auth_basic_enabled(self) -> _builtins.bool:
        return pulumi.get(self, "auth_basic_enabled")

    @_builtins.property
    @pulumi.getter(name="authenticationBackends")
    def authentication_backends(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "authentication_backends")

    @_builtins.property
    @pulumi.getter(name="disableLocalAuth")
    def disable_local_auth(self) -> _builtins.bool:
        return pulumi.get(self, "disable_local_auth")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="localPasswordMinDigits")
    def local_password_min_digits(self) -> _builtins.float:
        return pulumi.get(self, "local_password_min_digits")

    @_builtins.property
    @pulumi.getter(name="localPasswordMinLength")
    def local_password_min_length(self) -> _builtins.float:
        return pulumi.get(self, "local_password_min_length")

    @_builtins.property
    @pulumi.getter(name="localPasswordMinSpecial")
    def local_password_min_special(self) -> _builtins.float:
        return pulumi.get(self, "local_password_min_special")

    @_builtins.property
    @pulumi.getter(name="localPasswordMinUpper")
    def local_password_min_upper(self) -> _builtins.float:
        return pulumi.get(self, "local_password_min_upper")

    @_builtins.property
    @pulumi.getter(name="loginRedirectOverride")
    def login_redirect_override(self) -> _builtins.str:
        return pulumi.get(self, "login_redirect_override")

    @_builtins.property
    @pulumi.getter(name="oauth2Provider")
    def oauth2_provider(self) -> _builtins.str:
        return pulumi.get(self, "oauth2_provider")

    @_builtins.property
    @pulumi.getter(name="sessionCookieAge")
    def session_cookie_age(self) -> _builtins.float:
        return pulumi.get(self, "session_cookie_age")

    @_builtins.property
    @pulumi.getter(name="sessionsPerUser")
    def sessions_per_user(self) -> _builtins.float:
        return pulumi.get(self, "sessions_per_user")

    @_builtins.property
    @pulumi.getter(name="socialAuthOrganizationMap")
    def social_auth_organization_map(self) -> _builtins.str:
        return pulumi.get(self, "social_auth_organization_map")

    @_builtins.property
    @pulumi.getter(name="socialAuthTeamMap")
    def social_auth_team_map(self) -> _builtins.str:
        return pulumi.get(self, "social_auth_team_map")

    @_builtins.property
    @pulumi.getter(name="socialAuthUserFields")
    def social_auth_user_fields(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "social_auth_user_fields")

    @_builtins.property
    @pulumi.getter(name="socialAuthUsernameIsFullEmail")
    def social_auth_username_is_full_email(self) -> _builtins.bool:
        return pulumi.get(self, "social_auth_username_is_full_email")


class AwaitableGetSettingsMiscAuthenticationResult(GetSettingsMiscAuthenticationResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetSettingsMiscAuthenticationResult(
            allow_metrics_for_anonymous_users=self.allow_metrics_for_anonymous_users,
            allow_oauth2_for_external_users=self.allow_oauth2_for_external_users,
            auth_basic_enabled=self.auth_basic_enabled,
            authentication_backends=self.authentication_backends,
            disable_local_auth=self.disable_local_auth,
            id=self.id,
            local_password_min_digits=self.local_password_min_digits,
            local_password_min_length=self.local_password_min_length,
            local_password_min_special=self.local_password_min_special,
            local_password_min_upper=self.local_password_min_upper,
            login_redirect_override=self.login_redirect_override,
            oauth2_provider=self.oauth2_provider,
            session_cookie_age=self.session_cookie_age,
            sessions_per_user=self.sessions_per_user,
            social_auth_organization_map=self.social_auth_organization_map,
            social_auth_team_map=self.social_auth_team_map,
            social_auth_user_fields=self.social_auth_user_fields,
            social_auth_username_is_full_email=self.social_auth_username_is_full_email)


def get_settings_misc_authentication(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetSettingsMiscAuthenticationResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('awx:index/getSettingsMiscAuthentication:getSettingsMiscAuthentication', __args__, opts=opts, typ=GetSettingsMiscAuthenticationResult, package_ref=_utilities.get_package()).value

    return AwaitableGetSettingsMiscAuthenticationResult(
        allow_metrics_for_anonymous_users=pulumi.get(__ret__, 'allow_metrics_for_anonymous_users'),
        allow_oauth2_for_external_users=pulumi.get(__ret__, 'allow_oauth2_for_external_users'),
        auth_basic_enabled=pulumi.get(__ret__, 'auth_basic_enabled'),
        authentication_backends=pulumi.get(__ret__, 'authentication_backends'),
        disable_local_auth=pulumi.get(__ret__, 'disable_local_auth'),
        id=pulumi.get(__ret__, 'id'),
        local_password_min_digits=pulumi.get(__ret__, 'local_password_min_digits'),
        local_password_min_length=pulumi.get(__ret__, 'local_password_min_length'),
        local_password_min_special=pulumi.get(__ret__, 'local_password_min_special'),
        local_password_min_upper=pulumi.get(__ret__, 'local_password_min_upper'),
        login_redirect_override=pulumi.get(__ret__, 'login_redirect_override'),
        oauth2_provider=pulumi.get(__ret__, 'oauth2_provider'),
        session_cookie_age=pulumi.get(__ret__, 'session_cookie_age'),
        sessions_per_user=pulumi.get(__ret__, 'sessions_per_user'),
        social_auth_organization_map=pulumi.get(__ret__, 'social_auth_organization_map'),
        social_auth_team_map=pulumi.get(__ret__, 'social_auth_team_map'),
        social_auth_user_fields=pulumi.get(__ret__, 'social_auth_user_fields'),
        social_auth_username_is_full_email=pulumi.get(__ret__, 'social_auth_username_is_full_email'))
def get_settings_misc_authentication_output(opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetSettingsMiscAuthenticationResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('awx:index/getSettingsMiscAuthentication:getSettingsMiscAuthentication', __args__, opts=opts, typ=GetSettingsMiscAuthenticationResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetSettingsMiscAuthenticationResult(
        allow_metrics_for_anonymous_users=pulumi.get(__response__, 'allow_metrics_for_anonymous_users'),
        allow_oauth2_for_external_users=pulumi.get(__response__, 'allow_oauth2_for_external_users'),
        auth_basic_enabled=pulumi.get(__response__, 'auth_basic_enabled'),
        authentication_backends=pulumi.get(__response__, 'authentication_backends'),
        disable_local_auth=pulumi.get(__response__, 'disable_local_auth'),
        id=pulumi.get(__response__, 'id'),
        local_password_min_digits=pulumi.get(__response__, 'local_password_min_digits'),
        local_password_min_length=pulumi.get(__response__, 'local_password_min_length'),
        local_password_min_special=pulumi.get(__response__, 'local_password_min_special'),
        local_password_min_upper=pulumi.get(__response__, 'local_password_min_upper'),
        login_redirect_override=pulumi.get(__response__, 'login_redirect_override'),
        oauth2_provider=pulumi.get(__response__, 'oauth2_provider'),
        session_cookie_age=pulumi.get(__response__, 'session_cookie_age'),
        sessions_per_user=pulumi.get(__response__, 'sessions_per_user'),
        social_auth_organization_map=pulumi.get(__response__, 'social_auth_organization_map'),
        social_auth_team_map=pulumi.get(__response__, 'social_auth_team_map'),
        social_auth_user_fields=pulumi.get(__response__, 'social_auth_user_fields'),
        social_auth_username_is_full_email=pulumi.get(__response__, 'social_auth_username_is_full_email')))
