# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetSettingsAuthGithubEnterpriseTeamResult',
    'AwaitableGetSettingsAuthGithubEnterpriseTeamResult',
    'get_settings_auth_github_enterprise_team',
    'get_settings_auth_github_enterprise_team_output',
]

@pulumi.output_type
class GetSettingsAuthGithubEnterpriseTeamResult:
    """
    A collection of values returned by getSettingsAuthGithubEnterpriseTeam.
    """
    def __init__(__self__, id=None, social_auth_github_enterprise_team_api_url=None, social_auth_github_enterprise_team_callback_url=None, social_auth_github_enterprise_team_id=None, social_auth_github_enterprise_team_key=None, social_auth_github_enterprise_team_organization_map=None, social_auth_github_enterprise_team_secret=None, social_auth_github_enterprise_team_team_map=None, social_auth_github_enterprise_team_url=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if social_auth_github_enterprise_team_api_url and not isinstance(social_auth_github_enterprise_team_api_url, str):
            raise TypeError("Expected argument 'social_auth_github_enterprise_team_api_url' to be a str")
        pulumi.set(__self__, "social_auth_github_enterprise_team_api_url", social_auth_github_enterprise_team_api_url)
        if social_auth_github_enterprise_team_callback_url and not isinstance(social_auth_github_enterprise_team_callback_url, str):
            raise TypeError("Expected argument 'social_auth_github_enterprise_team_callback_url' to be a str")
        pulumi.set(__self__, "social_auth_github_enterprise_team_callback_url", social_auth_github_enterprise_team_callback_url)
        if social_auth_github_enterprise_team_id and not isinstance(social_auth_github_enterprise_team_id, str):
            raise TypeError("Expected argument 'social_auth_github_enterprise_team_id' to be a str")
        pulumi.set(__self__, "social_auth_github_enterprise_team_id", social_auth_github_enterprise_team_id)
        if social_auth_github_enterprise_team_key and not isinstance(social_auth_github_enterprise_team_key, str):
            raise TypeError("Expected argument 'social_auth_github_enterprise_team_key' to be a str")
        pulumi.set(__self__, "social_auth_github_enterprise_team_key", social_auth_github_enterprise_team_key)
        if social_auth_github_enterprise_team_organization_map and not isinstance(social_auth_github_enterprise_team_organization_map, str):
            raise TypeError("Expected argument 'social_auth_github_enterprise_team_organization_map' to be a str")
        pulumi.set(__self__, "social_auth_github_enterprise_team_organization_map", social_auth_github_enterprise_team_organization_map)
        if social_auth_github_enterprise_team_secret and not isinstance(social_auth_github_enterprise_team_secret, str):
            raise TypeError("Expected argument 'social_auth_github_enterprise_team_secret' to be a str")
        pulumi.set(__self__, "social_auth_github_enterprise_team_secret", social_auth_github_enterprise_team_secret)
        if social_auth_github_enterprise_team_team_map and not isinstance(social_auth_github_enterprise_team_team_map, str):
            raise TypeError("Expected argument 'social_auth_github_enterprise_team_team_map' to be a str")
        pulumi.set(__self__, "social_auth_github_enterprise_team_team_map", social_auth_github_enterprise_team_team_map)
        if social_auth_github_enterprise_team_url and not isinstance(social_auth_github_enterprise_team_url, str):
            raise TypeError("Expected argument 'social_auth_github_enterprise_team_url' to be a str")
        pulumi.set(__self__, "social_auth_github_enterprise_team_url", social_auth_github_enterprise_team_url)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="socialAuthGithubEnterpriseTeamApiUrl")
    def social_auth_github_enterprise_team_api_url(self) -> _builtins.str:
        return pulumi.get(self, "social_auth_github_enterprise_team_api_url")

    @_builtins.property
    @pulumi.getter(name="socialAuthGithubEnterpriseTeamCallbackUrl")
    def social_auth_github_enterprise_team_callback_url(self) -> _builtins.str:
        return pulumi.get(self, "social_auth_github_enterprise_team_callback_url")

    @_builtins.property
    @pulumi.getter(name="socialAuthGithubEnterpriseTeamId")
    def social_auth_github_enterprise_team_id(self) -> _builtins.str:
        return pulumi.get(self, "social_auth_github_enterprise_team_id")

    @_builtins.property
    @pulumi.getter(name="socialAuthGithubEnterpriseTeamKey")
    def social_auth_github_enterprise_team_key(self) -> _builtins.str:
        return pulumi.get(self, "social_auth_github_enterprise_team_key")

    @_builtins.property
    @pulumi.getter(name="socialAuthGithubEnterpriseTeamOrganizationMap")
    def social_auth_github_enterprise_team_organization_map(self) -> _builtins.str:
        return pulumi.get(self, "social_auth_github_enterprise_team_organization_map")

    @_builtins.property
    @pulumi.getter(name="socialAuthGithubEnterpriseTeamSecret")
    def social_auth_github_enterprise_team_secret(self) -> _builtins.str:
        return pulumi.get(self, "social_auth_github_enterprise_team_secret")

    @_builtins.property
    @pulumi.getter(name="socialAuthGithubEnterpriseTeamTeamMap")
    def social_auth_github_enterprise_team_team_map(self) -> _builtins.str:
        return pulumi.get(self, "social_auth_github_enterprise_team_team_map")

    @_builtins.property
    @pulumi.getter(name="socialAuthGithubEnterpriseTeamUrl")
    def social_auth_github_enterprise_team_url(self) -> _builtins.str:
        return pulumi.get(self, "social_auth_github_enterprise_team_url")


class AwaitableGetSettingsAuthGithubEnterpriseTeamResult(GetSettingsAuthGithubEnterpriseTeamResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetSettingsAuthGithubEnterpriseTeamResult(
            id=self.id,
            social_auth_github_enterprise_team_api_url=self.social_auth_github_enterprise_team_api_url,
            social_auth_github_enterprise_team_callback_url=self.social_auth_github_enterprise_team_callback_url,
            social_auth_github_enterprise_team_id=self.social_auth_github_enterprise_team_id,
            social_auth_github_enterprise_team_key=self.social_auth_github_enterprise_team_key,
            social_auth_github_enterprise_team_organization_map=self.social_auth_github_enterprise_team_organization_map,
            social_auth_github_enterprise_team_secret=self.social_auth_github_enterprise_team_secret,
            social_auth_github_enterprise_team_team_map=self.social_auth_github_enterprise_team_team_map,
            social_auth_github_enterprise_team_url=self.social_auth_github_enterprise_team_url)


def get_settings_auth_github_enterprise_team(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetSettingsAuthGithubEnterpriseTeamResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('awx:index/getSettingsAuthGithubEnterpriseTeam:getSettingsAuthGithubEnterpriseTeam', __args__, opts=opts, typ=GetSettingsAuthGithubEnterpriseTeamResult, package_ref=_utilities.get_package()).value

    return AwaitableGetSettingsAuthGithubEnterpriseTeamResult(
        id=pulumi.get(__ret__, 'id'),
        social_auth_github_enterprise_team_api_url=pulumi.get(__ret__, 'social_auth_github_enterprise_team_api_url'),
        social_auth_github_enterprise_team_callback_url=pulumi.get(__ret__, 'social_auth_github_enterprise_team_callback_url'),
        social_auth_github_enterprise_team_id=pulumi.get(__ret__, 'social_auth_github_enterprise_team_id'),
        social_auth_github_enterprise_team_key=pulumi.get(__ret__, 'social_auth_github_enterprise_team_key'),
        social_auth_github_enterprise_team_organization_map=pulumi.get(__ret__, 'social_auth_github_enterprise_team_organization_map'),
        social_auth_github_enterprise_team_secret=pulumi.get(__ret__, 'social_auth_github_enterprise_team_secret'),
        social_auth_github_enterprise_team_team_map=pulumi.get(__ret__, 'social_auth_github_enterprise_team_team_map'),
        social_auth_github_enterprise_team_url=pulumi.get(__ret__, 'social_auth_github_enterprise_team_url'))
def get_settings_auth_github_enterprise_team_output(opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetSettingsAuthGithubEnterpriseTeamResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('awx:index/getSettingsAuthGithubEnterpriseTeam:getSettingsAuthGithubEnterpriseTeam', __args__, opts=opts, typ=GetSettingsAuthGithubEnterpriseTeamResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetSettingsAuthGithubEnterpriseTeamResult(
        id=pulumi.get(__response__, 'id'),
        social_auth_github_enterprise_team_api_url=pulumi.get(__response__, 'social_auth_github_enterprise_team_api_url'),
        social_auth_github_enterprise_team_callback_url=pulumi.get(__response__, 'social_auth_github_enterprise_team_callback_url'),
        social_auth_github_enterprise_team_id=pulumi.get(__response__, 'social_auth_github_enterprise_team_id'),
        social_auth_github_enterprise_team_key=pulumi.get(__response__, 'social_auth_github_enterprise_team_key'),
        social_auth_github_enterprise_team_organization_map=pulumi.get(__response__, 'social_auth_github_enterprise_team_organization_map'),
        social_auth_github_enterprise_team_secret=pulumi.get(__response__, 'social_auth_github_enterprise_team_secret'),
        social_auth_github_enterprise_team_team_map=pulumi.get(__response__, 'social_auth_github_enterprise_team_team_map'),
        social_auth_github_enterprise_team_url=pulumi.get(__response__, 'social_auth_github_enterprise_team_url')))
