# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetInventorySourceResult',
    'AwaitableGetInventorySourceResult',
    'get_inventory_source',
    'get_inventory_source_output',
]

@pulumi.output_type
class GetInventorySourceResult:
    """
    A collection of values returned by getInventorySource.
    """
    def __init__(__self__, credential=None, description=None, enabled_value=None, enabled_var=None, execution_environment=None, host_filter=None, id=None, inventory=None, limit=None, name=None, overwrite=None, overwrite_vars=None, scm_branch=None, source=None, source_path=None, source_project=None, source_vars=None, timeout=None, update_cache_timeout=None, update_on_launch=None, verbosity=None):
        if credential and not isinstance(credential, float):
            raise TypeError("Expected argument 'credential' to be a float")
        pulumi.set(__self__, "credential", credential)
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if enabled_value and not isinstance(enabled_value, str):
            raise TypeError("Expected argument 'enabled_value' to be a str")
        pulumi.set(__self__, "enabled_value", enabled_value)
        if enabled_var and not isinstance(enabled_var, str):
            raise TypeError("Expected argument 'enabled_var' to be a str")
        pulumi.set(__self__, "enabled_var", enabled_var)
        if execution_environment and not isinstance(execution_environment, float):
            raise TypeError("Expected argument 'execution_environment' to be a float")
        pulumi.set(__self__, "execution_environment", execution_environment)
        if host_filter and not isinstance(host_filter, str):
            raise TypeError("Expected argument 'host_filter' to be a str")
        pulumi.set(__self__, "host_filter", host_filter)
        if id and not isinstance(id, float):
            raise TypeError("Expected argument 'id' to be a float")
        pulumi.set(__self__, "id", id)
        if inventory and not isinstance(inventory, float):
            raise TypeError("Expected argument 'inventory' to be a float")
        pulumi.set(__self__, "inventory", inventory)
        if limit and not isinstance(limit, str):
            raise TypeError("Expected argument 'limit' to be a str")
        pulumi.set(__self__, "limit", limit)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if overwrite and not isinstance(overwrite, bool):
            raise TypeError("Expected argument 'overwrite' to be a bool")
        pulumi.set(__self__, "overwrite", overwrite)
        if overwrite_vars and not isinstance(overwrite_vars, bool):
            raise TypeError("Expected argument 'overwrite_vars' to be a bool")
        pulumi.set(__self__, "overwrite_vars", overwrite_vars)
        if scm_branch and not isinstance(scm_branch, str):
            raise TypeError("Expected argument 'scm_branch' to be a str")
        pulumi.set(__self__, "scm_branch", scm_branch)
        if source and not isinstance(source, str):
            raise TypeError("Expected argument 'source' to be a str")
        pulumi.set(__self__, "source", source)
        if source_path and not isinstance(source_path, str):
            raise TypeError("Expected argument 'source_path' to be a str")
        pulumi.set(__self__, "source_path", source_path)
        if source_project and not isinstance(source_project, float):
            raise TypeError("Expected argument 'source_project' to be a float")
        pulumi.set(__self__, "source_project", source_project)
        if source_vars and not isinstance(source_vars, str):
            raise TypeError("Expected argument 'source_vars' to be a str")
        pulumi.set(__self__, "source_vars", source_vars)
        if timeout and not isinstance(timeout, float):
            raise TypeError("Expected argument 'timeout' to be a float")
        pulumi.set(__self__, "timeout", timeout)
        if update_cache_timeout and not isinstance(update_cache_timeout, float):
            raise TypeError("Expected argument 'update_cache_timeout' to be a float")
        pulumi.set(__self__, "update_cache_timeout", update_cache_timeout)
        if update_on_launch and not isinstance(update_on_launch, bool):
            raise TypeError("Expected argument 'update_on_launch' to be a bool")
        pulumi.set(__self__, "update_on_launch", update_on_launch)
        if verbosity and not isinstance(verbosity, str):
            raise TypeError("Expected argument 'verbosity' to be a str")
        pulumi.set(__self__, "verbosity", verbosity)

    @_builtins.property
    @pulumi.getter
    def credential(self) -> _builtins.float:
        return pulumi.get(self, "credential")

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="enabledValue")
    def enabled_value(self) -> _builtins.str:
        return pulumi.get(self, "enabled_value")

    @_builtins.property
    @pulumi.getter(name="enabledVar")
    def enabled_var(self) -> _builtins.str:
        return pulumi.get(self, "enabled_var")

    @_builtins.property
    @pulumi.getter(name="executionEnvironment")
    def execution_environment(self) -> _builtins.float:
        return pulumi.get(self, "execution_environment")

    @_builtins.property
    @pulumi.getter(name="hostFilter")
    @_utilities.deprecated("""Deprecated""")
    def host_filter(self) -> _builtins.str:
        return pulumi.get(self, "host_filter")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.float:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def inventory(self) -> _builtins.float:
        return pulumi.get(self, "inventory")

    @_builtins.property
    @pulumi.getter
    def limit(self) -> _builtins.str:
        return pulumi.get(self, "limit")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def overwrite(self) -> _builtins.bool:
        return pulumi.get(self, "overwrite")

    @_builtins.property
    @pulumi.getter(name="overwriteVars")
    def overwrite_vars(self) -> _builtins.bool:
        return pulumi.get(self, "overwrite_vars")

    @_builtins.property
    @pulumi.getter(name="scmBranch")
    def scm_branch(self) -> _builtins.str:
        return pulumi.get(self, "scm_branch")

    @_builtins.property
    @pulumi.getter
    def source(self) -> _builtins.str:
        return pulumi.get(self, "source")

    @_builtins.property
    @pulumi.getter(name="sourcePath")
    def source_path(self) -> _builtins.str:
        return pulumi.get(self, "source_path")

    @_builtins.property
    @pulumi.getter(name="sourceProject")
    def source_project(self) -> _builtins.float:
        return pulumi.get(self, "source_project")

    @_builtins.property
    @pulumi.getter(name="sourceVars")
    def source_vars(self) -> _builtins.str:
        return pulumi.get(self, "source_vars")

    @_builtins.property
    @pulumi.getter
    def timeout(self) -> _builtins.float:
        return pulumi.get(self, "timeout")

    @_builtins.property
    @pulumi.getter(name="updateCacheTimeout")
    def update_cache_timeout(self) -> _builtins.float:
        return pulumi.get(self, "update_cache_timeout")

    @_builtins.property
    @pulumi.getter(name="updateOnLaunch")
    def update_on_launch(self) -> _builtins.bool:
        return pulumi.get(self, "update_on_launch")

    @_builtins.property
    @pulumi.getter
    def verbosity(self) -> _builtins.str:
        return pulumi.get(self, "verbosity")


class AwaitableGetInventorySourceResult(GetInventorySourceResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetInventorySourceResult(
            credential=self.credential,
            description=self.description,
            enabled_value=self.enabled_value,
            enabled_var=self.enabled_var,
            execution_environment=self.execution_environment,
            host_filter=self.host_filter,
            id=self.id,
            inventory=self.inventory,
            limit=self.limit,
            name=self.name,
            overwrite=self.overwrite,
            overwrite_vars=self.overwrite_vars,
            scm_branch=self.scm_branch,
            source=self.source,
            source_path=self.source_path,
            source_project=self.source_project,
            source_vars=self.source_vars,
            timeout=self.timeout,
            update_cache_timeout=self.update_cache_timeout,
            update_on_launch=self.update_on_launch,
            verbosity=self.verbosity)


def get_inventory_source(id: Optional[_builtins.float] = None,
                         name: Optional[_builtins.str] = None,
                         opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetInventorySourceResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('awx:index/getInventorySource:getInventorySource', __args__, opts=opts, typ=GetInventorySourceResult, package_ref=_utilities.get_package()).value

    return AwaitableGetInventorySourceResult(
        credential=pulumi.get(__ret__, 'credential'),
        description=pulumi.get(__ret__, 'description'),
        enabled_value=pulumi.get(__ret__, 'enabled_value'),
        enabled_var=pulumi.get(__ret__, 'enabled_var'),
        execution_environment=pulumi.get(__ret__, 'execution_environment'),
        host_filter=pulumi.get(__ret__, 'host_filter'),
        id=pulumi.get(__ret__, 'id'),
        inventory=pulumi.get(__ret__, 'inventory'),
        limit=pulumi.get(__ret__, 'limit'),
        name=pulumi.get(__ret__, 'name'),
        overwrite=pulumi.get(__ret__, 'overwrite'),
        overwrite_vars=pulumi.get(__ret__, 'overwrite_vars'),
        scm_branch=pulumi.get(__ret__, 'scm_branch'),
        source=pulumi.get(__ret__, 'source'),
        source_path=pulumi.get(__ret__, 'source_path'),
        source_project=pulumi.get(__ret__, 'source_project'),
        source_vars=pulumi.get(__ret__, 'source_vars'),
        timeout=pulumi.get(__ret__, 'timeout'),
        update_cache_timeout=pulumi.get(__ret__, 'update_cache_timeout'),
        update_on_launch=pulumi.get(__ret__, 'update_on_launch'),
        verbosity=pulumi.get(__ret__, 'verbosity'))
def get_inventory_source_output(id: pulumi.Input[Optional[Optional[_builtins.float]]] = None,
                                name: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetInventorySourceResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('awx:index/getInventorySource:getInventorySource', __args__, opts=opts, typ=GetInventorySourceResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetInventorySourceResult(
        credential=pulumi.get(__response__, 'credential'),
        description=pulumi.get(__response__, 'description'),
        enabled_value=pulumi.get(__response__, 'enabled_value'),
        enabled_var=pulumi.get(__response__, 'enabled_var'),
        execution_environment=pulumi.get(__response__, 'execution_environment'),
        host_filter=pulumi.get(__response__, 'host_filter'),
        id=pulumi.get(__response__, 'id'),
        inventory=pulumi.get(__response__, 'inventory'),
        limit=pulumi.get(__response__, 'limit'),
        name=pulumi.get(__response__, 'name'),
        overwrite=pulumi.get(__response__, 'overwrite'),
        overwrite_vars=pulumi.get(__response__, 'overwrite_vars'),
        scm_branch=pulumi.get(__response__, 'scm_branch'),
        source=pulumi.get(__response__, 'source'),
        source_path=pulumi.get(__response__, 'source_path'),
        source_project=pulumi.get(__response__, 'source_project'),
        source_vars=pulumi.get(__response__, 'source_vars'),
        timeout=pulumi.get(__response__, 'timeout'),
        update_cache_timeout=pulumi.get(__response__, 'update_cache_timeout'),
        update_on_launch=pulumi.get(__response__, 'update_on_launch'),
        verbosity=pulumi.get(__response__, 'verbosity')))
