# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetAdHocCommandResult',
    'AwaitableGetAdHocCommandResult',
    'get_ad_hoc_command',
    'get_ad_hoc_command_output',
]

@pulumi.output_type
class GetAdHocCommandResult:
    """
    A collection of values returned by getAdHocCommand.
    """
    def __init__(__self__, become_enabled=None, canceled_on=None, controller_node=None, credential=None, diff_mode=None, elapsed=None, execution_environment=None, execution_node=None, extra_vars=None, failed=None, finished=None, forks=None, id=None, inventory=None, job_explanation=None, job_type=None, launch_type=None, launched_by=None, limit=None, module_args=None, module_name=None, name=None, started=None, status=None, verbosity=None, work_unit_id=None):
        if become_enabled and not isinstance(become_enabled, bool):
            raise TypeError("Expected argument 'become_enabled' to be a bool")
        pulumi.set(__self__, "become_enabled", become_enabled)
        if canceled_on and not isinstance(canceled_on, str):
            raise TypeError("Expected argument 'canceled_on' to be a str")
        pulumi.set(__self__, "canceled_on", canceled_on)
        if controller_node and not isinstance(controller_node, str):
            raise TypeError("Expected argument 'controller_node' to be a str")
        pulumi.set(__self__, "controller_node", controller_node)
        if credential and not isinstance(credential, float):
            raise TypeError("Expected argument 'credential' to be a float")
        pulumi.set(__self__, "credential", credential)
        if diff_mode and not isinstance(diff_mode, bool):
            raise TypeError("Expected argument 'diff_mode' to be a bool")
        pulumi.set(__self__, "diff_mode", diff_mode)
        if elapsed and not isinstance(elapsed, float):
            raise TypeError("Expected argument 'elapsed' to be a float")
        pulumi.set(__self__, "elapsed", elapsed)
        if execution_environment and not isinstance(execution_environment, float):
            raise TypeError("Expected argument 'execution_environment' to be a float")
        pulumi.set(__self__, "execution_environment", execution_environment)
        if execution_node and not isinstance(execution_node, str):
            raise TypeError("Expected argument 'execution_node' to be a str")
        pulumi.set(__self__, "execution_node", execution_node)
        if extra_vars and not isinstance(extra_vars, str):
            raise TypeError("Expected argument 'extra_vars' to be a str")
        pulumi.set(__self__, "extra_vars", extra_vars)
        if failed and not isinstance(failed, bool):
            raise TypeError("Expected argument 'failed' to be a bool")
        pulumi.set(__self__, "failed", failed)
        if finished and not isinstance(finished, str):
            raise TypeError("Expected argument 'finished' to be a str")
        pulumi.set(__self__, "finished", finished)
        if forks and not isinstance(forks, float):
            raise TypeError("Expected argument 'forks' to be a float")
        pulumi.set(__self__, "forks", forks)
        if id and not isinstance(id, float):
            raise TypeError("Expected argument 'id' to be a float")
        pulumi.set(__self__, "id", id)
        if inventory and not isinstance(inventory, float):
            raise TypeError("Expected argument 'inventory' to be a float")
        pulumi.set(__self__, "inventory", inventory)
        if job_explanation and not isinstance(job_explanation, str):
            raise TypeError("Expected argument 'job_explanation' to be a str")
        pulumi.set(__self__, "job_explanation", job_explanation)
        if job_type and not isinstance(job_type, str):
            raise TypeError("Expected argument 'job_type' to be a str")
        pulumi.set(__self__, "job_type", job_type)
        if launch_type and not isinstance(launch_type, str):
            raise TypeError("Expected argument 'launch_type' to be a str")
        pulumi.set(__self__, "launch_type", launch_type)
        if launched_by and not isinstance(launched_by, float):
            raise TypeError("Expected argument 'launched_by' to be a float")
        pulumi.set(__self__, "launched_by", launched_by)
        if limit and not isinstance(limit, str):
            raise TypeError("Expected argument 'limit' to be a str")
        pulumi.set(__self__, "limit", limit)
        if module_args and not isinstance(module_args, str):
            raise TypeError("Expected argument 'module_args' to be a str")
        pulumi.set(__self__, "module_args", module_args)
        if module_name and not isinstance(module_name, str):
            raise TypeError("Expected argument 'module_name' to be a str")
        pulumi.set(__self__, "module_name", module_name)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if started and not isinstance(started, str):
            raise TypeError("Expected argument 'started' to be a str")
        pulumi.set(__self__, "started", started)
        if status and not isinstance(status, str):
            raise TypeError("Expected argument 'status' to be a str")
        pulumi.set(__self__, "status", status)
        if verbosity and not isinstance(verbosity, str):
            raise TypeError("Expected argument 'verbosity' to be a str")
        pulumi.set(__self__, "verbosity", verbosity)
        if work_unit_id and not isinstance(work_unit_id, str):
            raise TypeError("Expected argument 'work_unit_id' to be a str")
        pulumi.set(__self__, "work_unit_id", work_unit_id)

    @_builtins.property
    @pulumi.getter(name="becomeEnabled")
    def become_enabled(self) -> _builtins.bool:
        return pulumi.get(self, "become_enabled")

    @_builtins.property
    @pulumi.getter(name="canceledOn")
    def canceled_on(self) -> _builtins.str:
        return pulumi.get(self, "canceled_on")

    @_builtins.property
    @pulumi.getter(name="controllerNode")
    def controller_node(self) -> _builtins.str:
        return pulumi.get(self, "controller_node")

    @_builtins.property
    @pulumi.getter
    def credential(self) -> _builtins.float:
        return pulumi.get(self, "credential")

    @_builtins.property
    @pulumi.getter(name="diffMode")
    def diff_mode(self) -> _builtins.bool:
        return pulumi.get(self, "diff_mode")

    @_builtins.property
    @pulumi.getter
    def elapsed(self) -> _builtins.float:
        return pulumi.get(self, "elapsed")

    @_builtins.property
    @pulumi.getter(name="executionEnvironment")
    def execution_environment(self) -> _builtins.float:
        return pulumi.get(self, "execution_environment")

    @_builtins.property
    @pulumi.getter(name="executionNode")
    def execution_node(self) -> _builtins.str:
        return pulumi.get(self, "execution_node")

    @_builtins.property
    @pulumi.getter(name="extraVars")
    def extra_vars(self) -> _builtins.str:
        return pulumi.get(self, "extra_vars")

    @_builtins.property
    @pulumi.getter
    def failed(self) -> _builtins.bool:
        return pulumi.get(self, "failed")

    @_builtins.property
    @pulumi.getter
    def finished(self) -> _builtins.str:
        return pulumi.get(self, "finished")

    @_builtins.property
    @pulumi.getter
    def forks(self) -> _builtins.float:
        return pulumi.get(self, "forks")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.float:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def inventory(self) -> _builtins.float:
        return pulumi.get(self, "inventory")

    @_builtins.property
    @pulumi.getter(name="jobExplanation")
    def job_explanation(self) -> _builtins.str:
        return pulumi.get(self, "job_explanation")

    @_builtins.property
    @pulumi.getter(name="jobType")
    def job_type(self) -> _builtins.str:
        return pulumi.get(self, "job_type")

    @_builtins.property
    @pulumi.getter(name="launchType")
    def launch_type(self) -> _builtins.str:
        return pulumi.get(self, "launch_type")

    @_builtins.property
    @pulumi.getter(name="launchedBy")
    def launched_by(self) -> _builtins.float:
        return pulumi.get(self, "launched_by")

    @_builtins.property
    @pulumi.getter
    def limit(self) -> _builtins.str:
        return pulumi.get(self, "limit")

    @_builtins.property
    @pulumi.getter(name="moduleArgs")
    def module_args(self) -> _builtins.str:
        return pulumi.get(self, "module_args")

    @_builtins.property
    @pulumi.getter(name="moduleName")
    def module_name(self) -> _builtins.str:
        return pulumi.get(self, "module_name")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def started(self) -> _builtins.str:
        return pulumi.get(self, "started")

    @_builtins.property
    @pulumi.getter
    def status(self) -> _builtins.str:
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter
    def verbosity(self) -> _builtins.str:
        return pulumi.get(self, "verbosity")

    @_builtins.property
    @pulumi.getter(name="workUnitId")
    def work_unit_id(self) -> _builtins.str:
        return pulumi.get(self, "work_unit_id")


class AwaitableGetAdHocCommandResult(GetAdHocCommandResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetAdHocCommandResult(
            become_enabled=self.become_enabled,
            canceled_on=self.canceled_on,
            controller_node=self.controller_node,
            credential=self.credential,
            diff_mode=self.diff_mode,
            elapsed=self.elapsed,
            execution_environment=self.execution_environment,
            execution_node=self.execution_node,
            extra_vars=self.extra_vars,
            failed=self.failed,
            finished=self.finished,
            forks=self.forks,
            id=self.id,
            inventory=self.inventory,
            job_explanation=self.job_explanation,
            job_type=self.job_type,
            launch_type=self.launch_type,
            launched_by=self.launched_by,
            limit=self.limit,
            module_args=self.module_args,
            module_name=self.module_name,
            name=self.name,
            started=self.started,
            status=self.status,
            verbosity=self.verbosity,
            work_unit_id=self.work_unit_id)


def get_ad_hoc_command(id: Optional[_builtins.float] = None,
                       name: Optional[_builtins.str] = None,
                       opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetAdHocCommandResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('awx:index/getAdHocCommand:getAdHocCommand', __args__, opts=opts, typ=GetAdHocCommandResult, package_ref=_utilities.get_package()).value

    return AwaitableGetAdHocCommandResult(
        become_enabled=pulumi.get(__ret__, 'become_enabled'),
        canceled_on=pulumi.get(__ret__, 'canceled_on'),
        controller_node=pulumi.get(__ret__, 'controller_node'),
        credential=pulumi.get(__ret__, 'credential'),
        diff_mode=pulumi.get(__ret__, 'diff_mode'),
        elapsed=pulumi.get(__ret__, 'elapsed'),
        execution_environment=pulumi.get(__ret__, 'execution_environment'),
        execution_node=pulumi.get(__ret__, 'execution_node'),
        extra_vars=pulumi.get(__ret__, 'extra_vars'),
        failed=pulumi.get(__ret__, 'failed'),
        finished=pulumi.get(__ret__, 'finished'),
        forks=pulumi.get(__ret__, 'forks'),
        id=pulumi.get(__ret__, 'id'),
        inventory=pulumi.get(__ret__, 'inventory'),
        job_explanation=pulumi.get(__ret__, 'job_explanation'),
        job_type=pulumi.get(__ret__, 'job_type'),
        launch_type=pulumi.get(__ret__, 'launch_type'),
        launched_by=pulumi.get(__ret__, 'launched_by'),
        limit=pulumi.get(__ret__, 'limit'),
        module_args=pulumi.get(__ret__, 'module_args'),
        module_name=pulumi.get(__ret__, 'module_name'),
        name=pulumi.get(__ret__, 'name'),
        started=pulumi.get(__ret__, 'started'),
        status=pulumi.get(__ret__, 'status'),
        verbosity=pulumi.get(__ret__, 'verbosity'),
        work_unit_id=pulumi.get(__ret__, 'work_unit_id'))
def get_ad_hoc_command_output(id: pulumi.Input[Optional[Optional[_builtins.float]]] = None,
                              name: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                              opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetAdHocCommandResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('awx:index/getAdHocCommand:getAdHocCommand', __args__, opts=opts, typ=GetAdHocCommandResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetAdHocCommandResult(
        become_enabled=pulumi.get(__response__, 'become_enabled'),
        canceled_on=pulumi.get(__response__, 'canceled_on'),
        controller_node=pulumi.get(__response__, 'controller_node'),
        credential=pulumi.get(__response__, 'credential'),
        diff_mode=pulumi.get(__response__, 'diff_mode'),
        elapsed=pulumi.get(__response__, 'elapsed'),
        execution_environment=pulumi.get(__response__, 'execution_environment'),
        execution_node=pulumi.get(__response__, 'execution_node'),
        extra_vars=pulumi.get(__response__, 'extra_vars'),
        failed=pulumi.get(__response__, 'failed'),
        finished=pulumi.get(__response__, 'finished'),
        forks=pulumi.get(__response__, 'forks'),
        id=pulumi.get(__response__, 'id'),
        inventory=pulumi.get(__response__, 'inventory'),
        job_explanation=pulumi.get(__response__, 'job_explanation'),
        job_type=pulumi.get(__response__, 'job_type'),
        launch_type=pulumi.get(__response__, 'launch_type'),
        launched_by=pulumi.get(__response__, 'launched_by'),
        limit=pulumi.get(__response__, 'limit'),
        module_args=pulumi.get(__response__, 'module_args'),
        module_name=pulumi.get(__response__, 'module_name'),
        name=pulumi.get(__response__, 'name'),
        started=pulumi.get(__response__, 'started'),
        status=pulumi.get(__response__, 'status'),
        verbosity=pulumi.get(__response__, 'verbosity'),
        work_unit_id=pulumi.get(__response__, 'work_unit_id')))
