# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetSettingsMiscSystemResult',
    'AwaitableGetSettingsMiscSystemResult',
    'get_settings_misc_system',
    'get_settings_misc_system_output',
]

@pulumi.output_type
class GetSettingsMiscSystemResult:
    """
    A collection of values returned by getSettingsMiscSystem.
    """
    def __init__(__self__, activity_stream_enabled=None, activity_stream_enabled_for_inventory_sync=None, automation_analytics_gather_interval=None, automation_analytics_last_entries=None, automation_analytics_last_gather=None, automation_analytics_url=None, cleanup_host_metrics_last_ts=None, csrf_trusted_origins=None, custom_venv_paths=None, default_control_plane_queue_name=None, default_execution_environment=None, default_execution_queue_name=None, host_metric_summary_task_last_ts=None, id=None, insights_tracking_state=None, install_uuid=None, is_k8s=None, license=None, manage_organization_auth=None, org_admins_can_see_all_users=None, proxy_ip_allowed_lists=None, redhat_password=None, redhat_username=None, remote_host_headers=None, subscription_usage_model=None, subscriptions_password=None, subscriptions_username=None, tower_url_base=None, ui_next=None):
        if activity_stream_enabled and not isinstance(activity_stream_enabled, bool):
            raise TypeError("Expected argument 'activity_stream_enabled' to be a bool")
        pulumi.set(__self__, "activity_stream_enabled", activity_stream_enabled)
        if activity_stream_enabled_for_inventory_sync and not isinstance(activity_stream_enabled_for_inventory_sync, bool):
            raise TypeError("Expected argument 'activity_stream_enabled_for_inventory_sync' to be a bool")
        pulumi.set(__self__, "activity_stream_enabled_for_inventory_sync", activity_stream_enabled_for_inventory_sync)
        if automation_analytics_gather_interval and not isinstance(automation_analytics_gather_interval, float):
            raise TypeError("Expected argument 'automation_analytics_gather_interval' to be a float")
        pulumi.set(__self__, "automation_analytics_gather_interval", automation_analytics_gather_interval)
        if automation_analytics_last_entries and not isinstance(automation_analytics_last_entries, str):
            raise TypeError("Expected argument 'automation_analytics_last_entries' to be a str")
        pulumi.set(__self__, "automation_analytics_last_entries", automation_analytics_last_entries)
        if automation_analytics_last_gather and not isinstance(automation_analytics_last_gather, str):
            raise TypeError("Expected argument 'automation_analytics_last_gather' to be a str")
        pulumi.set(__self__, "automation_analytics_last_gather", automation_analytics_last_gather)
        if automation_analytics_url and not isinstance(automation_analytics_url, str):
            raise TypeError("Expected argument 'automation_analytics_url' to be a str")
        pulumi.set(__self__, "automation_analytics_url", automation_analytics_url)
        if cleanup_host_metrics_last_ts and not isinstance(cleanup_host_metrics_last_ts, str):
            raise TypeError("Expected argument 'cleanup_host_metrics_last_ts' to be a str")
        pulumi.set(__self__, "cleanup_host_metrics_last_ts", cleanup_host_metrics_last_ts)
        if csrf_trusted_origins and not isinstance(csrf_trusted_origins, list):
            raise TypeError("Expected argument 'csrf_trusted_origins' to be a list")
        pulumi.set(__self__, "csrf_trusted_origins", csrf_trusted_origins)
        if custom_venv_paths and not isinstance(custom_venv_paths, list):
            raise TypeError("Expected argument 'custom_venv_paths' to be a list")
        pulumi.set(__self__, "custom_venv_paths", custom_venv_paths)
        if default_control_plane_queue_name and not isinstance(default_control_plane_queue_name, str):
            raise TypeError("Expected argument 'default_control_plane_queue_name' to be a str")
        pulumi.set(__self__, "default_control_plane_queue_name", default_control_plane_queue_name)
        if default_execution_environment and not isinstance(default_execution_environment, float):
            raise TypeError("Expected argument 'default_execution_environment' to be a float")
        pulumi.set(__self__, "default_execution_environment", default_execution_environment)
        if default_execution_queue_name and not isinstance(default_execution_queue_name, str):
            raise TypeError("Expected argument 'default_execution_queue_name' to be a str")
        pulumi.set(__self__, "default_execution_queue_name", default_execution_queue_name)
        if host_metric_summary_task_last_ts and not isinstance(host_metric_summary_task_last_ts, str):
            raise TypeError("Expected argument 'host_metric_summary_task_last_ts' to be a str")
        pulumi.set(__self__, "host_metric_summary_task_last_ts", host_metric_summary_task_last_ts)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if insights_tracking_state and not isinstance(insights_tracking_state, bool):
            raise TypeError("Expected argument 'insights_tracking_state' to be a bool")
        pulumi.set(__self__, "insights_tracking_state", insights_tracking_state)
        if install_uuid and not isinstance(install_uuid, str):
            raise TypeError("Expected argument 'install_uuid' to be a str")
        pulumi.set(__self__, "install_uuid", install_uuid)
        if is_k8s and not isinstance(is_k8s, bool):
            raise TypeError("Expected argument 'is_k8s' to be a bool")
        pulumi.set(__self__, "is_k8s", is_k8s)
        if license and not isinstance(license, str):
            raise TypeError("Expected argument 'license' to be a str")
        pulumi.set(__self__, "license", license)
        if manage_organization_auth and not isinstance(manage_organization_auth, bool):
            raise TypeError("Expected argument 'manage_organization_auth' to be a bool")
        pulumi.set(__self__, "manage_organization_auth", manage_organization_auth)
        if org_admins_can_see_all_users and not isinstance(org_admins_can_see_all_users, bool):
            raise TypeError("Expected argument 'org_admins_can_see_all_users' to be a bool")
        pulumi.set(__self__, "org_admins_can_see_all_users", org_admins_can_see_all_users)
        if proxy_ip_allowed_lists and not isinstance(proxy_ip_allowed_lists, list):
            raise TypeError("Expected argument 'proxy_ip_allowed_lists' to be a list")
        pulumi.set(__self__, "proxy_ip_allowed_lists", proxy_ip_allowed_lists)
        if redhat_password and not isinstance(redhat_password, str):
            raise TypeError("Expected argument 'redhat_password' to be a str")
        pulumi.set(__self__, "redhat_password", redhat_password)
        if redhat_username and not isinstance(redhat_username, str):
            raise TypeError("Expected argument 'redhat_username' to be a str")
        pulumi.set(__self__, "redhat_username", redhat_username)
        if remote_host_headers and not isinstance(remote_host_headers, list):
            raise TypeError("Expected argument 'remote_host_headers' to be a list")
        pulumi.set(__self__, "remote_host_headers", remote_host_headers)
        if subscription_usage_model and not isinstance(subscription_usage_model, str):
            raise TypeError("Expected argument 'subscription_usage_model' to be a str")
        pulumi.set(__self__, "subscription_usage_model", subscription_usage_model)
        if subscriptions_password and not isinstance(subscriptions_password, str):
            raise TypeError("Expected argument 'subscriptions_password' to be a str")
        pulumi.set(__self__, "subscriptions_password", subscriptions_password)
        if subscriptions_username and not isinstance(subscriptions_username, str):
            raise TypeError("Expected argument 'subscriptions_username' to be a str")
        pulumi.set(__self__, "subscriptions_username", subscriptions_username)
        if tower_url_base and not isinstance(tower_url_base, str):
            raise TypeError("Expected argument 'tower_url_base' to be a str")
        pulumi.set(__self__, "tower_url_base", tower_url_base)
        if ui_next and not isinstance(ui_next, bool):
            raise TypeError("Expected argument 'ui_next' to be a bool")
        pulumi.set(__self__, "ui_next", ui_next)

    @_builtins.property
    @pulumi.getter(name="activityStreamEnabled")
    def activity_stream_enabled(self) -> _builtins.bool:
        return pulumi.get(self, "activity_stream_enabled")

    @_builtins.property
    @pulumi.getter(name="activityStreamEnabledForInventorySync")
    def activity_stream_enabled_for_inventory_sync(self) -> _builtins.bool:
        return pulumi.get(self, "activity_stream_enabled_for_inventory_sync")

    @_builtins.property
    @pulumi.getter(name="automationAnalyticsGatherInterval")
    def automation_analytics_gather_interval(self) -> _builtins.float:
        return pulumi.get(self, "automation_analytics_gather_interval")

    @_builtins.property
    @pulumi.getter(name="automationAnalyticsLastEntries")
    def automation_analytics_last_entries(self) -> _builtins.str:
        return pulumi.get(self, "automation_analytics_last_entries")

    @_builtins.property
    @pulumi.getter(name="automationAnalyticsLastGather")
    def automation_analytics_last_gather(self) -> _builtins.str:
        return pulumi.get(self, "automation_analytics_last_gather")

    @_builtins.property
    @pulumi.getter(name="automationAnalyticsUrl")
    def automation_analytics_url(self) -> _builtins.str:
        return pulumi.get(self, "automation_analytics_url")

    @_builtins.property
    @pulumi.getter(name="cleanupHostMetricsLastTs")
    def cleanup_host_metrics_last_ts(self) -> _builtins.str:
        return pulumi.get(self, "cleanup_host_metrics_last_ts")

    @_builtins.property
    @pulumi.getter(name="csrfTrustedOrigins")
    def csrf_trusted_origins(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "csrf_trusted_origins")

    @_builtins.property
    @pulumi.getter(name="customVenvPaths")
    def custom_venv_paths(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "custom_venv_paths")

    @_builtins.property
    @pulumi.getter(name="defaultControlPlaneQueueName")
    def default_control_plane_queue_name(self) -> _builtins.str:
        return pulumi.get(self, "default_control_plane_queue_name")

    @_builtins.property
    @pulumi.getter(name="defaultExecutionEnvironment")
    def default_execution_environment(self) -> _builtins.float:
        return pulumi.get(self, "default_execution_environment")

    @_builtins.property
    @pulumi.getter(name="defaultExecutionQueueName")
    def default_execution_queue_name(self) -> _builtins.str:
        return pulumi.get(self, "default_execution_queue_name")

    @_builtins.property
    @pulumi.getter(name="hostMetricSummaryTaskLastTs")
    def host_metric_summary_task_last_ts(self) -> _builtins.str:
        return pulumi.get(self, "host_metric_summary_task_last_ts")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="insightsTrackingState")
    def insights_tracking_state(self) -> _builtins.bool:
        return pulumi.get(self, "insights_tracking_state")

    @_builtins.property
    @pulumi.getter(name="installUuid")
    def install_uuid(self) -> _builtins.str:
        return pulumi.get(self, "install_uuid")

    @_builtins.property
    @pulumi.getter(name="isK8s")
    def is_k8s(self) -> _builtins.bool:
        return pulumi.get(self, "is_k8s")

    @_builtins.property
    @pulumi.getter
    def license(self) -> _builtins.str:
        return pulumi.get(self, "license")

    @_builtins.property
    @pulumi.getter(name="manageOrganizationAuth")
    def manage_organization_auth(self) -> _builtins.bool:
        return pulumi.get(self, "manage_organization_auth")

    @_builtins.property
    @pulumi.getter(name="orgAdminsCanSeeAllUsers")
    def org_admins_can_see_all_users(self) -> _builtins.bool:
        return pulumi.get(self, "org_admins_can_see_all_users")

    @_builtins.property
    @pulumi.getter(name="proxyIpAllowedLists")
    def proxy_ip_allowed_lists(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "proxy_ip_allowed_lists")

    @_builtins.property
    @pulumi.getter(name="redhatPassword")
    def redhat_password(self) -> _builtins.str:
        return pulumi.get(self, "redhat_password")

    @_builtins.property
    @pulumi.getter(name="redhatUsername")
    def redhat_username(self) -> _builtins.str:
        return pulumi.get(self, "redhat_username")

    @_builtins.property
    @pulumi.getter(name="remoteHostHeaders")
    def remote_host_headers(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "remote_host_headers")

    @_builtins.property
    @pulumi.getter(name="subscriptionUsageModel")
    def subscription_usage_model(self) -> _builtins.str:
        return pulumi.get(self, "subscription_usage_model")

    @_builtins.property
    @pulumi.getter(name="subscriptionsPassword")
    def subscriptions_password(self) -> _builtins.str:
        return pulumi.get(self, "subscriptions_password")

    @_builtins.property
    @pulumi.getter(name="subscriptionsUsername")
    def subscriptions_username(self) -> _builtins.str:
        return pulumi.get(self, "subscriptions_username")

    @_builtins.property
    @pulumi.getter(name="towerUrlBase")
    def tower_url_base(self) -> _builtins.str:
        return pulumi.get(self, "tower_url_base")

    @_builtins.property
    @pulumi.getter(name="uiNext")
    def ui_next(self) -> _builtins.bool:
        return pulumi.get(self, "ui_next")


class AwaitableGetSettingsMiscSystemResult(GetSettingsMiscSystemResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetSettingsMiscSystemResult(
            activity_stream_enabled=self.activity_stream_enabled,
            activity_stream_enabled_for_inventory_sync=self.activity_stream_enabled_for_inventory_sync,
            automation_analytics_gather_interval=self.automation_analytics_gather_interval,
            automation_analytics_last_entries=self.automation_analytics_last_entries,
            automation_analytics_last_gather=self.automation_analytics_last_gather,
            automation_analytics_url=self.automation_analytics_url,
            cleanup_host_metrics_last_ts=self.cleanup_host_metrics_last_ts,
            csrf_trusted_origins=self.csrf_trusted_origins,
            custom_venv_paths=self.custom_venv_paths,
            default_control_plane_queue_name=self.default_control_plane_queue_name,
            default_execution_environment=self.default_execution_environment,
            default_execution_queue_name=self.default_execution_queue_name,
            host_metric_summary_task_last_ts=self.host_metric_summary_task_last_ts,
            id=self.id,
            insights_tracking_state=self.insights_tracking_state,
            install_uuid=self.install_uuid,
            is_k8s=self.is_k8s,
            license=self.license,
            manage_organization_auth=self.manage_organization_auth,
            org_admins_can_see_all_users=self.org_admins_can_see_all_users,
            proxy_ip_allowed_lists=self.proxy_ip_allowed_lists,
            redhat_password=self.redhat_password,
            redhat_username=self.redhat_username,
            remote_host_headers=self.remote_host_headers,
            subscription_usage_model=self.subscription_usage_model,
            subscriptions_password=self.subscriptions_password,
            subscriptions_username=self.subscriptions_username,
            tower_url_base=self.tower_url_base,
            ui_next=self.ui_next)


def get_settings_misc_system(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetSettingsMiscSystemResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('awx:index/getSettingsMiscSystem:getSettingsMiscSystem', __args__, opts=opts, typ=GetSettingsMiscSystemResult, package_ref=_utilities.get_package()).value

    return AwaitableGetSettingsMiscSystemResult(
        activity_stream_enabled=pulumi.get(__ret__, 'activity_stream_enabled'),
        activity_stream_enabled_for_inventory_sync=pulumi.get(__ret__, 'activity_stream_enabled_for_inventory_sync'),
        automation_analytics_gather_interval=pulumi.get(__ret__, 'automation_analytics_gather_interval'),
        automation_analytics_last_entries=pulumi.get(__ret__, 'automation_analytics_last_entries'),
        automation_analytics_last_gather=pulumi.get(__ret__, 'automation_analytics_last_gather'),
        automation_analytics_url=pulumi.get(__ret__, 'automation_analytics_url'),
        cleanup_host_metrics_last_ts=pulumi.get(__ret__, 'cleanup_host_metrics_last_ts'),
        csrf_trusted_origins=pulumi.get(__ret__, 'csrf_trusted_origins'),
        custom_venv_paths=pulumi.get(__ret__, 'custom_venv_paths'),
        default_control_plane_queue_name=pulumi.get(__ret__, 'default_control_plane_queue_name'),
        default_execution_environment=pulumi.get(__ret__, 'default_execution_environment'),
        default_execution_queue_name=pulumi.get(__ret__, 'default_execution_queue_name'),
        host_metric_summary_task_last_ts=pulumi.get(__ret__, 'host_metric_summary_task_last_ts'),
        id=pulumi.get(__ret__, 'id'),
        insights_tracking_state=pulumi.get(__ret__, 'insights_tracking_state'),
        install_uuid=pulumi.get(__ret__, 'install_uuid'),
        is_k8s=pulumi.get(__ret__, 'is_k8s'),
        license=pulumi.get(__ret__, 'license'),
        manage_organization_auth=pulumi.get(__ret__, 'manage_organization_auth'),
        org_admins_can_see_all_users=pulumi.get(__ret__, 'org_admins_can_see_all_users'),
        proxy_ip_allowed_lists=pulumi.get(__ret__, 'proxy_ip_allowed_lists'),
        redhat_password=pulumi.get(__ret__, 'redhat_password'),
        redhat_username=pulumi.get(__ret__, 'redhat_username'),
        remote_host_headers=pulumi.get(__ret__, 'remote_host_headers'),
        subscription_usage_model=pulumi.get(__ret__, 'subscription_usage_model'),
        subscriptions_password=pulumi.get(__ret__, 'subscriptions_password'),
        subscriptions_username=pulumi.get(__ret__, 'subscriptions_username'),
        tower_url_base=pulumi.get(__ret__, 'tower_url_base'),
        ui_next=pulumi.get(__ret__, 'ui_next'))
def get_settings_misc_system_output(opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetSettingsMiscSystemResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('awx:index/getSettingsMiscSystem:getSettingsMiscSystem', __args__, opts=opts, typ=GetSettingsMiscSystemResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetSettingsMiscSystemResult(
        activity_stream_enabled=pulumi.get(__response__, 'activity_stream_enabled'),
        activity_stream_enabled_for_inventory_sync=pulumi.get(__response__, 'activity_stream_enabled_for_inventory_sync'),
        automation_analytics_gather_interval=pulumi.get(__response__, 'automation_analytics_gather_interval'),
        automation_analytics_last_entries=pulumi.get(__response__, 'automation_analytics_last_entries'),
        automation_analytics_last_gather=pulumi.get(__response__, 'automation_analytics_last_gather'),
        automation_analytics_url=pulumi.get(__response__, 'automation_analytics_url'),
        cleanup_host_metrics_last_ts=pulumi.get(__response__, 'cleanup_host_metrics_last_ts'),
        csrf_trusted_origins=pulumi.get(__response__, 'csrf_trusted_origins'),
        custom_venv_paths=pulumi.get(__response__, 'custom_venv_paths'),
        default_control_plane_queue_name=pulumi.get(__response__, 'default_control_plane_queue_name'),
        default_execution_environment=pulumi.get(__response__, 'default_execution_environment'),
        default_execution_queue_name=pulumi.get(__response__, 'default_execution_queue_name'),
        host_metric_summary_task_last_ts=pulumi.get(__response__, 'host_metric_summary_task_last_ts'),
        id=pulumi.get(__response__, 'id'),
        insights_tracking_state=pulumi.get(__response__, 'insights_tracking_state'),
        install_uuid=pulumi.get(__response__, 'install_uuid'),
        is_k8s=pulumi.get(__response__, 'is_k8s'),
        license=pulumi.get(__response__, 'license'),
        manage_organization_auth=pulumi.get(__response__, 'manage_organization_auth'),
        org_admins_can_see_all_users=pulumi.get(__response__, 'org_admins_can_see_all_users'),
        proxy_ip_allowed_lists=pulumi.get(__response__, 'proxy_ip_allowed_lists'),
        redhat_password=pulumi.get(__response__, 'redhat_password'),
        redhat_username=pulumi.get(__response__, 'redhat_username'),
        remote_host_headers=pulumi.get(__response__, 'remote_host_headers'),
        subscription_usage_model=pulumi.get(__response__, 'subscription_usage_model'),
        subscriptions_password=pulumi.get(__response__, 'subscriptions_password'),
        subscriptions_username=pulumi.get(__response__, 'subscriptions_username'),
        tower_url_base=pulumi.get(__response__, 'tower_url_base'),
        ui_next=pulumi.get(__response__, 'ui_next')))
