# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['InventoryArgs', 'Inventory']

@pulumi.input_type
class InventoryArgs:
    def __init__(__self__, *,
                 organization_id: pulumi.Input[_builtins.str],
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 host_filter: pulumi.Input[Optional[_builtins.str]] = None,
                 inventory_id: pulumi.Input[Optional[_builtins.str]] = None,
                 kind: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 variables: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a Inventory resource.

        :param pulumi.Input[_builtins.str] organization_id: The organization id of the inventory
        :param pulumi.Input[_builtins.str] description: The description of the inventory
        :param pulumi.Input[_builtins.str] host_filter: The host filter of the inventory
        :param pulumi.Input[_builtins.str] kind: The kind of the inventory
        :param pulumi.Input[_builtins.str] name: The name of the inventory
        :param pulumi.Input[_builtins.str] variables: The variables of the inventory
        """
        pulumi.set(__self__, "organization_id", organization_id)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if host_filter is not None:
            pulumi.set(__self__, "host_filter", host_filter)
        if inventory_id is not None:
            pulumi.set(__self__, "inventory_id", inventory_id)
        if kind is not None:
            pulumi.set(__self__, "kind", kind)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if variables is not None:
            pulumi.set(__self__, "variables", variables)

    @_builtins.property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Input[_builtins.str]:
        """
        The organization id of the inventory
        """
        return pulumi.get(self, "organization_id")

    @organization_id.setter
    def organization_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "organization_id", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The description of the inventory
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="hostFilter")
    def host_filter(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The host filter of the inventory
        """
        return pulumi.get(self, "host_filter")

    @host_filter.setter
    def host_filter(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "host_filter", value)

    @_builtins.property
    @pulumi.getter(name="inventoryId")
    def inventory_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "inventory_id")

    @inventory_id.setter
    def inventory_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "inventory_id", value)

    @_builtins.property
    @pulumi.getter
    def kind(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The kind of the inventory
        """
        return pulumi.get(self, "kind")

    @kind.setter
    def kind(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "kind", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the inventory
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def variables(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The variables of the inventory
        """
        return pulumi.get(self, "variables")

    @variables.setter
    def variables(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "variables", value)


@pulumi.input_type
class _InventoryState:
    def __init__(__self__, *,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 host_filter: pulumi.Input[Optional[_builtins.str]] = None,
                 inventory_id: pulumi.Input[Optional[_builtins.str]] = None,
                 kind: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 organization_id: pulumi.Input[Optional[_builtins.str]] = None,
                 variables: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Inventory resources.

        :param pulumi.Input[_builtins.str] description: The description of the inventory
        :param pulumi.Input[_builtins.str] host_filter: The host filter of the inventory
        :param pulumi.Input[_builtins.str] kind: The kind of the inventory
        :param pulumi.Input[_builtins.str] name: The name of the inventory
        :param pulumi.Input[_builtins.str] organization_id: The organization id of the inventory
        :param pulumi.Input[_builtins.str] variables: The variables of the inventory
        """
        if description is not None:
            pulumi.set(__self__, "description", description)
        if host_filter is not None:
            pulumi.set(__self__, "host_filter", host_filter)
        if inventory_id is not None:
            pulumi.set(__self__, "inventory_id", inventory_id)
        if kind is not None:
            pulumi.set(__self__, "kind", kind)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if organization_id is not None:
            pulumi.set(__self__, "organization_id", organization_id)
        if variables is not None:
            pulumi.set(__self__, "variables", variables)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The description of the inventory
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="hostFilter")
    def host_filter(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The host filter of the inventory
        """
        return pulumi.get(self, "host_filter")

    @host_filter.setter
    def host_filter(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "host_filter", value)

    @_builtins.property
    @pulumi.getter(name="inventoryId")
    def inventory_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "inventory_id")

    @inventory_id.setter
    def inventory_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "inventory_id", value)

    @_builtins.property
    @pulumi.getter
    def kind(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The kind of the inventory
        """
        return pulumi.get(self, "kind")

    @kind.setter
    def kind(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "kind", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the inventory
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The organization id of the inventory
        """
        return pulumi.get(self, "organization_id")

    @organization_id.setter
    def organization_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "organization_id", value)

    @_builtins.property
    @pulumi.getter
    def variables(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The variables of the inventory
        """
        return pulumi.get(self, "variables")

    @variables.setter
    def variables(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "variables", value)


@pulumi.type_token("awx:index/inventory:Inventory")
class Inventory(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 host_filter: pulumi.Input[Optional[_builtins.str]] = None,
                 inventory_id: pulumi.Input[Optional[_builtins.str]] = None,
                 kind: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 organization_id: pulumi.Input[Optional[_builtins.str]] = None,
                 variables: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Create a Inventory resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] description: The description of the inventory
        :param pulumi.Input[_builtins.str] host_filter: The host filter of the inventory
        :param pulumi.Input[_builtins.str] kind: The kind of the inventory
        :param pulumi.Input[_builtins.str] name: The name of the inventory
        :param pulumi.Input[_builtins.str] organization_id: The organization id of the inventory
        :param pulumi.Input[_builtins.str] variables: The variables of the inventory
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: InventoryArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Inventory resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param InventoryArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(InventoryArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 host_filter: pulumi.Input[Optional[_builtins.str]] = None,
                 inventory_id: pulumi.Input[Optional[_builtins.str]] = None,
                 kind: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 organization_id: pulumi.Input[Optional[_builtins.str]] = None,
                 variables: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = InventoryArgs.__new__(InventoryArgs)

            __props__.__dict__["description"] = description
            __props__.__dict__["host_filter"] = host_filter
            __props__.__dict__["inventory_id"] = inventory_id
            __props__.__dict__["kind"] = kind
            __props__.__dict__["name"] = name
            if organization_id is None and not opts.urn:
                raise TypeError("Missing required property 'organization_id'")
            __props__.__dict__["organization_id"] = organization_id
            __props__.__dict__["variables"] = variables
        super(Inventory, __self__).__init__(
            'awx:index/inventory:Inventory',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            description: pulumi.Input[Optional[_builtins.str]] = None,
            host_filter: pulumi.Input[Optional[_builtins.str]] = None,
            inventory_id: pulumi.Input[Optional[_builtins.str]] = None,
            kind: pulumi.Input[Optional[_builtins.str]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            organization_id: pulumi.Input[Optional[_builtins.str]] = None,
            variables: pulumi.Input[Optional[_builtins.str]] = None) -> 'Inventory':
        """
        Get an existing Inventory resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] description: The description of the inventory
        :param pulumi.Input[_builtins.str] host_filter: The host filter of the inventory
        :param pulumi.Input[_builtins.str] kind: The kind of the inventory
        :param pulumi.Input[_builtins.str] name: The name of the inventory
        :param pulumi.Input[_builtins.str] organization_id: The organization id of the inventory
        :param pulumi.Input[_builtins.str] variables: The variables of the inventory
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _InventoryState.__new__(_InventoryState)

        __props__.__dict__["description"] = description
        __props__.__dict__["host_filter"] = host_filter
        __props__.__dict__["inventory_id"] = inventory_id
        __props__.__dict__["kind"] = kind
        __props__.__dict__["name"] = name
        __props__.__dict__["organization_id"] = organization_id
        __props__.__dict__["variables"] = variables
        return Inventory(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The description of the inventory
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="hostFilter")
    def host_filter(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The host filter of the inventory
        """
        return pulumi.get(self, "host_filter")

    @_builtins.property
    @pulumi.getter(name="inventoryId")
    def inventory_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "inventory_id")

    @_builtins.property
    @pulumi.getter
    def kind(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The kind of the inventory
        """
        return pulumi.get(self, "kind")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the inventory
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Output[_builtins.str]:
        """
        The organization id of the inventory
        """
        return pulumi.get(self, "organization_id")

    @_builtins.property
    @pulumi.getter
    def variables(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The variables of the inventory
        """
        return pulumi.get(self, "variables")

