# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['OrganizationAssociateGalaxyCredentialArgs', 'OrganizationAssociateGalaxyCredential']

@pulumi.input_type
class OrganizationAssociateGalaxyCredentialArgs:
    def __init__(__self__, *,
                 galaxy_credential_id: pulumi.Input[_builtins.float],
                 organization_id: pulumi.Input[_builtins.float]):
        """
        The set of arguments for constructing a OrganizationAssociateGalaxyCredential resource.

        :param pulumi.Input[_builtins.float] galaxy_credential_id: Database ID of the galaxycredential to assign.
        :param pulumi.Input[_builtins.float] organization_id: Database ID for this Organization.
        """
        pulumi.set(__self__, "galaxy_credential_id", galaxy_credential_id)
        pulumi.set(__self__, "organization_id", organization_id)

    @_builtins.property
    @pulumi.getter(name="galaxyCredentialId")
    def galaxy_credential_id(self) -> pulumi.Input[_builtins.float]:
        """
        Database ID of the galaxycredential to assign.
        """
        return pulumi.get(self, "galaxy_credential_id")

    @galaxy_credential_id.setter
    def galaxy_credential_id(self, value: pulumi.Input[_builtins.float]):
        pulumi.set(self, "galaxy_credential_id", value)

    @_builtins.property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Input[_builtins.float]:
        """
        Database ID for this Organization.
        """
        return pulumi.get(self, "organization_id")

    @organization_id.setter
    def organization_id(self, value: pulumi.Input[_builtins.float]):
        pulumi.set(self, "organization_id", value)


@pulumi.input_type
class _OrganizationAssociateGalaxyCredentialState:
    def __init__(__self__, *,
                 galaxy_credential_id: pulumi.Input[Optional[_builtins.float]] = None,
                 organization_id: pulumi.Input[Optional[_builtins.float]] = None):
        """
        Input properties used for looking up and filtering OrganizationAssociateGalaxyCredential resources.

        :param pulumi.Input[_builtins.float] galaxy_credential_id: Database ID of the galaxycredential to assign.
        :param pulumi.Input[_builtins.float] organization_id: Database ID for this Organization.
        """
        if galaxy_credential_id is not None:
            pulumi.set(__self__, "galaxy_credential_id", galaxy_credential_id)
        if organization_id is not None:
            pulumi.set(__self__, "organization_id", organization_id)

    @_builtins.property
    @pulumi.getter(name="galaxyCredentialId")
    def galaxy_credential_id(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Database ID of the galaxycredential to assign.
        """
        return pulumi.get(self, "galaxy_credential_id")

    @galaxy_credential_id.setter
    def galaxy_credential_id(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "galaxy_credential_id", value)

    @_builtins.property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Database ID for this Organization.
        """
        return pulumi.get(self, "organization_id")

    @organization_id.setter
    def organization_id(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "organization_id", value)


@pulumi.type_token("awx:index/organizationAssociateGalaxyCredential:OrganizationAssociateGalaxyCredential")
class OrganizationAssociateGalaxyCredential(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 galaxy_credential_id: pulumi.Input[Optional[_builtins.float]] = None,
                 organization_id: pulumi.Input[Optional[_builtins.float]] = None,
                 __props__=None):
        """
        Create a OrganizationAssociateGalaxyCredential resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.float] galaxy_credential_id: Database ID of the galaxycredential to assign.
        :param pulumi.Input[_builtins.float] organization_id: Database ID for this Organization.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: OrganizationAssociateGalaxyCredentialArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a OrganizationAssociateGalaxyCredential resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param OrganizationAssociateGalaxyCredentialArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(OrganizationAssociateGalaxyCredentialArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 galaxy_credential_id: pulumi.Input[Optional[_builtins.float]] = None,
                 organization_id: pulumi.Input[Optional[_builtins.float]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = OrganizationAssociateGalaxyCredentialArgs.__new__(OrganizationAssociateGalaxyCredentialArgs)

            if galaxy_credential_id is None and not opts.urn:
                raise TypeError("Missing required property 'galaxy_credential_id'")
            __props__.__dict__["galaxy_credential_id"] = galaxy_credential_id
            if organization_id is None and not opts.urn:
                raise TypeError("Missing required property 'organization_id'")
            __props__.__dict__["organization_id"] = organization_id
        super(OrganizationAssociateGalaxyCredential, __self__).__init__(
            'awx:index/organizationAssociateGalaxyCredential:OrganizationAssociateGalaxyCredential',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            galaxy_credential_id: pulumi.Input[Optional[_builtins.float]] = None,
            organization_id: pulumi.Input[Optional[_builtins.float]] = None) -> 'OrganizationAssociateGalaxyCredential':
        """
        Get an existing OrganizationAssociateGalaxyCredential resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.float] galaxy_credential_id: Database ID of the galaxycredential to assign.
        :param pulumi.Input[_builtins.float] organization_id: Database ID for this Organization.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _OrganizationAssociateGalaxyCredentialState.__new__(_OrganizationAssociateGalaxyCredentialState)

        __props__.__dict__["galaxy_credential_id"] = galaxy_credential_id
        __props__.__dict__["organization_id"] = organization_id
        return OrganizationAssociateGalaxyCredential(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="galaxyCredentialId")
    def galaxy_credential_id(self) -> pulumi.Output[_builtins.float]:
        """
        Database ID of the galaxycredential to assign.
        """
        return pulumi.get(self, "galaxy_credential_id")

    @_builtins.property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Output[_builtins.float]:
        """
        Database ID for this Organization.
        """
        return pulumi.get(self, "organization_id")

