# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['SettingsMiscAuthenticationArgs', 'SettingsMiscAuthentication']

@pulumi.input_type
class SettingsMiscAuthenticationArgs:
    def __init__(__self__, *,
                 allow_metrics_for_anonymous_users: pulumi.Input[Optional[_builtins.bool]] = None,
                 allow_oauth2_for_external_users: pulumi.Input[Optional[_builtins.bool]] = None,
                 auth_basic_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 disable_local_auth: pulumi.Input[Optional[_builtins.bool]] = None,
                 local_password_min_digits: pulumi.Input[Optional[_builtins.float]] = None,
                 local_password_min_length: pulumi.Input[Optional[_builtins.float]] = None,
                 local_password_min_special: pulumi.Input[Optional[_builtins.float]] = None,
                 local_password_min_upper: pulumi.Input[Optional[_builtins.float]] = None,
                 login_redirect_override: pulumi.Input[Optional[_builtins.str]] = None,
                 oauth2_provider: pulumi.Input[Optional[_builtins.str]] = None,
                 session_cookie_age: pulumi.Input[Optional[_builtins.float]] = None,
                 sessions_per_user: pulumi.Input[Optional[_builtins.float]] = None,
                 social_auth_organization_map: pulumi.Input[Optional[_builtins.str]] = None,
                 social_auth_team_map: pulumi.Input[Optional[_builtins.str]] = None,
                 social_auth_user_fields: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 social_auth_username_is_full_email: pulumi.Input[Optional[_builtins.bool]] = None):
        """
        The set of arguments for constructing a SettingsMiscAuthentication resource.

        :param pulumi.Input[_builtins.bool] allow_metrics_for_anonymous_users: If true, anonymous users are allowed to poll metrics.
        :param pulumi.Input[_builtins.bool] allow_oauth2_for_external_users: For security reasons, users from external auth providers (LDAP, SAML, SSO, Radius, and others) are not allowed to create OAuth2 tokens. To change this behavior, enable this setting. Existing tokens will not be deleted when this setting is toggled off.
        :param pulumi.Input[_builtins.bool] auth_basic_enabled: Enable HTTP Basic Auth for the API Browser.
        :param pulumi.Input[_builtins.bool] disable_local_auth: Controls whether users are prevented from using the built-in authentication system. You probably want to do this if you are using an LDAP or SAML integration.
        :param pulumi.Input[_builtins.float] local_password_min_digits: Minimum number of digit characters required in a local password. 0 means no minimum
        :param pulumi.Input[_builtins.float] local_password_min_length: Minimum number of characters required in a local password. 0 means no minimum
        :param pulumi.Input[_builtins.float] local_password_min_special: Minimum number of special characters required in a local password. 0 means no minimum
        :param pulumi.Input[_builtins.float] local_password_min_upper: Minimum number of uppercase characters required in a local password. 0 means no minimum
        :param pulumi.Input[_builtins.str] login_redirect_override: URL to which unauthorized users will be redirected to log in.  If blank, users will be sent to the login page.
        :param pulumi.Input[_builtins.str] oauth2_provider: Dictionary for customizing OAuth 2 timeouts, available items are `ACCESS_TOKEN_EXPIRE_SECONDS`, the duration of access tokens in the number of seconds, `AUTHORIZATION_CODE_EXPIRE_SECONDS`, the duration of authorization codes in the number of seconds, and `REFRESH_TOKEN_EXPIRE_SECONDS`, the duration of refresh tokens, after expired access tokens, in the number of seconds.
        :param pulumi.Input[_builtins.float] session_cookie_age: Number of seconds that a user is inactive before they will need to login again.
        :param pulumi.Input[_builtins.float] sessions_per_user: Maximum number of simultaneous logged in sessions a user may have. To disable enter -1.
        :param pulumi.Input[_builtins.str] social_auth_organization_map: Mapping to organization admins/users from social auth accounts. This setting
               controls which users are placed into which organizations based on their
               username and email address. Configuration details are available in the
               documentation.
        :param pulumi.Input[_builtins.str] social_auth_team_map: Mapping of team members (users) from social auth accounts. Configuration
               details are available in the documentation.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] social_auth_user_fields: When set to an empty list `[]`, this setting prevents new user accounts from being created. Only users who have previously logged in using social auth or have a user account with a matching email address will be able to login.
        :param pulumi.Input[_builtins.bool] social_auth_username_is_full_email: Enabling this setting will tell social auth to use the full Email as username instead of the full name
        """
        if allow_metrics_for_anonymous_users is not None:
            pulumi.set(__self__, "allow_metrics_for_anonymous_users", allow_metrics_for_anonymous_users)
        if allow_oauth2_for_external_users is not None:
            pulumi.set(__self__, "allow_oauth2_for_external_users", allow_oauth2_for_external_users)
        if auth_basic_enabled is not None:
            pulumi.set(__self__, "auth_basic_enabled", auth_basic_enabled)
        if disable_local_auth is not None:
            pulumi.set(__self__, "disable_local_auth", disable_local_auth)
        if local_password_min_digits is not None:
            pulumi.set(__self__, "local_password_min_digits", local_password_min_digits)
        if local_password_min_length is not None:
            pulumi.set(__self__, "local_password_min_length", local_password_min_length)
        if local_password_min_special is not None:
            pulumi.set(__self__, "local_password_min_special", local_password_min_special)
        if local_password_min_upper is not None:
            pulumi.set(__self__, "local_password_min_upper", local_password_min_upper)
        if login_redirect_override is not None:
            pulumi.set(__self__, "login_redirect_override", login_redirect_override)
        if oauth2_provider is not None:
            pulumi.set(__self__, "oauth2_provider", oauth2_provider)
        if session_cookie_age is not None:
            pulumi.set(__self__, "session_cookie_age", session_cookie_age)
        if sessions_per_user is not None:
            pulumi.set(__self__, "sessions_per_user", sessions_per_user)
        if social_auth_organization_map is not None:
            pulumi.set(__self__, "social_auth_organization_map", social_auth_organization_map)
        if social_auth_team_map is not None:
            pulumi.set(__self__, "social_auth_team_map", social_auth_team_map)
        if social_auth_user_fields is not None:
            pulumi.set(__self__, "social_auth_user_fields", social_auth_user_fields)
        if social_auth_username_is_full_email is not None:
            pulumi.set(__self__, "social_auth_username_is_full_email", social_auth_username_is_full_email)

    @_builtins.property
    @pulumi.getter(name="allowMetricsForAnonymousUsers")
    def allow_metrics_for_anonymous_users(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        If true, anonymous users are allowed to poll metrics.
        """
        return pulumi.get(self, "allow_metrics_for_anonymous_users")

    @allow_metrics_for_anonymous_users.setter
    def allow_metrics_for_anonymous_users(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "allow_metrics_for_anonymous_users", value)

    @_builtins.property
    @pulumi.getter(name="allowOauth2ForExternalUsers")
    def allow_oauth2_for_external_users(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        For security reasons, users from external auth providers (LDAP, SAML, SSO, Radius, and others) are not allowed to create OAuth2 tokens. To change this behavior, enable this setting. Existing tokens will not be deleted when this setting is toggled off.
        """
        return pulumi.get(self, "allow_oauth2_for_external_users")

    @allow_oauth2_for_external_users.setter
    def allow_oauth2_for_external_users(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "allow_oauth2_for_external_users", value)

    @_builtins.property
    @pulumi.getter(name="authBasicEnabled")
    def auth_basic_enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Enable HTTP Basic Auth for the API Browser.
        """
        return pulumi.get(self, "auth_basic_enabled")

    @auth_basic_enabled.setter
    def auth_basic_enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "auth_basic_enabled", value)

    @_builtins.property
    @pulumi.getter(name="disableLocalAuth")
    def disable_local_auth(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Controls whether users are prevented from using the built-in authentication system. You probably want to do this if you are using an LDAP or SAML integration.
        """
        return pulumi.get(self, "disable_local_auth")

    @disable_local_auth.setter
    def disable_local_auth(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "disable_local_auth", value)

    @_builtins.property
    @pulumi.getter(name="localPasswordMinDigits")
    def local_password_min_digits(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Minimum number of digit characters required in a local password. 0 means no minimum
        """
        return pulumi.get(self, "local_password_min_digits")

    @local_password_min_digits.setter
    def local_password_min_digits(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "local_password_min_digits", value)

    @_builtins.property
    @pulumi.getter(name="localPasswordMinLength")
    def local_password_min_length(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Minimum number of characters required in a local password. 0 means no minimum
        """
        return pulumi.get(self, "local_password_min_length")

    @local_password_min_length.setter
    def local_password_min_length(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "local_password_min_length", value)

    @_builtins.property
    @pulumi.getter(name="localPasswordMinSpecial")
    def local_password_min_special(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Minimum number of special characters required in a local password. 0 means no minimum
        """
        return pulumi.get(self, "local_password_min_special")

    @local_password_min_special.setter
    def local_password_min_special(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "local_password_min_special", value)

    @_builtins.property
    @pulumi.getter(name="localPasswordMinUpper")
    def local_password_min_upper(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Minimum number of uppercase characters required in a local password. 0 means no minimum
        """
        return pulumi.get(self, "local_password_min_upper")

    @local_password_min_upper.setter
    def local_password_min_upper(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "local_password_min_upper", value)

    @_builtins.property
    @pulumi.getter(name="loginRedirectOverride")
    def login_redirect_override(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        URL to which unauthorized users will be redirected to log in.  If blank, users will be sent to the login page.
        """
        return pulumi.get(self, "login_redirect_override")

    @login_redirect_override.setter
    def login_redirect_override(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "login_redirect_override", value)

    @_builtins.property
    @pulumi.getter(name="oauth2Provider")
    def oauth2_provider(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Dictionary for customizing OAuth 2 timeouts, available items are `ACCESS_TOKEN_EXPIRE_SECONDS`, the duration of access tokens in the number of seconds, `AUTHORIZATION_CODE_EXPIRE_SECONDS`, the duration of authorization codes in the number of seconds, and `REFRESH_TOKEN_EXPIRE_SECONDS`, the duration of refresh tokens, after expired access tokens, in the number of seconds.
        """
        return pulumi.get(self, "oauth2_provider")

    @oauth2_provider.setter
    def oauth2_provider(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "oauth2_provider", value)

    @_builtins.property
    @pulumi.getter(name="sessionCookieAge")
    def session_cookie_age(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Number of seconds that a user is inactive before they will need to login again.
        """
        return pulumi.get(self, "session_cookie_age")

    @session_cookie_age.setter
    def session_cookie_age(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "session_cookie_age", value)

    @_builtins.property
    @pulumi.getter(name="sessionsPerUser")
    def sessions_per_user(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Maximum number of simultaneous logged in sessions a user may have. To disable enter -1.
        """
        return pulumi.get(self, "sessions_per_user")

    @sessions_per_user.setter
    def sessions_per_user(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "sessions_per_user", value)

    @_builtins.property
    @pulumi.getter(name="socialAuthOrganizationMap")
    def social_auth_organization_map(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Mapping to organization admins/users from social auth accounts. This setting
        controls which users are placed into which organizations based on their
        username and email address. Configuration details are available in the
        documentation.
        """
        return pulumi.get(self, "social_auth_organization_map")

    @social_auth_organization_map.setter
    def social_auth_organization_map(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "social_auth_organization_map", value)

    @_builtins.property
    @pulumi.getter(name="socialAuthTeamMap")
    def social_auth_team_map(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Mapping of team members (users) from social auth accounts. Configuration
        details are available in the documentation.
        """
        return pulumi.get(self, "social_auth_team_map")

    @social_auth_team_map.setter
    def social_auth_team_map(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "social_auth_team_map", value)

    @_builtins.property
    @pulumi.getter(name="socialAuthUserFields")
    def social_auth_user_fields(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        When set to an empty list `[]`, this setting prevents new user accounts from being created. Only users who have previously logged in using social auth or have a user account with a matching email address will be able to login.
        """
        return pulumi.get(self, "social_auth_user_fields")

    @social_auth_user_fields.setter
    def social_auth_user_fields(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "social_auth_user_fields", value)

    @_builtins.property
    @pulumi.getter(name="socialAuthUsernameIsFullEmail")
    def social_auth_username_is_full_email(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Enabling this setting will tell social auth to use the full Email as username instead of the full name
        """
        return pulumi.get(self, "social_auth_username_is_full_email")

    @social_auth_username_is_full_email.setter
    def social_auth_username_is_full_email(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "social_auth_username_is_full_email", value)


@pulumi.input_type
class _SettingsMiscAuthenticationState:
    def __init__(__self__, *,
                 allow_metrics_for_anonymous_users: pulumi.Input[Optional[_builtins.bool]] = None,
                 allow_oauth2_for_external_users: pulumi.Input[Optional[_builtins.bool]] = None,
                 auth_basic_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 authentication_backends: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 disable_local_auth: pulumi.Input[Optional[_builtins.bool]] = None,
                 local_password_min_digits: pulumi.Input[Optional[_builtins.float]] = None,
                 local_password_min_length: pulumi.Input[Optional[_builtins.float]] = None,
                 local_password_min_special: pulumi.Input[Optional[_builtins.float]] = None,
                 local_password_min_upper: pulumi.Input[Optional[_builtins.float]] = None,
                 login_redirect_override: pulumi.Input[Optional[_builtins.str]] = None,
                 oauth2_provider: pulumi.Input[Optional[_builtins.str]] = None,
                 session_cookie_age: pulumi.Input[Optional[_builtins.float]] = None,
                 sessions_per_user: pulumi.Input[Optional[_builtins.float]] = None,
                 social_auth_organization_map: pulumi.Input[Optional[_builtins.str]] = None,
                 social_auth_team_map: pulumi.Input[Optional[_builtins.str]] = None,
                 social_auth_user_fields: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 social_auth_username_is_full_email: pulumi.Input[Optional[_builtins.bool]] = None):
        """
        Input properties used for looking up and filtering SettingsMiscAuthentication resources.

        :param pulumi.Input[_builtins.bool] allow_metrics_for_anonymous_users: If true, anonymous users are allowed to poll metrics.
        :param pulumi.Input[_builtins.bool] allow_oauth2_for_external_users: For security reasons, users from external auth providers (LDAP, SAML, SSO, Radius, and others) are not allowed to create OAuth2 tokens. To change this behavior, enable this setting. Existing tokens will not be deleted when this setting is toggled off.
        :param pulumi.Input[_builtins.bool] auth_basic_enabled: Enable HTTP Basic Auth for the API Browser.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] authentication_backends: List of authentication backends that are enabled based on license features and other authentication settings.
        :param pulumi.Input[_builtins.bool] disable_local_auth: Controls whether users are prevented from using the built-in authentication system. You probably want to do this if you are using an LDAP or SAML integration.
        :param pulumi.Input[_builtins.float] local_password_min_digits: Minimum number of digit characters required in a local password. 0 means no minimum
        :param pulumi.Input[_builtins.float] local_password_min_length: Minimum number of characters required in a local password. 0 means no minimum
        :param pulumi.Input[_builtins.float] local_password_min_special: Minimum number of special characters required in a local password. 0 means no minimum
        :param pulumi.Input[_builtins.float] local_password_min_upper: Minimum number of uppercase characters required in a local password. 0 means no minimum
        :param pulumi.Input[_builtins.str] login_redirect_override: URL to which unauthorized users will be redirected to log in.  If blank, users will be sent to the login page.
        :param pulumi.Input[_builtins.str] oauth2_provider: Dictionary for customizing OAuth 2 timeouts, available items are `ACCESS_TOKEN_EXPIRE_SECONDS`, the duration of access tokens in the number of seconds, `AUTHORIZATION_CODE_EXPIRE_SECONDS`, the duration of authorization codes in the number of seconds, and `REFRESH_TOKEN_EXPIRE_SECONDS`, the duration of refresh tokens, after expired access tokens, in the number of seconds.
        :param pulumi.Input[_builtins.float] session_cookie_age: Number of seconds that a user is inactive before they will need to login again.
        :param pulumi.Input[_builtins.float] sessions_per_user: Maximum number of simultaneous logged in sessions a user may have. To disable enter -1.
        :param pulumi.Input[_builtins.str] social_auth_organization_map: Mapping to organization admins/users from social auth accounts. This setting
               controls which users are placed into which organizations based on their
               username and email address. Configuration details are available in the
               documentation.
        :param pulumi.Input[_builtins.str] social_auth_team_map: Mapping of team members (users) from social auth accounts. Configuration
               details are available in the documentation.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] social_auth_user_fields: When set to an empty list `[]`, this setting prevents new user accounts from being created. Only users who have previously logged in using social auth or have a user account with a matching email address will be able to login.
        :param pulumi.Input[_builtins.bool] social_auth_username_is_full_email: Enabling this setting will tell social auth to use the full Email as username instead of the full name
        """
        if allow_metrics_for_anonymous_users is not None:
            pulumi.set(__self__, "allow_metrics_for_anonymous_users", allow_metrics_for_anonymous_users)
        if allow_oauth2_for_external_users is not None:
            pulumi.set(__self__, "allow_oauth2_for_external_users", allow_oauth2_for_external_users)
        if auth_basic_enabled is not None:
            pulumi.set(__self__, "auth_basic_enabled", auth_basic_enabled)
        if authentication_backends is not None:
            pulumi.set(__self__, "authentication_backends", authentication_backends)
        if disable_local_auth is not None:
            pulumi.set(__self__, "disable_local_auth", disable_local_auth)
        if local_password_min_digits is not None:
            pulumi.set(__self__, "local_password_min_digits", local_password_min_digits)
        if local_password_min_length is not None:
            pulumi.set(__self__, "local_password_min_length", local_password_min_length)
        if local_password_min_special is not None:
            pulumi.set(__self__, "local_password_min_special", local_password_min_special)
        if local_password_min_upper is not None:
            pulumi.set(__self__, "local_password_min_upper", local_password_min_upper)
        if login_redirect_override is not None:
            pulumi.set(__self__, "login_redirect_override", login_redirect_override)
        if oauth2_provider is not None:
            pulumi.set(__self__, "oauth2_provider", oauth2_provider)
        if session_cookie_age is not None:
            pulumi.set(__self__, "session_cookie_age", session_cookie_age)
        if sessions_per_user is not None:
            pulumi.set(__self__, "sessions_per_user", sessions_per_user)
        if social_auth_organization_map is not None:
            pulumi.set(__self__, "social_auth_organization_map", social_auth_organization_map)
        if social_auth_team_map is not None:
            pulumi.set(__self__, "social_auth_team_map", social_auth_team_map)
        if social_auth_user_fields is not None:
            pulumi.set(__self__, "social_auth_user_fields", social_auth_user_fields)
        if social_auth_username_is_full_email is not None:
            pulumi.set(__self__, "social_auth_username_is_full_email", social_auth_username_is_full_email)

    @_builtins.property
    @pulumi.getter(name="allowMetricsForAnonymousUsers")
    def allow_metrics_for_anonymous_users(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        If true, anonymous users are allowed to poll metrics.
        """
        return pulumi.get(self, "allow_metrics_for_anonymous_users")

    @allow_metrics_for_anonymous_users.setter
    def allow_metrics_for_anonymous_users(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "allow_metrics_for_anonymous_users", value)

    @_builtins.property
    @pulumi.getter(name="allowOauth2ForExternalUsers")
    def allow_oauth2_for_external_users(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        For security reasons, users from external auth providers (LDAP, SAML, SSO, Radius, and others) are not allowed to create OAuth2 tokens. To change this behavior, enable this setting. Existing tokens will not be deleted when this setting is toggled off.
        """
        return pulumi.get(self, "allow_oauth2_for_external_users")

    @allow_oauth2_for_external_users.setter
    def allow_oauth2_for_external_users(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "allow_oauth2_for_external_users", value)

    @_builtins.property
    @pulumi.getter(name="authBasicEnabled")
    def auth_basic_enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Enable HTTP Basic Auth for the API Browser.
        """
        return pulumi.get(self, "auth_basic_enabled")

    @auth_basic_enabled.setter
    def auth_basic_enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "auth_basic_enabled", value)

    @_builtins.property
    @pulumi.getter(name="authenticationBackends")
    def authentication_backends(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of authentication backends that are enabled based on license features and other authentication settings.
        """
        return pulumi.get(self, "authentication_backends")

    @authentication_backends.setter
    def authentication_backends(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "authentication_backends", value)

    @_builtins.property
    @pulumi.getter(name="disableLocalAuth")
    def disable_local_auth(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Controls whether users are prevented from using the built-in authentication system. You probably want to do this if you are using an LDAP or SAML integration.
        """
        return pulumi.get(self, "disable_local_auth")

    @disable_local_auth.setter
    def disable_local_auth(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "disable_local_auth", value)

    @_builtins.property
    @pulumi.getter(name="localPasswordMinDigits")
    def local_password_min_digits(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Minimum number of digit characters required in a local password. 0 means no minimum
        """
        return pulumi.get(self, "local_password_min_digits")

    @local_password_min_digits.setter
    def local_password_min_digits(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "local_password_min_digits", value)

    @_builtins.property
    @pulumi.getter(name="localPasswordMinLength")
    def local_password_min_length(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Minimum number of characters required in a local password. 0 means no minimum
        """
        return pulumi.get(self, "local_password_min_length")

    @local_password_min_length.setter
    def local_password_min_length(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "local_password_min_length", value)

    @_builtins.property
    @pulumi.getter(name="localPasswordMinSpecial")
    def local_password_min_special(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Minimum number of special characters required in a local password. 0 means no minimum
        """
        return pulumi.get(self, "local_password_min_special")

    @local_password_min_special.setter
    def local_password_min_special(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "local_password_min_special", value)

    @_builtins.property
    @pulumi.getter(name="localPasswordMinUpper")
    def local_password_min_upper(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Minimum number of uppercase characters required in a local password. 0 means no minimum
        """
        return pulumi.get(self, "local_password_min_upper")

    @local_password_min_upper.setter
    def local_password_min_upper(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "local_password_min_upper", value)

    @_builtins.property
    @pulumi.getter(name="loginRedirectOverride")
    def login_redirect_override(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        URL to which unauthorized users will be redirected to log in.  If blank, users will be sent to the login page.
        """
        return pulumi.get(self, "login_redirect_override")

    @login_redirect_override.setter
    def login_redirect_override(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "login_redirect_override", value)

    @_builtins.property
    @pulumi.getter(name="oauth2Provider")
    def oauth2_provider(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Dictionary for customizing OAuth 2 timeouts, available items are `ACCESS_TOKEN_EXPIRE_SECONDS`, the duration of access tokens in the number of seconds, `AUTHORIZATION_CODE_EXPIRE_SECONDS`, the duration of authorization codes in the number of seconds, and `REFRESH_TOKEN_EXPIRE_SECONDS`, the duration of refresh tokens, after expired access tokens, in the number of seconds.
        """
        return pulumi.get(self, "oauth2_provider")

    @oauth2_provider.setter
    def oauth2_provider(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "oauth2_provider", value)

    @_builtins.property
    @pulumi.getter(name="sessionCookieAge")
    def session_cookie_age(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Number of seconds that a user is inactive before they will need to login again.
        """
        return pulumi.get(self, "session_cookie_age")

    @session_cookie_age.setter
    def session_cookie_age(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "session_cookie_age", value)

    @_builtins.property
    @pulumi.getter(name="sessionsPerUser")
    def sessions_per_user(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Maximum number of simultaneous logged in sessions a user may have. To disable enter -1.
        """
        return pulumi.get(self, "sessions_per_user")

    @sessions_per_user.setter
    def sessions_per_user(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "sessions_per_user", value)

    @_builtins.property
    @pulumi.getter(name="socialAuthOrganizationMap")
    def social_auth_organization_map(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Mapping to organization admins/users from social auth accounts. This setting
        controls which users are placed into which organizations based on their
        username and email address. Configuration details are available in the
        documentation.
        """
        return pulumi.get(self, "social_auth_organization_map")

    @social_auth_organization_map.setter
    def social_auth_organization_map(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "social_auth_organization_map", value)

    @_builtins.property
    @pulumi.getter(name="socialAuthTeamMap")
    def social_auth_team_map(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Mapping of team members (users) from social auth accounts. Configuration
        details are available in the documentation.
        """
        return pulumi.get(self, "social_auth_team_map")

    @social_auth_team_map.setter
    def social_auth_team_map(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "social_auth_team_map", value)

    @_builtins.property
    @pulumi.getter(name="socialAuthUserFields")
    def social_auth_user_fields(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        When set to an empty list `[]`, this setting prevents new user accounts from being created. Only users who have previously logged in using social auth or have a user account with a matching email address will be able to login.
        """
        return pulumi.get(self, "social_auth_user_fields")

    @social_auth_user_fields.setter
    def social_auth_user_fields(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "social_auth_user_fields", value)

    @_builtins.property
    @pulumi.getter(name="socialAuthUsernameIsFullEmail")
    def social_auth_username_is_full_email(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Enabling this setting will tell social auth to use the full Email as username instead of the full name
        """
        return pulumi.get(self, "social_auth_username_is_full_email")

    @social_auth_username_is_full_email.setter
    def social_auth_username_is_full_email(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "social_auth_username_is_full_email", value)


@pulumi.type_token("awx:index/settingsMiscAuthentication:SettingsMiscAuthentication")
class SettingsMiscAuthentication(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allow_metrics_for_anonymous_users: pulumi.Input[Optional[_builtins.bool]] = None,
                 allow_oauth2_for_external_users: pulumi.Input[Optional[_builtins.bool]] = None,
                 auth_basic_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 disable_local_auth: pulumi.Input[Optional[_builtins.bool]] = None,
                 local_password_min_digits: pulumi.Input[Optional[_builtins.float]] = None,
                 local_password_min_length: pulumi.Input[Optional[_builtins.float]] = None,
                 local_password_min_special: pulumi.Input[Optional[_builtins.float]] = None,
                 local_password_min_upper: pulumi.Input[Optional[_builtins.float]] = None,
                 login_redirect_override: pulumi.Input[Optional[_builtins.str]] = None,
                 oauth2_provider: pulumi.Input[Optional[_builtins.str]] = None,
                 session_cookie_age: pulumi.Input[Optional[_builtins.float]] = None,
                 sessions_per_user: pulumi.Input[Optional[_builtins.float]] = None,
                 social_auth_organization_map: pulumi.Input[Optional[_builtins.str]] = None,
                 social_auth_team_map: pulumi.Input[Optional[_builtins.str]] = None,
                 social_auth_user_fields: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 social_auth_username_is_full_email: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        """
        Create a SettingsMiscAuthentication resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] allow_metrics_for_anonymous_users: If true, anonymous users are allowed to poll metrics.
        :param pulumi.Input[_builtins.bool] allow_oauth2_for_external_users: For security reasons, users from external auth providers (LDAP, SAML, SSO, Radius, and others) are not allowed to create OAuth2 tokens. To change this behavior, enable this setting. Existing tokens will not be deleted when this setting is toggled off.
        :param pulumi.Input[_builtins.bool] auth_basic_enabled: Enable HTTP Basic Auth for the API Browser.
        :param pulumi.Input[_builtins.bool] disable_local_auth: Controls whether users are prevented from using the built-in authentication system. You probably want to do this if you are using an LDAP or SAML integration.
        :param pulumi.Input[_builtins.float] local_password_min_digits: Minimum number of digit characters required in a local password. 0 means no minimum
        :param pulumi.Input[_builtins.float] local_password_min_length: Minimum number of characters required in a local password. 0 means no minimum
        :param pulumi.Input[_builtins.float] local_password_min_special: Minimum number of special characters required in a local password. 0 means no minimum
        :param pulumi.Input[_builtins.float] local_password_min_upper: Minimum number of uppercase characters required in a local password. 0 means no minimum
        :param pulumi.Input[_builtins.str] login_redirect_override: URL to which unauthorized users will be redirected to log in.  If blank, users will be sent to the login page.
        :param pulumi.Input[_builtins.str] oauth2_provider: Dictionary for customizing OAuth 2 timeouts, available items are `ACCESS_TOKEN_EXPIRE_SECONDS`, the duration of access tokens in the number of seconds, `AUTHORIZATION_CODE_EXPIRE_SECONDS`, the duration of authorization codes in the number of seconds, and `REFRESH_TOKEN_EXPIRE_SECONDS`, the duration of refresh tokens, after expired access tokens, in the number of seconds.
        :param pulumi.Input[_builtins.float] session_cookie_age: Number of seconds that a user is inactive before they will need to login again.
        :param pulumi.Input[_builtins.float] sessions_per_user: Maximum number of simultaneous logged in sessions a user may have. To disable enter -1.
        :param pulumi.Input[_builtins.str] social_auth_organization_map: Mapping to organization admins/users from social auth accounts. This setting
               controls which users are placed into which organizations based on their
               username and email address. Configuration details are available in the
               documentation.
        :param pulumi.Input[_builtins.str] social_auth_team_map: Mapping of team members (users) from social auth accounts. Configuration
               details are available in the documentation.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] social_auth_user_fields: When set to an empty list `[]`, this setting prevents new user accounts from being created. Only users who have previously logged in using social auth or have a user account with a matching email address will be able to login.
        :param pulumi.Input[_builtins.bool] social_auth_username_is_full_email: Enabling this setting will tell social auth to use the full Email as username instead of the full name
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[SettingsMiscAuthenticationArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a SettingsMiscAuthentication resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param SettingsMiscAuthenticationArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SettingsMiscAuthenticationArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allow_metrics_for_anonymous_users: pulumi.Input[Optional[_builtins.bool]] = None,
                 allow_oauth2_for_external_users: pulumi.Input[Optional[_builtins.bool]] = None,
                 auth_basic_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 disable_local_auth: pulumi.Input[Optional[_builtins.bool]] = None,
                 local_password_min_digits: pulumi.Input[Optional[_builtins.float]] = None,
                 local_password_min_length: pulumi.Input[Optional[_builtins.float]] = None,
                 local_password_min_special: pulumi.Input[Optional[_builtins.float]] = None,
                 local_password_min_upper: pulumi.Input[Optional[_builtins.float]] = None,
                 login_redirect_override: pulumi.Input[Optional[_builtins.str]] = None,
                 oauth2_provider: pulumi.Input[Optional[_builtins.str]] = None,
                 session_cookie_age: pulumi.Input[Optional[_builtins.float]] = None,
                 sessions_per_user: pulumi.Input[Optional[_builtins.float]] = None,
                 social_auth_organization_map: pulumi.Input[Optional[_builtins.str]] = None,
                 social_auth_team_map: pulumi.Input[Optional[_builtins.str]] = None,
                 social_auth_user_fields: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 social_auth_username_is_full_email: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SettingsMiscAuthenticationArgs.__new__(SettingsMiscAuthenticationArgs)

            __props__.__dict__["allow_metrics_for_anonymous_users"] = allow_metrics_for_anonymous_users
            __props__.__dict__["allow_oauth2_for_external_users"] = allow_oauth2_for_external_users
            __props__.__dict__["auth_basic_enabled"] = auth_basic_enabled
            __props__.__dict__["disable_local_auth"] = disable_local_auth
            __props__.__dict__["local_password_min_digits"] = local_password_min_digits
            __props__.__dict__["local_password_min_length"] = local_password_min_length
            __props__.__dict__["local_password_min_special"] = local_password_min_special
            __props__.__dict__["local_password_min_upper"] = local_password_min_upper
            __props__.__dict__["login_redirect_override"] = login_redirect_override
            __props__.__dict__["oauth2_provider"] = oauth2_provider
            __props__.__dict__["session_cookie_age"] = session_cookie_age
            __props__.__dict__["sessions_per_user"] = sessions_per_user
            __props__.__dict__["social_auth_organization_map"] = social_auth_organization_map
            __props__.__dict__["social_auth_team_map"] = social_auth_team_map
            __props__.__dict__["social_auth_user_fields"] = social_auth_user_fields
            __props__.__dict__["social_auth_username_is_full_email"] = social_auth_username_is_full_email
            __props__.__dict__["authentication_backends"] = None
        super(SettingsMiscAuthentication, __self__).__init__(
            'awx:index/settingsMiscAuthentication:SettingsMiscAuthentication',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            allow_metrics_for_anonymous_users: pulumi.Input[Optional[_builtins.bool]] = None,
            allow_oauth2_for_external_users: pulumi.Input[Optional[_builtins.bool]] = None,
            auth_basic_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
            authentication_backends: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            disable_local_auth: pulumi.Input[Optional[_builtins.bool]] = None,
            local_password_min_digits: pulumi.Input[Optional[_builtins.float]] = None,
            local_password_min_length: pulumi.Input[Optional[_builtins.float]] = None,
            local_password_min_special: pulumi.Input[Optional[_builtins.float]] = None,
            local_password_min_upper: pulumi.Input[Optional[_builtins.float]] = None,
            login_redirect_override: pulumi.Input[Optional[_builtins.str]] = None,
            oauth2_provider: pulumi.Input[Optional[_builtins.str]] = None,
            session_cookie_age: pulumi.Input[Optional[_builtins.float]] = None,
            sessions_per_user: pulumi.Input[Optional[_builtins.float]] = None,
            social_auth_organization_map: pulumi.Input[Optional[_builtins.str]] = None,
            social_auth_team_map: pulumi.Input[Optional[_builtins.str]] = None,
            social_auth_user_fields: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            social_auth_username_is_full_email: pulumi.Input[Optional[_builtins.bool]] = None) -> 'SettingsMiscAuthentication':
        """
        Get an existing SettingsMiscAuthentication resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] allow_metrics_for_anonymous_users: If true, anonymous users are allowed to poll metrics.
        :param pulumi.Input[_builtins.bool] allow_oauth2_for_external_users: For security reasons, users from external auth providers (LDAP, SAML, SSO, Radius, and others) are not allowed to create OAuth2 tokens. To change this behavior, enable this setting. Existing tokens will not be deleted when this setting is toggled off.
        :param pulumi.Input[_builtins.bool] auth_basic_enabled: Enable HTTP Basic Auth for the API Browser.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] authentication_backends: List of authentication backends that are enabled based on license features and other authentication settings.
        :param pulumi.Input[_builtins.bool] disable_local_auth: Controls whether users are prevented from using the built-in authentication system. You probably want to do this if you are using an LDAP or SAML integration.
        :param pulumi.Input[_builtins.float] local_password_min_digits: Minimum number of digit characters required in a local password. 0 means no minimum
        :param pulumi.Input[_builtins.float] local_password_min_length: Minimum number of characters required in a local password. 0 means no minimum
        :param pulumi.Input[_builtins.float] local_password_min_special: Minimum number of special characters required in a local password. 0 means no minimum
        :param pulumi.Input[_builtins.float] local_password_min_upper: Minimum number of uppercase characters required in a local password. 0 means no minimum
        :param pulumi.Input[_builtins.str] login_redirect_override: URL to which unauthorized users will be redirected to log in.  If blank, users will be sent to the login page.
        :param pulumi.Input[_builtins.str] oauth2_provider: Dictionary for customizing OAuth 2 timeouts, available items are `ACCESS_TOKEN_EXPIRE_SECONDS`, the duration of access tokens in the number of seconds, `AUTHORIZATION_CODE_EXPIRE_SECONDS`, the duration of authorization codes in the number of seconds, and `REFRESH_TOKEN_EXPIRE_SECONDS`, the duration of refresh tokens, after expired access tokens, in the number of seconds.
        :param pulumi.Input[_builtins.float] session_cookie_age: Number of seconds that a user is inactive before they will need to login again.
        :param pulumi.Input[_builtins.float] sessions_per_user: Maximum number of simultaneous logged in sessions a user may have. To disable enter -1.
        :param pulumi.Input[_builtins.str] social_auth_organization_map: Mapping to organization admins/users from social auth accounts. This setting
               controls which users are placed into which organizations based on their
               username and email address. Configuration details are available in the
               documentation.
        :param pulumi.Input[_builtins.str] social_auth_team_map: Mapping of team members (users) from social auth accounts. Configuration
               details are available in the documentation.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] social_auth_user_fields: When set to an empty list `[]`, this setting prevents new user accounts from being created. Only users who have previously logged in using social auth or have a user account with a matching email address will be able to login.
        :param pulumi.Input[_builtins.bool] social_auth_username_is_full_email: Enabling this setting will tell social auth to use the full Email as username instead of the full name
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _SettingsMiscAuthenticationState.__new__(_SettingsMiscAuthenticationState)

        __props__.__dict__["allow_metrics_for_anonymous_users"] = allow_metrics_for_anonymous_users
        __props__.__dict__["allow_oauth2_for_external_users"] = allow_oauth2_for_external_users
        __props__.__dict__["auth_basic_enabled"] = auth_basic_enabled
        __props__.__dict__["authentication_backends"] = authentication_backends
        __props__.__dict__["disable_local_auth"] = disable_local_auth
        __props__.__dict__["local_password_min_digits"] = local_password_min_digits
        __props__.__dict__["local_password_min_length"] = local_password_min_length
        __props__.__dict__["local_password_min_special"] = local_password_min_special
        __props__.__dict__["local_password_min_upper"] = local_password_min_upper
        __props__.__dict__["login_redirect_override"] = login_redirect_override
        __props__.__dict__["oauth2_provider"] = oauth2_provider
        __props__.__dict__["session_cookie_age"] = session_cookie_age
        __props__.__dict__["sessions_per_user"] = sessions_per_user
        __props__.__dict__["social_auth_organization_map"] = social_auth_organization_map
        __props__.__dict__["social_auth_team_map"] = social_auth_team_map
        __props__.__dict__["social_auth_user_fields"] = social_auth_user_fields
        __props__.__dict__["social_auth_username_is_full_email"] = social_auth_username_is_full_email
        return SettingsMiscAuthentication(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="allowMetricsForAnonymousUsers")
    def allow_metrics_for_anonymous_users(self) -> pulumi.Output[_builtins.bool]:
        """
        If true, anonymous users are allowed to poll metrics.
        """
        return pulumi.get(self, "allow_metrics_for_anonymous_users")

    @_builtins.property
    @pulumi.getter(name="allowOauth2ForExternalUsers")
    def allow_oauth2_for_external_users(self) -> pulumi.Output[_builtins.bool]:
        """
        For security reasons, users from external auth providers (LDAP, SAML, SSO, Radius, and others) are not allowed to create OAuth2 tokens. To change this behavior, enable this setting. Existing tokens will not be deleted when this setting is toggled off.
        """
        return pulumi.get(self, "allow_oauth2_for_external_users")

    @_builtins.property
    @pulumi.getter(name="authBasicEnabled")
    def auth_basic_enabled(self) -> pulumi.Output[_builtins.bool]:
        """
        Enable HTTP Basic Auth for the API Browser.
        """
        return pulumi.get(self, "auth_basic_enabled")

    @_builtins.property
    @pulumi.getter(name="authenticationBackends")
    def authentication_backends(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        List of authentication backends that are enabled based on license features and other authentication settings.
        """
        return pulumi.get(self, "authentication_backends")

    @_builtins.property
    @pulumi.getter(name="disableLocalAuth")
    def disable_local_auth(self) -> pulumi.Output[_builtins.bool]:
        """
        Controls whether users are prevented from using the built-in authentication system. You probably want to do this if you are using an LDAP or SAML integration.
        """
        return pulumi.get(self, "disable_local_auth")

    @_builtins.property
    @pulumi.getter(name="localPasswordMinDigits")
    def local_password_min_digits(self) -> pulumi.Output[_builtins.float]:
        """
        Minimum number of digit characters required in a local password. 0 means no minimum
        """
        return pulumi.get(self, "local_password_min_digits")

    @_builtins.property
    @pulumi.getter(name="localPasswordMinLength")
    def local_password_min_length(self) -> pulumi.Output[_builtins.float]:
        """
        Minimum number of characters required in a local password. 0 means no minimum
        """
        return pulumi.get(self, "local_password_min_length")

    @_builtins.property
    @pulumi.getter(name="localPasswordMinSpecial")
    def local_password_min_special(self) -> pulumi.Output[_builtins.float]:
        """
        Minimum number of special characters required in a local password. 0 means no minimum
        """
        return pulumi.get(self, "local_password_min_special")

    @_builtins.property
    @pulumi.getter(name="localPasswordMinUpper")
    def local_password_min_upper(self) -> pulumi.Output[_builtins.float]:
        """
        Minimum number of uppercase characters required in a local password. 0 means no minimum
        """
        return pulumi.get(self, "local_password_min_upper")

    @_builtins.property
    @pulumi.getter(name="loginRedirectOverride")
    def login_redirect_override(self) -> pulumi.Output[_builtins.str]:
        """
        URL to which unauthorized users will be redirected to log in.  If blank, users will be sent to the login page.
        """
        return pulumi.get(self, "login_redirect_override")

    @_builtins.property
    @pulumi.getter(name="oauth2Provider")
    def oauth2_provider(self) -> pulumi.Output[_builtins.str]:
        """
        Dictionary for customizing OAuth 2 timeouts, available items are `ACCESS_TOKEN_EXPIRE_SECONDS`, the duration of access tokens in the number of seconds, `AUTHORIZATION_CODE_EXPIRE_SECONDS`, the duration of authorization codes in the number of seconds, and `REFRESH_TOKEN_EXPIRE_SECONDS`, the duration of refresh tokens, after expired access tokens, in the number of seconds.
        """
        return pulumi.get(self, "oauth2_provider")

    @_builtins.property
    @pulumi.getter(name="sessionCookieAge")
    def session_cookie_age(self) -> pulumi.Output[_builtins.float]:
        """
        Number of seconds that a user is inactive before they will need to login again.
        """
        return pulumi.get(self, "session_cookie_age")

    @_builtins.property
    @pulumi.getter(name="sessionsPerUser")
    def sessions_per_user(self) -> pulumi.Output[_builtins.float]:
        """
        Maximum number of simultaneous logged in sessions a user may have. To disable enter -1.
        """
        return pulumi.get(self, "sessions_per_user")

    @_builtins.property
    @pulumi.getter(name="socialAuthOrganizationMap")
    def social_auth_organization_map(self) -> pulumi.Output[_builtins.str]:
        """
        Mapping to organization admins/users from social auth accounts. This setting
        controls which users are placed into which organizations based on their
        username and email address. Configuration details are available in the
        documentation.
        """
        return pulumi.get(self, "social_auth_organization_map")

    @_builtins.property
    @pulumi.getter(name="socialAuthTeamMap")
    def social_auth_team_map(self) -> pulumi.Output[_builtins.str]:
        """
        Mapping of team members (users) from social auth accounts. Configuration
        details are available in the documentation.
        """
        return pulumi.get(self, "social_auth_team_map")

    @_builtins.property
    @pulumi.getter(name="socialAuthUserFields")
    def social_auth_user_fields(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        When set to an empty list `[]`, this setting prevents new user accounts from being created. Only users who have previously logged in using social auth or have a user account with a matching email address will be able to login.
        """
        return pulumi.get(self, "social_auth_user_fields")

    @_builtins.property
    @pulumi.getter(name="socialAuthUsernameIsFullEmail")
    def social_auth_username_is_full_email(self) -> pulumi.Output[_builtins.bool]:
        """
        Enabling this setting will tell social auth to use the full Email as username instead of the full name
        """
        return pulumi.get(self, "social_auth_username_is_full_email")

