# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['WorkflowJobTemplateSurveySpecArgs', 'WorkflowJobTemplateSurveySpec']

@pulumi.input_type
class WorkflowJobTemplateSurveySpecArgs:
    def __init__(__self__, *,
                 spec: pulumi.Input[_builtins.str],
                 workflow_job_template_id: pulumi.Input[_builtins.float]):
        """
        The set of arguments for constructing a WorkflowJobTemplateSurveySpec resource.

        :param pulumi.Input[_builtins.str] spec: The survey spec for this WorkflowJobTemplate.
        :param pulumi.Input[_builtins.float] workflow_job_template_id: Database ID for this WorkflowJobTemplate.
        """
        pulumi.set(__self__, "spec", spec)
        pulumi.set(__self__, "workflow_job_template_id", workflow_job_template_id)

    @_builtins.property
    @pulumi.getter
    def spec(self) -> pulumi.Input[_builtins.str]:
        """
        The survey spec for this WorkflowJobTemplate.
        """
        return pulumi.get(self, "spec")

    @spec.setter
    def spec(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "spec", value)

    @_builtins.property
    @pulumi.getter(name="workflowJobTemplateId")
    def workflow_job_template_id(self) -> pulumi.Input[_builtins.float]:
        """
        Database ID for this WorkflowJobTemplate.
        """
        return pulumi.get(self, "workflow_job_template_id")

    @workflow_job_template_id.setter
    def workflow_job_template_id(self, value: pulumi.Input[_builtins.float]):
        pulumi.set(self, "workflow_job_template_id", value)


@pulumi.input_type
class _WorkflowJobTemplateSurveySpecState:
    def __init__(__self__, *,
                 spec: pulumi.Input[Optional[_builtins.str]] = None,
                 workflow_job_template_id: pulumi.Input[Optional[_builtins.float]] = None):
        """
        Input properties used for looking up and filtering WorkflowJobTemplateSurveySpec resources.

        :param pulumi.Input[_builtins.str] spec: The survey spec for this WorkflowJobTemplate.
        :param pulumi.Input[_builtins.float] workflow_job_template_id: Database ID for this WorkflowJobTemplate.
        """
        if spec is not None:
            pulumi.set(__self__, "spec", spec)
        if workflow_job_template_id is not None:
            pulumi.set(__self__, "workflow_job_template_id", workflow_job_template_id)

    @_builtins.property
    @pulumi.getter
    def spec(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The survey spec for this WorkflowJobTemplate.
        """
        return pulumi.get(self, "spec")

    @spec.setter
    def spec(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "spec", value)

    @_builtins.property
    @pulumi.getter(name="workflowJobTemplateId")
    def workflow_job_template_id(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Database ID for this WorkflowJobTemplate.
        """
        return pulumi.get(self, "workflow_job_template_id")

    @workflow_job_template_id.setter
    def workflow_job_template_id(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "workflow_job_template_id", value)


@pulumi.type_token("awx:index/workflowJobTemplateSurveySpec:WorkflowJobTemplateSurveySpec")
class WorkflowJobTemplateSurveySpec(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 spec: pulumi.Input[Optional[_builtins.str]] = None,
                 workflow_job_template_id: pulumi.Input[Optional[_builtins.float]] = None,
                 __props__=None):
        """
        Create a WorkflowJobTemplateSurveySpec resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] spec: The survey spec for this WorkflowJobTemplate.
        :param pulumi.Input[_builtins.float] workflow_job_template_id: Database ID for this WorkflowJobTemplate.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: WorkflowJobTemplateSurveySpecArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a WorkflowJobTemplateSurveySpec resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param WorkflowJobTemplateSurveySpecArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(WorkflowJobTemplateSurveySpecArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 spec: pulumi.Input[Optional[_builtins.str]] = None,
                 workflow_job_template_id: pulumi.Input[Optional[_builtins.float]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = WorkflowJobTemplateSurveySpecArgs.__new__(WorkflowJobTemplateSurveySpecArgs)

            if spec is None and not opts.urn:
                raise TypeError("Missing required property 'spec'")
            __props__.__dict__["spec"] = spec
            if workflow_job_template_id is None and not opts.urn:
                raise TypeError("Missing required property 'workflow_job_template_id'")
            __props__.__dict__["workflow_job_template_id"] = workflow_job_template_id
        super(WorkflowJobTemplateSurveySpec, __self__).__init__(
            'awx:index/workflowJobTemplateSurveySpec:WorkflowJobTemplateSurveySpec',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            spec: pulumi.Input[Optional[_builtins.str]] = None,
            workflow_job_template_id: pulumi.Input[Optional[_builtins.float]] = None) -> 'WorkflowJobTemplateSurveySpec':
        """
        Get an existing WorkflowJobTemplateSurveySpec resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] spec: The survey spec for this WorkflowJobTemplate.
        :param pulumi.Input[_builtins.float] workflow_job_template_id: Database ID for this WorkflowJobTemplate.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _WorkflowJobTemplateSurveySpecState.__new__(_WorkflowJobTemplateSurveySpecState)

        __props__.__dict__["spec"] = spec
        __props__.__dict__["workflow_job_template_id"] = workflow_job_template_id
        return WorkflowJobTemplateSurveySpec(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def spec(self) -> pulumi.Output[_builtins.str]:
        """
        The survey spec for this WorkflowJobTemplate.
        """
        return pulumi.get(self, "spec")

    @_builtins.property
    @pulumi.getter(name="workflowJobTemplateId")
    def workflow_job_template_id(self) -> pulumi.Output[_builtins.float]:
        """
        Database ID for this WorkflowJobTemplate.
        """
        return pulumi.get(self, "workflow_job_template_id")

